### PR TITLE
Fix Contents API fetch documentation of the `content` default

### LINKED ISSUE #18380: Contents api implementation does not fetch file content by default
## Description

In https://github.com/jupyterlab/jupyterlab/blob/171fc4e1b59f2f778252f16f8c2d22a8c06029d9/packages/services/src/contents/index.ts#L184-L189 the `contents` option is documented as defaulting to true.

However, in the code at https://github.com/jupyterlab/jupyterlab/blob/171fc4e1b59f2f778252f16f8c2d22a8c06029d9/packages/services/src/contents/index.ts#L1785, if `content` is not specified (i.e., is undefined), then we default to 0, i.e., not fetching the content. We only fetch the content if `options.content` is truthy.

## Context

This came up when investigating https://github.com/jupyterlab/jupyterlab/pull/18379

### PR DESCRIPTION
**Pull request by ceasermikes002**
The implementation didn't respect the documented default of true for 
the content option. Changed the check to properly default to fetching 
content unless explicitly set to false.

Fixes #18380

### CODE REVIEW

**Comment by jasongrout** [comment]
Could you do a quick dive into the history of this implementation? I'm curious when it stopped following the documented default - if it's been a very long time, it may be better to change the documentation rather than the implementation.

**Comment by ceasermikes002** [comment]
Hey, so based on my investigation the bug was introduced Dec. 30th 2024,  (commit 4a6bc6c573e, PR #17092 - "Add Content Provider API"). The fix Is correct because the documentation was added in the same commit that introduced the bug, indicating this was the intended behaviour from the start.

**Comment by krassowski** [comment]
> Hey, so based on my investigation the bug was introduced Dec. 30th 2024, (commit https://github.com/jupyterlab/jupyterlab/commit/4a6bc6c573e0b3a10b1b23edcf0894aff42aa9c0, PR https://github.com/jupyterlab/jupyterlab/pull/17092 - "Add Content Provider API").

That's not accurate - that commit barely moved the implementation from one place to another

image

image

**Comment by ceasermikes002** [comment]
Hey, so you were correct. Sorry about that.
The bug was originally introduced in the initial import commit bd9c7df74d (March 2017) in the Drive class and persisted for  approx. 7 years. So In your commit, 4a6bc6c573e (Dec 30, 2024) when the code was refactored to the RestContentProvider class
Finally fixed: In my commit e25ae4650b

**Comment by krassowski** [comment]
I think that in that case we should update documentation, not code. Changing this has very little advantage and would likely break a lot of code.

**Comment by jasongrout** [comment]
Just to verify, here is the code in bd9c7df74d4b197ffa5e8823577160629f46e3c2 from 2017:

https://github.com/jupyterlab/jupyterlab/blob/bd9c7df74d4b197ffa5e8823577160629f46e3c2/packages/services/src/contents/index.ts#L432

So I guess it's always been this way. I agree that it would be better to change the documentation for this.

**Comment by jasongrout** [comment]
Tracking down where the default true came from, it looks like the jupyter server rest api has a default of sending all of the contents:

https://github.com/jupyter-server/jupyter_server/blob/df624c0c24f12d7c801eca96c9cf1fc030278a4c/jupyter_server/services/contents/handlers.py#L136

So: we likely copied the Jupyter server api behavior in the docs, but made an error in the implementation in 2017 that effectively flipped the default to false. And now our frontend code relies on the default being false.

So the original issue at https://github.com/jupyterlab/jupyterlab/issues/15153 probably assumed that the get fetched the contents, but in reality it didn't?

File: packages/services/src/contents/index.ts [hunk 1]
```diff
@@ -1782,7 +1782,7 @@ export class RestContentProvider implements IContentProvider {
       if (options.type === 'notebook') {
         delete options['format'];
       }
-      const content = options.content ? '1' : '0';
+      const content = options.content !== false ? '1' : '0';
```
Comment (jasongrout) [inline packages/services/src/contents/index.ts]: Given the investigation and discussion in the issue, let's instead rewrite the documentation for the options to say the default is to not get the contents

Comment (ceasermikes002) [reply packages/services/src/contents/index.ts]: Agreed 👍

**Comment by ceasermikes002** [comment]
@jasongrout, after reverting my changes I can close the PR right?

**Comment by jasongrout** [comment]
> [ceasermikes002](https://github.com/ceasermikes002) requested a review from [jasongrout](https://github.com/jasongrout) [19 minutes ago](https://github.com/jupyterlab/jupyterlab/pull/18383#event-22371616321)

I see there are now no new changes in this PR. I thought we were changing the docs for the interface?

**Comment by ceasermikes002** [comment]
I have made the change, I'd be happy for you to re-review and give the go ahead

**Comment by brichet** [comment]
On my side the content is provided by default (Jupyterlab Version 4.5.6), so the comment was exact.
Can it be related to local config/install ?

image

**Comment by brichet** [comment]
I opened https://github.com/jupyterlab/jupyterlab/issues/18695, the behavior is actually inconsistent.
