### PR TITLE
Fix Mime Document Activation Handling

### LINKED ISSUE #3058: MimeDocument should delegate activate requests
We should be calling `activate()` on the wrapped renderer for `MimeDocuments`.  https://github.com/jupyterlab/jupyterlab/blob/d788d6e883a2462027b2a8dcbe319167fb34500a/packages/docregistry/src/default.ts#L485

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #3058.

### CODE REVIEW

File: packages/docregistry/src/default.ts [hunk 1]
```diff
@@ -508,12 +515,12 @@ class MimeDocument extends Widget implements DocumentRegistry.IReadyWidget {
...
-    if (!this._renderer) {
-      this._renderer = this.rendermime.createRenderer(this._mimeType);
-      (this.layout as BoxLayout).addWidget(this._renderer);
-      BoxLayout.setStretch(this._renderer, 1);
-    }
-    return this._renderer.renderModel(mimeModel);
+    return this._renderer.renderModel(mimeModel).then(() => {
+      // Handle a render after an activation.
+      if (this.node === document.activeElement) {
+        MessageLoop.sendMessage(this._renderer, Widget.Msg.ActivateRequest);
```
Comment (sccolbert) [inline packages/docregistry/src/default.ts]: I'm not sure about this logic. Shouldn't it be on the re-renderer to refocus itself if it had focus before re-rendering?

Comment (blink1073) [reply packages/docregistry/src/default.ts]: The renderer might not have a focusable element at construction time, this allows it to defer taking focus in its `onActivateRequest` until after it has a focusable node.

Comment (sccolbert) [reply packages/docregistry/src/default.ts]: My point was more that this is subtle, and I'm not sure that the logic belongs in the render method.
