### PR TITLE
Prevent split/merge on non-editable cells

### LINKED ISSUE #11140: Non-editable cells can be split and merged
## Description

Cells with "editable": false can be split and merged with other cells.

## Reproduce

In a new notebook, edit metadata adding  

    "editable": false

the cell cannot be edited, but it is possible to split it and merge it with other cells.

## Expected behavior

It should not be possible to split and merge non-editable cells, as in jupyter notebook.

## Context

Reproduced in a clean env (conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c nodefaults jupyterlab)

JupyterLab Version 3.1.13
Google Chrome | 93.0.4577.82
Windows 10 OS Version 2009
JavaScript | V8 9.3.345.19

I was NOT able to reproduce the problem in Jupyter notebook.

### PR DESCRIPTION
**Pull request by MUFFANUJ**
## References
fixes #11140

## Code changes
This update ensures read-only notebook cells stay protected by preventing split and merge actions whenever a non-editable cell is involved.

### Before

https://github.com/user-attachments/assets/d92f53a2-38b1-4ed4-8cda-31b8cd6e0567

### After

https://github.com/user-attachments/assets/7fc4cb14-8a36-4271-ad6c-af6e9235e925

## Backwards-incompatible changes
None

## AI usage

- **NO**: Some or all of the content of this PR was generated by AI.

### CODE REVIEW

**Comment by krassowski** [comment]
Also, should we display a dialog to the user? I don't remember what we do in other cases.

**Comment by MUFFANUJ** [comment]
hmm maybe instead of showing a dialog, we can have a notification https://jupyterlab.readthedocs.io/en/latest/api/functions/apputils.Notification.error.html?. Dialog might be too much for this

**Comment by MUFFANUJ** [comment]
Quick demo of the latest tweaks 🚀

https://github.com/user-attachments/assets/b68130bf-fad7-44a6-b738-28ede958b556

File: packages/notebook/src/actions.tsx [hunk 1]
```diff
@@ -146,11 +148,21 @@ export class NotebookActions {
  * A namespace for `NotebookActions` static methods.
  */
 export namespace NotebookActions {
+  function notifyReadOnlyAction(
+    message: string,
+    translator?: ITranslator
+  ): void {
+    const trans = (translator ?? nullTranslator).load('jupyterlab');
+    Notification.error(trans.__(message));
```
[the remark this answers is not in the document]
Comment (MUFFANUJ) [reply packages/notebook/src/actions.tsx]: Thanks for pointing out :) https://jupyterlab.readthedocs.io/en/stable/extension/internationalization.html?utm_source=chatgpt.com#internationalization-rules

File: packages/notebook/src/actions.tsx [hunk 2]
```diff
@@ -146,11 +146,23 @@ export class NotebookActions {
...
  */
 export namespace NotebookActions {
+  function notifySplitReadOnlyAction(translator?: ITranslator): void {
+    const trans = (translator ?? nullTranslator).load('jupyterlab');
+    Notification.error(trans.__('The cell is read-only and cannot be split.'));
+  }
+
+  function notifyMergeReadOnlyAction(translator?: ITranslator): void {
+    const trans = (translator ?? nullTranslator).load('jupyterlab');
+    Notification.error(trans.__('The cell is read-only and cannot be merged.'));
```
Comment (krassowski) [inline packages/notebook/src/actions.tsx]: I tested this and seen that these toasts show up in the statusbar but do not show up on screen without user clicking on the notification center.

Maybe adding `autoClose` option for 5 or 10 seconds would make it a smoother experience?

Comment (MUFFANUJ) [reply packages/notebook/src/actions.tsx]: autoClose should do
