### PR TITLE
Carriage return perf

### LINKED ISSUE #4202: Keras progress bars cause jupyterlab to freeze firefox and chrome
I noticed the builtin keras progress bar often causes the jupyterlab UI to freeze after a while (both under firefox and chrome, under Linux at least). I do not observe this issue under the traditional jupyter notebook app.

Here is a minimal reproduction script that does not depend on Keras. I am not sure Keras is implemented that way but might script seem to be able able to reproduce the same behavior as Keras is causing.

```python
import time


def make_progress(n_steps=int(1e4), line_length=70, delay=0,
                  flush_every=1e-2, prompt=""):
    last_flush = time.time()
    for i in range(n_steps):
        progressed = ((i + 1) * line_length) // n_steps
        prefix = '#' * progressed
        suffix = '-' * (line_length - progressed)
        now = time.time()
        flush = (now - last_flush) > flush_every
        if flush:
            last_flush = now
        print(f'\r{prompt}{i + 1:05d} [{prefix}{suffix}]', end="", flush=flush)
        if delay:
            time.sleep(delay)

            
for i in range(30):
    make_progress(prompt=f"{i + 1:02d} ")
    print()
```

Steps to reproduce:

- copy the above snippet in a jupyterlab cell in a fresh new Python 3.6 notebook
- execute the cell

Observed:

- the progress bars display one after the other;
- the first progress bars are very smooth;
- after 5 or 10 bars, progression is much less smooth;
- after 20 or so firefox window is completely frozen: it's clicking on the interrupt button takes a while to be taken into account.

Expected:

- smooth progress bars as observed when running the same notebook in the old jupyter notebook instead of jupyterlab.

I suspect that the `\r` not handled in the same way as in jupyter notebook and some datastructure in the browser is growing beyond acceptable.

Note that this bug is not the same as #1104 that was already fixed in previous versions of jupyter lab.

This issue was observed using jupyter lab 0.31.10. I have just upgraded to 0.31.12 and it seems to behave a bit better: I now get the following warning after a while:

```
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)
```

but firefox still gets much slower than under the original jupyter notebook app after a while.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #4202, for real this time. Boy, it's kind of tricky to debug something for which the test case locks up the browser. The problem was essentially a bad cached value. We were overwriting carriage returns and backspaces correctly, but then not updating the cached value of the overwritten output stream. This meant that we were doing the same work, over, and over, and over, in a quadratically growing fashion.

The real fix for this is a one-liner in b899ab0 . The rest of this PR is just some cleanup.

## References

#4202.

## Code changes

Restructuring of private functionality.

## User-facing changes

None, except that the browser won't lock up when using progress bars.

## Backwards-incompatible changes

Removal of `IModelDB` from output area input options. So far as I know, this was only used by the now-broken Google RTC.

### CODE REVIEW

File: packages/outputarea/src/model.ts [hunk 1]
```diff
@@ -153,19 +151,6 @@ export class OutputAreaModel implements IOutputAreaModel {
       });
     }
     this.list.changed.connect(this._onListChanged, this);
-
-    // If we are given a IModelDB, keep an up-to-date
-    // serialized copy of the OutputAreaModel in it.
-    if (options.modelDB) {
```
Comment (jasongrout) [inline packages/outputarea/src/model.ts]: Should we also delete the modelDB option in the options interface?

**Comment by jasongrout** [comment]
Nice, the progress bar example in #4202 is now really smooth!

File: packages/outputarea/src/model.ts (hunk 1 above)
Comment (ian-r-rose) [reply packages/outputarea/src/model.ts]: Sure, I guess that's a breaking change, but one that I am pretty sure was used nowhere but in the context of Google RTC.

**Comment by jasongrout** [comment]
Looks good to me.

**Comment by jasongrout** [comment]
Thanks! Let's merge after tests pass.

**Comment by jasongrout** [comment]
Looks like the linux integrity test failed because a timeout to yarn? I tried restarting it, but it seems to ignore my efforts to rerun.

**Comment by ian-r-rose** [comment]
Not sure if it was the cause of the timeout, but there was a real mistake I just fixed. Let's see if that changes things.

File: packages/outputarea/src/model.ts (hunk 1 above)
Comment (jasongrout) [reply packages/outputarea/src/model.ts]: Can you note it above in the breaking changes section?

Comment (jasongrout) [reply packages/outputarea/src/model.ts]: oh, you already did. Thanks!

**Comment by jasongrout** [comment]
Looks like the python test is having an error installing:

> error Couldn't find package "@jupyterlab/rendermime-interfaces@^1.3.0-alpha.6" required by "@jupyterlab/docregistry@^1.0.0-alpha.6" on the "npm" registry.

**Comment by ian-r-rose** [comment]
Maybe `npmjs.org` is having a hiccup?

**Comment by jasongrout** [comment]
> Maybe `npmjs.org` is having a hiccup?

Or the linux images, since it seems like Windows was fine.

**Comment by vidartf** [comment]
Will the `IModelDB` things affect the current RTC work?

**Comment by cupdike** [comment]
Thanks for the efforts on this one--cheering you on from the sidelines (as I'm sure others are too).  REALLY looking forward to being able to reliably do long running deep learning training runs in JupyterLab.

**Comment by ian-r-rose** [comment]
@vidartf that's a good point. My hope had still been to remove it entirely (and this particular application of it has always smelled off), but if you feel it would still be useful as a bridge, we can restore it here.

**Comment by blink1073** [comment]
I'm going to backport that first commit and make a 0.35.x release tomorrow.  Thanks @ian-r-rose, this one was a 🐻!

**Comment by ian-r-rose** [comment]
Awesome, thanks @blink1073. Note that the second commit contains the fix.

**Comment by blink1073** [comment]
:+1:
