### PR TITLE
Fix usage tests refusing to uninstall federated extensions

### LINKED ISSUE #9280: Fix usage tests uninstalling federated extensions
The `usage` tests have started to fail recently, which seems to be related to the new check that prevents uninstalling extensions installed by other means than `jupyter labextension install`.

Example run: https://github.com/jupyterlab/jupyterlab/pull/9275/checks?check_run_id=1349786158

```
JupyterLab cannot uninstall @jupyterlab/mock-extension since it was installed outside of JupyterLab. Use the same method used to install this extension to uninstall this extension
```

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #9280 

## Code changes

- Test `jupyter labextension uninstall` with  `mock-mime-extension` instead of the federated `mock-extension`
- Test `jupyter labextension uninstall` fails with a federated extension

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
We should also be able to update the script to check the error is returned when calling `jupyter labextension uninstall` on a federated extension.

**Comment by jasongrout** [comment]
This looks okay to me. Thanks!

File: scripts/ci_script.sh [hunk 1]
```diff
@@ -198,8 +198,8 @@ if [[ $GROUP == usage ]]; then
     jupyter labextension enable @jupyterlab/mock-extension --debug
     jupyter labextension uninstall @jupyterlab/mock-extension --debug
     jupyter labextension list 1>labextensions 2>&1
-    # bail if mock-extension was listed
-    cat labextensions | grep -q "mock-extension" && exit 1
+    # check the federated extension is still listed after jupyter labextension uninstall
+    cat labextensions | grep -q "mock-extension"
```
Comment (jtpio) [inline scripts/ci_script.sh:202]: Switched back to using `grep` to check for the extension, since `jupyter labextension uninstall @jupyterlab/mock-extension --debug` returns exist code 0 also if it refuses to uninstall the extension.

**Comment by jasongrout** [comment]
Yeah, usage tests pass now!
