### PR TITLE
Fix uncoalesced cell stream outputs clearing

### LINKED ISSUE #17632: Uncoalesced stream outputs persists in notebook after cleaning cells
## Description

Uncoalesced stream outputs do not get removed from the saved ipynb JSON. This means that after re-executing a notebook, the outputs from previous execution can show up after re-opening the file.

This happens with both `stdout` and `stderr`.

## Reproduce

1. Create a notebook `Untitled.ipynb` with one code cell:
    ```python
    import time
    for i in range(5):
        print(i)
        time.sleep(0.5)
    ```
   Image
2. Run the notebook using `jupyter execute Untitled.ipynb --inplace`
   Image
3. Reopen the notebook, see the results are shown correctly
  Image
4. View notebook source, see the partial results were not coalesced into a single stream
  Image
5. Change the first cell to say `print('hi')`
  Image
6. Run the first cell, save the notebook
   Image
7. Close and reopen the notebook, see the partial stream was retained in the output array
  Image
8. This is also visible in the notebook JSON:
  Image

## Expected behaviour

The notebook after step 7 contains only `hi` in the cell output.

## Context

- JupyterLab version:
    - `>= 4.1.0` 
    - `<= 4.4.3`
    - 4.0.x fails to open the notebook
    - 3.6.x does **not** have this problem

### PR DESCRIPTION
**Pull request by Darshan808**
### Description 
This PR integrates the new `clearOutputs()` method from the shared model to ensure all cell outputs are properly cleared, addressing cases with uncoalesced stream outputs. Related to upstream PR in `jupyter_ydoc` that introduced `clearOutputs()`.

### CODE REVIEW

**Comment by Darshan808** [comment]
I kept the `args` the same here:
```javascript
    this._changed.emit({
      type: 'clear',
      oldIndex: 0,
      newIndex: 0,
      newValues: [],
      oldValues: copy
    });
```

We could modify the interface to make the arguments optional and emit the event without any, but I wanted to get feedback on that first.

Also, do we need to test this function here? It's already tested in `jupyter_ydoc`, and I didn't see other shared model methods being tested in this repo.

**Comment by krassowski** [comment]
@Darshan808 https://github.com/jupyter-server/jupyter_ydoc/pull/330 was released in `v3.1.0` you should now be able to upgrade `@jupyter/ydoc` in `package.json`. We have `jlpm update:dependency` that can be helpful (`jlpm update:dependency --help`) or you can just bump the required ranges manually.

**Comment by krassowski** [comment]
And it look like we should add a test here too.

File: packages/cells/src/model.ts [hunk 1]
```diff
@@ -811,6 +811,9 @@ export class CodeCellModel extends CellModel implements ICodeCellModel {
             'silent-change'
           );
           break;
+        case 'clear':
+          codeCell.clearOutputs();
+          break;
```
Comment (krassowski) [inline packages/cells/src/model.ts:816]: Could we possibly avoid adding `clear` option and instead dispatch either `updateOutputs` or `clearOutputs` from the `remove` case depending on whether clearing of all outputs was requested or not?

File: packages/cells/test/model.spec.ts [hunk 2]
```diff
@@ -681,6 +681,23 @@ describe('cells/model', () => {
         model['onOutputsChange'](null as any, newEvent0);
         expect(sharedModel.ymodel.get('outputs').length).toBe(0);
       });
+
+      it('should clear the outputs', () => {
```
Comment (krassowski) [inline packages/cells/test/model.spec.ts:685]: It would be great to have a higher level test too. What is the minimal possible test case to replicate the issue described in https://github.com/jupyterlab/jupyterlab/issues/17632, which would fail on `main` but would pass in this PR?

File: packages/cells/src/model.ts (hunk 1 above)
Comment (Darshan808) [reply packages/cells/src/model.ts:816]: @krassowski 

This is a bit trickier to handle within the `remove` case, given the limited information available inside the event. The original issue arises from the coalescing of outputs on the frontend due to which jupyterlab thinks there is only one output which prevents us from simply relying on checking `event.oldValues.length` in `updateOutputs` and comparing it to `this.sharedModel.getOutputs().length` to determine whether clearing of all or partial output was requested.

For example, in the test that was recently added, here are the logged values of the shared model's outputs and the event's `oldValues`:

```
sharedModel's outputs: [
{
"name": "stdout",
"output_type": "stream",
"text": "0\n"
},
{
"name": "stdout",
"output_type": "stream",
"text": "1\n"
},
{
"name": "stdout",
"output_type": "stream",
"text": "2\n"
},
{
"name": "stdout",
"output_type": "stream",
"text": "3\n"
},
{
"name": "stdout",
"output_type": "stream",
"text": "4\n"
}
]

model.ts:816 event's old values (1): [
{
"name": "stdout",
"output_type": "stream",
"text": ""
}
]
```

I can see that other tests are now failing due to this change from `'remove'` to `'clear'`. I'm currently exploring possible ways to distinguish between a full clear request and a partial removal. Any suggestions or ideas would be greatly appreciated!

File: packages/cells/test/model.spec.ts (hunk 2 above)
Comment (Darshan808) [reply packages/cells/test/model.spec.ts:685]: I'm trying to add a Jest test but I'm having a bit of difficulty doing so. I believe I can add a Galata Playwright test instead, but I wanted to check which direction we should move forward with.

Is there a similar Jest test I could refer to for guidance? Or would it be better to proceed with a Galata test in this case?

Comment (krassowski) [reply packages/cells/test/model.spec.ts:685]: Maybe it is easier to add it in notebook tests, not in cell tests. Notebook model has `.fromJSON` method which can be use to create a minimal notebook with one cell with uncoalesced outputs:

https://github.com/jupyterlab/jupyterlab/blob/c103b77a25cf354592a5e9dc495f1814a6193397/packages/notebook/test/model.spec.ts#L53-L57

Then you  could call `clearExecution()` as in:

https://github.com/jupyterlab/jupyterlab/blob/fb24783eb4820585ac215bd1abc319a8501eec0b/packages/notebook/src/actions.tsx#L1539-L1551

and see if the ymodel ends up as intended.

File: packages/cells/src/model.ts (hunk 1 above)
Comment (krassowski) [reply packages/cells/src/model.ts:816]: That's ok to keep `clear` then if that makes it significantly easier. I do not follow why the tests are failing though.

**Comment by Darshan808** [comment]
I'm not sure whether failing tests are related or not.

**Comment by krassowski** [comment]
I restarted both jobs but js-debugger is still failing. I think I saw it fail in other recent PRs. It would be good to open a new issue and investigate what caused it. Maybe a new dependency release is causing it?

**Review by krassowski — APPROVED** [review]
Thank you @Darshan808!
