### PR TITLE
Don't play with the focus when handling focus event

### LINKED ISSUE #15407: Scrolling jitter [windowed nb]
## Description

In full windowing mode, it is possible to enter a jitter mode when activating a inactive notebook with active cell out side the view (aka scrolling will be needed).

bug_focus_switching

> Note that before the jittering notebook, when returning on the cell with `pp` leads to an unexpected scroll.

## Reproduce

See screen cast - basically switch between two tabs one being a notebook and when going back to the notebook, click on a cell that is not active with the active cell out of the view.

## Expected behavior

No scrolling occur when reactivating a notebook.

## Context

main branch: 5a28ab4147764a6c8ac2ad442ed948579f8615b3

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #15407

## Code changes

Create a new protected method `setMode` that allow to turn off some side-effect related to focus
Turn off focus actions when changing mode in focus event handlers.

## User-facing changes

In full windowing mode, we can switch to any cell even if the active cell is not in the view.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by fcollonval** [comment]
js-notebook issue is legit:

```
  ● @jupyter/notebook › Notebook › #handleEvent() › focusout › should switch to command mode

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      1358 |           MessageLoop.sendMessage(widget, Widget.Msg.ActivateRequest);
      1359 |           expect(widget.mode).toBe('command');
    > 1360 |           expect(widget.activeCell!.editor!.hasFocus()).toBe(false);
           |                                                         ^
      1361 |         });
      1362 |
      1363 |         it('should set command mode', () => {

      at Object.<anonymous> (test/widget.spec.ts:1360:57)
```

File: packages/notebook/src/widget.ts [hunk 1]
```diff
@@ -2696,21 +2717,23 @@ export class Notebook extends StaticNotebook {
   private _evtFocusIn(event: FocusEvent): void {
     const target = event.target as HTMLElement;
     const index = this._findCell(target);
+    console.log(`In _evtFocusIn idx ${index}`);
```
Comment (fcollonval) [inline packages/notebook/src/widget.ts:2720]:
```suggestion
```

**Comment by krassowski** [comment]
Thanks! Conceptually and code-wise looks good. I will test locally tomorrow.
I think backport is not needed here and will change the milestone, but please correct me/revert milestone if I am wrong.

**Review by krassowski — APPROVED** [review]
Thank you!
