### PR TITLE
Make extension dependency versions more permissive.

### LINKED ISSUE #8936: Build API Tests Failing on Windows
## Description
We are currently skipping the build tests in `jupyterlab/tests/test_build_api.py` on Windows.  We should reinstate them and fix the underlying error.

## Reproduce
Uncomment the skipped tests and run CI on Windows.

### PR DESCRIPTION
**Pull request by afshin**
- Fixes #8936 (build on Windows)
- Allow extensions build for 3.0 to work with 3.x
- Upgrade `webpack` to version 5.0.0-rc.0

## References
cf. https://github.com/jupyterlab/extension-cookiecutter-ts/pull/93

### CODE REVIEW

**Comment by afshin** [comment]
cc: @vidartf @jasongrout 

The Windows build is broken in this PR (the `webpack` upgrade notwithstanding -- it is still running CI on that commit) and we think it may be that there is a `webpack` bug on Windows.

We looked at this issue: https://github.com/webpack-contrib/css-loader/issues/978 which appears similar but cannot confirm that this is indeed what is going wrong.

If we cannot resolve the issue, one possible option we have is disabling `jupyter lab build` in Windows, which is less painful now that extensions can be installed with `pip`, even though it is not ideal. Other suggestions are welcome.

File: builder/src/extensionConfig.ts [hunk 1]
```diff
@@ -78,9 +78,11 @@ function generateConfig({
     ...(coreData.resolutions ?? {})
   };
 
+  // Alow extensions to match a wider range than the core dependency
+  // To ensure forward compatibility.
   Object.keys(coreDeps).forEach(element => {
     shared[element] = {
-      requiredVersion: coreDeps[element],
+      requiredVersion: coreDeps[element].replace('~', '^'),
```
Comment (jasongrout) [inline builder/src/extensionConfig.ts:85]: I'm not sure exactly what this is affecting - does it make sense to not restrict to ~ updates in core now?

**Comment by jasongrout** [comment]
> If we cannot resolve the issue, one possible option we have is disabling `jupyter lab build` in Windows, which is less painful now that extensions can be installed with `pip`, even though it is not ideal. Other suggestions are welcome.

Less painful...but my guess is that it will take some time for extensions to migrate to the new pip system, so if we can make it possible to do build, that will be way better.

**Comment by vidartf** [comment]
I was able to run `jupyter lab build` on this branch locally without any issues, so I think disabling that command on Windows in general would be overkill.

**Comment by vidartf** [comment]
Is there a command to clear the cache for the CI?

**Comment by vidartf** [comment]
Have we considered whether running the CI bash script via msys might be affecting things?

**Comment by afshin** [comment]
@vidartf,

> Is there a command to clear the cache for the CI?

I don't know.

> Have we considered whether running the CI bash script via msys might be affecting things?

I don't know that, either.

Please feel free to push to this branch if you have an idea, though!

**Comment by vidartf** [comment]
Seems like running it via normal batch scripts did the trick, so there is some msys stuff getting in the way. I'll restart it now to verify that it wasn't just a fluke

**Comment by vidartf** [comment]
Seems ok. If someone reviews the batch scripts + execution we should be good to go then.

**Comment by afshin** [comment]
@vidartf So the Linux integrity failure is a fluke too? Should I restart the CI after it fails to confirm?

**Comment by vidartf** [comment]
Ah, I have no idea about the linux integrity bit, I was only focused on the Windows bit. I also believe there are a few attempted windows fixes in this PR that needs cleaning up.

**Comment by vidartf** [comment]
Note that the integrity test runs with `webpack 5.0.0-rc.0` while the python tests run with `webpack 5.0.0-beta.32`, as that is what is in jupyterlab/staging (I've lost track of all the logic about this bit, sorry).

**Comment by jasongrout** [comment]
> Note that the integrity test runs with `webpack 5.0.0-rc.0` while the python tests run with `webpack 5.0.0-beta.32`, as that is what is in jupyterlab/staging (I've lost track of all the logic about this bit, sorry).

When we release, `jupyterlab/staging` is updated to reflect what is currently in `dev_mode/`.

File: scripts/ci_script.sh [hunk 2]
```diff
@@ -12,6 +12,7 @@ fi
 
 
 if [[ $GROUP == python ]]; then
+    jupyter lab build --debug
```
Comment (vidartf) [inline scripts/ci_script.sh:15]: Did we want to keep this, or was it just for debugging? If the latter, we might shave off some CI time by removing it again.

**Comment by jasongrout** [comment]
Perhaps the windows `jupyter lab build` was failing because of the issues explored at https://github.com/jupyterlab/jupyterlab/issues/9698
