### PR TITLE
Avoid changing type of read-only cells

### LINKED ISSUE #11165: The type of a non-editable cell can be changed
## Description

The type of cells with "editable": false can be changed (e.g. from Code to Markdown or Raw).

## Reproduce

In a new notebook, edit metadata adding  

    "editable": false

the cell cannot be edited, but it is possible to change its type from the toolbar.

## Expected behavior

It should not be possible to change the type, as in jupyter notebook.

## Context

Reproduced in a clean env (conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c nodefaults jupyterlab)

JupyterLab Version 3.1.13
Google Chrome | 93.0.4577.82
Windows 10 OS Version 2009
JavaScript | V8 9.3.345.19

I was NOT able to reproduce the problem in Jupyter notebook.

### PR DESCRIPTION
**Pull request by cmarmo**
## References
This pull request closes  #11165: thanks for considering it.

## Code changes
This pull request adds a check for read-only status of the cell, as described [here](https://github.com/jupyterlab/jupyterlab/issues/11165#issuecomment-2016493224).

The related spec has been added.

### CODE REVIEW

File: packages/notebook/src/actions.tsx [hunk 1]
```diff
@@ -2615,6 +2615,19 @@ namespace Private {
         });
         return;
       }
+      if (child.model.getMetadata('editable') == false) {
+        translator = translator || nullTranslator;
+        const trans = translator.load('jupyterlab');
+        // Do not permit changing cell type when the cell is readonly
+        void showDialog({
+          title: trans.__('Cell type not editable'),
```
Comment (krassowski) [inline packages/notebook/src/actions.tsx:2623]:
```suggestion
          title: trans.__('Cell is not editable'),
```

File: packages/notebook/src/actions.tsx [hunk 2]
```diff
@@ -2615,6 +2615,19 @@ namespace Private {
...
+          body: trans.__(
+            'The cell type is not editable, its type cannot be changed!'
```
Comment (krassowski) [inline packages/notebook/src/actions.tsx:2625]:
```suggestion
            'The cell is not editable, its type cannot be changed!'
```

**Review by krassowski — COMMENTED** [review]
Thank you @cmarmo, this looks good to me - just small suggestions on wording

**Comment by cmarmo** [comment]
Thank you @krassowski ! Comments applied.

File: packages/notebook/src/actions.tsx [hunk 3]
```diff
@@ -2615,6 +2615,19 @@ namespace Private {
...
       }
+      if (child.model.getMetadata('editable') == false) {
+        translator = translator || nullTranslator;
+        const trans = translator.load('jupyterlab');
+        // Do not permit changing cell type when the cell is readonly
+        void showDialog({
+          title: trans.__('Cell is not editable'),
+          body: trans.__(
+            'The cell is not editable, its type cannot be changed!'
+          ),
```
Comment (krassowski) [inline packages/notebook/src/actions.tsx:2626]: Having looked more at the interface I wonder if it should be:

```suggestion
          title: trans.__('Cell is read-only'),
          body: trans.__(
            'The cell is read-only, its type cannot be changed!'
          ),
```

This is how we refer to non-editable cells in the property inspector:

image

and in the settings:

image

**Review by krassowski — APPROVED** [review]
Thank you @cmarmo!

File: packages/notebook/src/actions.tsx [hunk 4]
```diff
@@ -2615,6 +2615,19 @@ namespace Private {
...
       }
+      if (child.model.getMetadata('editable') == false) {
+        translator = translator || nullTranslator;
+        const trans = translator.load('jupyterlab');
+        // Do not permit changing cell type when the cell is readonly
+        void showDialog({
+          title: trans.__('Cell is read-only'),
+          body: trans.__(
+            'The cell is read-only, its type cannot be changed!'
+          ),
```
Comment (krassowski) [inline packages/notebook/src/actions.tsx:2626]:
```suggestion
          body: trans.__('The cell is read-only, its type cannot be changed!'),
```

**Comment by cmarmo** [comment]
Thank you @krassowski ... sorry I didn't check the lint.
