### PR TITLE
Fix HTML lang attribute

### LINKED ISSUE #16277: `Language pack 'en_US' not installed` in the dev tools console
## Description

JupyterLab often shows the following warning in the dev tools console: 

image

## Reproduce

Using `4.2.0rc0` on Binder.

But this is also reproducible from the latest commit on `main`.

## Expected behavior

There should likely be no warning in the dev tools.

## Context

- Operating System and version: Ubuntu 23.10
- Browser and version: Latest Firefox and Chrome
- JupyterLab version: 4.2.0rc0

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #16277
Fixes inconsistency of lang attribute value when the language was set from the system language; prior to this PR, if your system language is e.g. french, the lang was 'en-US' and not 'fr-FR'

image

## Code changes

- Use default language to _en_ for consistency with the server configuration
- Simplify the logic for the translation extension as the true source for the current locale is `TranslationManager.languageCode` not the settings
- This allows to avoid loading the translation settings in both plugins (the one creating the manager and the one adding the menu/commands).
- Refactor the internationalization ui test to be a single test with soft except to follow good pw practices.

> Note: the background of some documentation snapshots have changed due to the test refactoring that open a subfolder `data`. This induces a shift downward of the icons in the launcher compared to the previous reference pictures.

## User-facing changes

No useless warning when using default language aka `en`.
Consistent `lang` attribute when using _default_ language (aka language is set from system language).

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by fcollonval** [comment]
bot, please update documentation snapshots

**Comment by krassowski** [comment]
I think these snapshot updates are just flaky and the test was failing on a timeout, not due to snapshots change:

```
    Retry #2 ───────────────────────────────────────────────────────────────────────────────────────
    Error: proxy.waitForURL: Test ended.
    =========================== logs ===========================
    waiting for navigation to "http://localhost:8888/lab*" until "load"
      navigated to "http://localhost:8888/lab/tree/data"
      navigated to "http://localhost:8888/lab/tree/data"
      navigated to "http://localhost:8888/lab/tree/data"
    ============================================================

      47 |     // Check UI is in Chinese
      48 |     await Promise.all([
    > 49 |       page.waitForURL(baseURL! + '/lab*'),
         |            ^
      50 |       page.locator('#jupyterlab-splash').waitFor(),
      51 |       page.click('button:has-text("Change and reload")')
      52 |     ]);
```

**Comment by fcollonval** [comment]
@krassowski thanks for the follow up. Actually there is a slight change due to the test refactoring - quoting the additional note I wrote in the PR description:

> the background of some documentation snapshots have changed due to the test refactoring that open a subfolder data. This induces a shift downward of the icons in the launcher compared to the previous reference pictures.

**Comment by fcollonval** [comment]
But it seems I should indeed update the url pattern on which we are waiting for.

**Comment by fcollonval** [comment]
For reference, the glob pattern `http://localhost:8888/lab*` is not capturing `http://localhost:8888/lab/tree/data` because I should have used double start `**` (xref https://playwright.dev/docs/api/class-page#page-wait-for-url).

But anyway in de0d682, I set the full URL to be extra safe.

**Comment by krassowski** [comment]
Any idea how can we make sure the font stays consistent across snapshots? This is currently the major source of noise when using asking bot to update snapshots. Both actions run on `ubuntu-22.04` so it does not seem to be down to OS?

**Comment by fcollonval** [comment]
> Any idea how can we make sure the Chinese font stays consistent across snapshots? This is currently the major source of noise when using asking bot to update snapshots. Both actions run on `ubuntu-22.04` so it does not seem to be down to OS?

Diving into the workflow, I spotted two difference:

- in the update-snapshots actions, we are [executing](https://github.com/jupyterlab/maintainer-tools/blob/e3870c30c55351fca0b3ea900db3bda528022077/.github/actions/update-snapshots/action.yml#L78) `npx playwright install-deps`. But we don't do that in the integration tests. This leads to apt packages changes - among which are font related packages:

<details>
<code>
Installing dependencies...
Switching to root user to install dependencies...
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://packages.microsoft.com/repos/azure-cli jammy InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
fonts-liberation is already the newest version (1:1.07.4-11).
fonts-liberation set to manually installed.
libasound2 is already the newest version (1.2.6.1-1ubuntu1).
libasound2 set to manually installed.
libatk-bridge2.0-0 is already the newest version (2.38.0-3).
libatk-bridge2.0-0 set to manually installed.
libatk1.0-0 is already the newest version (2.36.0-3build1).
libatk1.0-0 set to manually installed.
libatspi2.0-0 is already the newest version (2.44.0-3).
libatspi2.0-0 set to manually installed.
libcairo-gobject2 is already the newest version (1.16.0-5ubuntu2).
libcairo-gobject2 set to manually installed.
libcairo2 is already the newest version (1.16.0-5ubuntu2).
libcairo2 set to manually installed.
libdbus-glib-1-2 is already the newest version (0.112-2build1).
libdbus-glib-1-2 set to manually installed.
libenchant-2-2 is already the newest version (2.3.2-1ubuntu2).
libenchant-2-2 set to manually installed.
libepoxy0 is already the newest version (1.5.10-1).
libepoxy0 set to manually installed.
libfontconfig1 is already the newest version (2.13.1-4.2ubuntu5).
libfontconfig1 set to manually installed.
libglx0 is already the newest version (1.4.0-1).
libglx0 set to manually installed.
libgudev-1.0-0 is already the newest version (1:237-2build1).
libicu70 is already the newest version (70.1-2).
libicu70 set to manually installed.
libjpeg-turbo8 is already the newest version (2.1.2-0ubuntu1).
libjpeg-turbo8 set to manually installed.
liblcms2-2 is already the newest version (2.12~rc1-2build2).
liblcms2-2 set to manually installed.
libpng16-16 is already the newest version (1.6.37-3build5).
libpng16-16 set to manually installed.
libproxy1v5 is already the newest version (0.4.17-2).
libproxy1v5 set to manually installed.
libsecret-1-0 is already the newest version (0.20.5-2).
libsecret-1-0 set to manually installed.
libxcb-shm0 is already the newest version (1.14-3ubuntu3).
libxcb-shm0 set to manually installed.
libxcb1 is already the newest version (1.14-3ubuntu3).
libxcb1 set to manually installed.
libxcomposite1 is already the newest version (1:0.4.5-1build2).
libxcomposite1 set to manually installed.
libxcursor1 is already the newest version (1:1.2.0-2build4).
libxcursor1 set to manually installed.
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxext6 is already the newest version (2:1.3.4-1build1).
libxext6 set to manually installed.
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxi6 is already the newest version (2:1.8-1build1).
libxi6 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libxrender1 is already the newest version (1:0.9.10-1build4).
libxrender1 set to manually installed.
libxtst6 is already the newest version (2:1.2.3-1build4).
libxtst6 set to manually installed.
libatomic1 is already the newest version (12.3.0-1ubuntu1~22.04).
libatomic1 set to manually installed.
libcups2 is already the newest version (2.4.1op1-1ubuntu4.11).
libcups2 set to manually installed.
libdbus-1-3 is already the newest version (1.12.20-2ubuntu4.1).
libdbus-1-3 set to manually installed.
libdrm2 is already the newest version (2.4.113-2~ubuntu0.22.04.1).
libdrm2 set to manually installed.
libfreetype6 is already the newest version (2.11.1+dfsg-1ubuntu0.2).
libfreetype6 set to manually installed.
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgbm1 set to manually installed.
libgdk-pixbuf-2.0-0 is already the newest version (2.42.8+dfsg-1ubuntu0.3).
libgdk-pixbuf-2.0-0 set to manually installed.
libglib2.0-0 is already the newest version (2.72.4-0ubuntu2.4).
libglib2.0-0 set to manually installed.
libgstreamer1.0-0 is already the newest version (1.20.3-0ubuntu1.1).
libgstreamer1.0-0 set to manually installed.
libgtk-3-0 is already the newest version (3.24.33-1ubuntu2.2).
libharfbuzz0b is already the newest version (2.7.4-1ubuntu3.2).
libharfbuzz0b set to manually installed.
libnspr4 is already the newest version (2:4.35-0ubuntu0.22.04.1).
libnss3 is already the newest version (2:3.98-0ubuntu0.22.04.2).
libopenjp2-7 is already the newest version (2.4.0-6ubuntu0.3).
libopenjp2-7 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
libpangocairo-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpangocairo-1.0-0 set to manually installed.
libwayland-client0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-client0 set to manually installed.
libwayland-egl1 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-egl1 set to manually installed.
libwayland-server0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-server0 set to manually installed.
libwebpdemux2 is already the newest version (1.2.2-2ubuntu0.22.04.2).
libwebpdemux2 set to manually installed.
libx11-6 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-6 set to manually installed.
libx11-xcb1 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-xcb1 set to manually installed.
libxslt1.1 is already the newest version (1.1.34-4ubuntu0.22.04.1).
libxslt1.1 set to manually installed.
The following additional packages will be installed:
  libaa1 libabsl20210324 libass9 libasyncns0 libavc1394-0 libavcodec58
  libavdevice58 libavfilter7 libavformat58 libavutil56 libbluray2 libbs2b0
  libcaca0 libcdio-cdda2 libcdio-paranoia2 libcdio19 libcdparanoia0
  libchromaprint1 libcodec2-1.0 libdc1394-25 libdca0 libdecor-0-0 libdv4
  libdvdnav4 libdvdread8 libegl-mesa0 libfaad2 libflac8 libflite1
  libfluidsynth3 libfreeaptx0 libgav1-0 libgme0 libgraphene-1.0-0 libgsm1
  libgssdp-1.2-0 libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-good1.0-0
  libgtk-4-common libgupnp-1.2-1 libgupnp-igd-1.0-4 libiec61883-0
  libinstpatch-1.0-2 libjack-jackd2-0 libkate1 libldacbt-enc2 liblilv-0-0
  libltc11 libmfx1 libmjpegutils-2.1-0 libmodplug1 libmp3lame0 libmpcdec6
  libmpeg2encpp-2.1-0 libmpg123-0 libmplex2-2.1-0 libmysofa1 libnice10
  libopenal-data libopenal1 libopenh264-6 libopenmpt0 libopenni2-0
  liborc-0.4-0 libpocketsphinx3 libpostproc55 libpulse0 libqrencode4
  libraw1394-11 librubberband2 libsamplerate0 libsbc1 libsdl2-2.0-0
  libserd-0-0 libshine3 libshout3 libsndfile1 libsndio7.0 libsord-0-0
  libsoundtouch1 libsoup-3.0-common libsoxr0 libspandsp2 libspeex1
  libsphinxbase3 libsratom-0-0 libsrt1.4-gnutls libsrtp2-1 libssh-gcrypt-4
  libswresample3 libswscale5 libtag1v5 libtag1v5-vanilla libtheora0
  libtwolame0 libudfread0 libv4l-0 libv4lconvert0 libva-drm2 libva-x11-2
  libva2 libvdpau1 libvidstab1.1 libvisual-0.4-0 libvo-aacenc0 libvo-amrwbenc0
  libvorbisenc2 libvpx7 libwavpack1 libwebrtc-audio-processing1 libwildmidi2
  libxcb-shape0 libxml2-dev libxv1 libxvidcore4 libyuv0 libzbar0 libzimg2
  libzvbi-common libzvbi0 libzxingcore1 ocl-icd-libopencl1 timgm6mb-soundfont
  xfonts-encodings xfonts-utils xserver-common
Suggested packages:
  ffmpeg-doc frei0r-plugins gvfs libcuda1 libnvcuvid1 libnvidia-encode1
  libbluray-bdj libdv-bin oss-compat libdvdcss2 libvisual-0.4-plugins
  libgtk-4-media-gstreamer | libgtk-4-media-ffmpeg jackd2 gnome-shell
  | notification-daemon libportaudio2 opus-tools pulseaudio libraw1394-doc
  serdi sndiod sordi speex libwildmidi-config opencl-icd fluid-soundfont-gm
Recommended packages:
  fonts-ipafont-mincho fonts-tlwg-loma gstreamer1.0-x libaacs0
  libdecor-0-plugin-1-cairo | libdecor-0-plugin-1 gstreamer1.0-gl libgtk-4-bin
  pocketsphinx-en-us va-driver-all | va-driver vdpau-driver-all | vdpau-driver
  xfonts-base
The following NEW packages will be installed:
  ffmpeg fonts-freefont-ttf fonts-ipafont-gothic fonts-tlwg-loma-otf
  fonts-unifont fonts-wqy-zenhei gstreamer1.0-libav gstreamer1.0-plugins-bad
  gstreamer1.0-plugins-base gstreamer1.0-plugins-good libaa1 libabsl20210324
  libass9 libasyncns0 libavc1394-0 libavcodec58 libavdevice58 libavfilter7
  libavformat58 libavif13 libavutil56 libbluray2 libbs2b0 libcaca0
  libcdio-cdda2 libcdio-paranoia2 libcdio19 libcdparanoia0 libchromaprint1
  libcodec2-1.0 libdc1394-25 libdca0 libdecor-0-0 libdv4 libdvdnav4
  libdvdread8 libegl-mesa0 libegl1 libevdev2 libevent-2.1-7 libfaad2 libffi7
  libflac8 libflite1 libfluidsynth3 libfreeaptx0 libgav1-0 libgles2 libgme0
  libgraphene-1.0-0 libgsm1 libgssdp-1.2-0 libgstreamer-gl1.0-0
  libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-base1.0-0
  libgstreamer-plugins-good1.0-0 libgtk-4-1 libgtk-4-common libgupnp-1.2-1
  libgupnp-igd-1.0-4 libharfbuzz-icu0 libhyphen0 libiec61883-0
  libinstpatch-1.0-2 libjack-jackd2-0 libkate1 libldacbt-enc2 liblilv-0-0
  libltc11 libmanette-0.2-0 libmfx1 libmjpegutils-2.1-0 libmodplug1
  libmp3lame0 libmpcdec6 libmpeg2encpp-2.1-0 libmpg123-0 libmplex2-2.1-0
  libmysofa1 libnice10 libnotify4 libopenal-data libopenal1 libopengl0
  libopenh264-6 libopenmpt0 libopenni2-0 libopus0 liborc-0.4-0
  libpocketsphinx3 libpostproc55 libpulse0 libqrencode4 libraw1394-11
  librubberband2 libsamplerate0 libsbc1 libsdl2-2.0-0 libserd-0-0 libshine3
  libshout3 libsndfile1 libsndio7.0 libsord-0-0 libsoundtouch1 libsoup-3.0-0
  libsoup-3.0-common libsoxr0 libspandsp2 libspeex1 libsphinxbase3
  libsratom-0-0 libsrt1.4-gnutls libsrtp2-1 libssh-gcrypt-4 libswresample3
  libswscale5 libtag1v5 libtag1v5-vanilla libtheora0 libtwolame0 libudfread0
  libv4l-0 libv4lconvert0 libva-drm2 libva-x11-2 libva2 libvdpau1
  libvidstab1.1 libvisual-0.4-0 libvo-aacenc0 libvo-amrwbenc0 libvorbisenc2
  libvpx7 libwavpack1 libwebrtc-audio-processing1 libwildmidi2 libwoff1
  libx264-163 libxcb-shape0 libxv1 libxvidcore4 libyuv0 libzbar0 libzimg2
  libzvbi-common libzvbi0 libzxingcore1 ocl-icd-libopencl1 timgm6mb-soundfont
  xfonts-cyrillic xfonts-encodings xfonts-scalable xfonts-utils
The following packages will be upgraded:
  fonts-noto-color-emoji libxml2 libxml2-dev xserver-common xvfb
5 upgraded, 154 newly installed, 0 to remove and 39 not upgraded.
</code>
</details>

- We install all browser in the update snapshot action, we install [all browsers](https://github.com/jupyterlab/maintainer-tools/blob/e3870c30c55351fca0b3ea900db3bda528022077/.github/actions/update-snapshots/action.yml#L79) because of a bug in the input variable name; we actually have a stale fix for that: https://github.com/jupyterlab/maintainer-tools/pull/183

In [e3c1da3](https://github.com/jupyterlab/jupyterlab/pull/17337/commits/e3c1da339f4ed24f967658ebdff6f7071eef7988), I added the `install-deps` command to see if this solves the issue.

**Comment by fcollonval** [comment]
Ok so it seems that the discrepancy lies on the step `install-deps`. As this is mentioned in the documentation as a step when updating playwright, I would say [e3c1da3](https://github.com/jupyterlab/jupyterlab/pull/17337/commits/e3c1da339f4ed24f967658ebdff6f7071eef7988) is the path forward.

File: packages/translation/src/manager.ts [hunk 1]
```diff
@@ -33,10 +34,13 @@ export class TranslationManager implements ITranslator {
...
     this._stringsPrefix = stringsPrefix || '';
     this._englishBundle = new Gettext({ stringsPrefix: this._stringsPrefix });
+    this._currentLocale = DEFAULT_LANGUAGE_CODE;
   }
 
   /**
-   * Get the language code of the current locale.
+   * Get the language code (tag) of the current locale.
+   *
+   * It respects RFC5646: https://datatracker.ietf.org/doc/html/rfc5646
```
Comment (krassowski) [inline packages/translation/src/manager.ts:43]: I would mention BCP 47 as a more general standard. I am not sure if we comply with RFC5646 in particular.

File: .github/workflows/galata.yml [hunk 2]
```diff
@@ -49,6 +49,7 @@ jobs:
       - name: Install browser
         run: |
           cd galata
+          jlpm playwright install-deps || true
```
Comment (krassowski) [inline .github/workflows/galata.yml:52]: Do we need `|| true`?

**Review by krassowski — APPROVED** [review]
Thank you @fcollonval!

File: packages/translation/src/manager.ts (hunk 1 above)
Comment (fcollonval) [reply packages/translation/src/manager.ts:43]: For what I understand, this is the same document; see https://www.rfc-editor.org/info/rfc5646. For reference, the link set up in the [spellchecker extension readme](https://github.com/jupyterlab-contrib/spellchecker) for BCP47 is to RFC5646 :wink:

File: .github/workflows/galata.yml (hunk 2 above)
Comment (fcollonval) [reply .github/workflows/galata.yml:52]: That's a good question. I copied the line from the action in which I guess we want to be robust to the case the os is not well supported. I guess in this case we control the os, so it will be better to remove it.

File: packages/translation/src/manager.ts (hunk 1 above)
Comment (krassowski) [reply packages/translation/src/manager.ts:43]: Yeah, so the thing is "BCP47" is the long-living name which more folks understand because previously it was defined in RFC 4646 and earlier in RFC 3066 and yet earlier in RFC 1766. My point is, I do not remember all RFCs, but "BCP 47" rings a bell immediately.

Comment (fcollonval) [reply packages/translation/src/manager.ts:43]: So I learnt something today, BCP (Best Current Practice) is a sub series of RFC (Request For Comment); list of BCPs https://www.ietf.org/rfc/bcp-index.txt
And the current state of BCP47 is RFC4647 and RFC5646:
> 0047 Language Tags. A. Phillips, M. Davis. (Format: TXT=254322 HTML=bytes) (Also RFC4647, RFC5646)

From [wikipedia](https://en.wikipedia.org/wiki/Best_current_practice)

> Each RFC number refers to a specific version of a document Standard Track, but the BCP number refers to the most recent revision of the document. Thus, citations often reference both the BCP number and the RFC number.

So I would say it is better to point to a RFC5646 as it is a stable reference even if it can become obsolete.

**Comment by krassowski** [comment]
Picked up a conflict in `galata/test/documentation/plugins.test.ts-snapshots/plugins-documentation-linux.json` due to https://github.com/jupyterlab/jupyterlab/pull/17338
