### PR TITLE
Manage kernel message queueing better to prevent out-of-order execution

### LINKED ISSUE #9566: Out-of-order execution
## Description

Manually executing cells while the kernel is restarting leads to out-of-order cell execution:
Peek 2021-01-06 15-11

## Reproduce

1. Open this binder: https://mybinder.org/v2/gh/jupyter-widgets/ipyleaflet/stable?urlpath=lab%2Ftree%2Fexamples%2FChoropleth.ipynb
2. Restart the kernel
3. Quickly execute every cell by hand while the kernel is restarting
4. After execution finished, you should see some cells still marked with `*`, and/or some cells executed out of order, potentially leading to execution errors.

## Expected behavior

Cells should be executed in order.

## Context

- Operating System and version: Linux Ubuntu 20.04 LTS
- Browser and version: Google Chrome 87.0.4280.88 (Official Build) (64-bit)
- JupyterLab version: 3.0.1

<details><summary>Troubleshoot Output</summary>
<pre>
jovyan@jupyter-jupyter-2dwidgets-2dipyleaflet-2duyxyynfv:~$ jupyter troubleshoot
$PATH:
        /srv/conda/envs/notebook/bin
        /srv/conda/condabin
        /home/jovyan/.local/bin
        /home/jovyan/.local/bin
        /srv/conda/envs/notebook/bin
        /srv/conda/bin
        /srv/npm/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /srv/conda/envs/notebook/bin
        /srv/conda/envs/notebook/lib/python37.zip
        /srv/conda/envs/notebook/lib/python3.7
        /srv/conda/envs/notebook/lib/python3.7/lib-dynload
        /srv/conda/envs/notebook/lib/python3.7/site-packages

sys.executable:
        /srv/conda/envs/notebook/bin/python

sys.version:
        3.7.8 | packaged by conda-forge | (default, Jul 23 2020, 03:54:19) 
        [GCC 7.5.0]

platform.platform():
        Linux-4.19.112+-x86_64-with-debian-buster-sid

which -a jupyter:
        /srv/conda/envs/notebook/bin/jupyter
        /srv/conda/envs/notebook/bin/jupyter

pip list:
        Package                 Version
        ----------------------- -------------------
        affine                  2.3.0
        alembic                 1.4.2
        anyio                   2.0.2
        async-generator         1.10
        attrs                   19.3.0
        Babel                   2.9.0
        backcall                0.2.0
        bleach                  3.1.5
        blinker                 1.4
        bqplot                  0.12.18
        branca                  0.4.2
        brotlipy                0.7.0
        certifi                 2020.6.20
        certipy                 0.1.3
        cffi                    1.14.0
        cftime                  1.3.0
        chardet                 3.0.4
        click                   7.1.2
        click-plugins           1.1.1
        cligj                   0.7.1
        cryptography            3.0
        cycler                  0.10.0
        decorator               4.4.2
        defusedxml              0.6.0
        entrypoints             0.3
        Fiona                   1.8.18
        Flask                   1.1.2
        GDAL                    3.1.4
        geopandas               0.8.1
        idna                    2.10
        importlib-metadata      1.7.0
        ipykernel               5.3.4
        ipyleaflet              0.13.5
        ipython                 7.16.1
        ipython-genutils        0.2.0
        ipywidgets              7.6.2
        itsdangerous            1.1.0
        jedi                    0.17.2
        Jinja2                  2.11.2
        json5                   0.9.4
        jsonschema              3.2.0
        jupyter-client          6.1.6
        jupyter-core            4.6.3
        jupyter-offlinenotebook 0.1.0
        jupyter-server          1.1.4
        jupyter-telemetry       0.0.5
        jupyterhub              1.1.0
        jupyterlab              3.0.1
        jupyterlab-server       2.0.0
        jupyterlab-widgets      1.0.0
        kiwisolver              1.3.1
        Mako                    1.1.0
        MarkupSafe              1.1.1
        matplotlib              3.3.3
        mistune                 0.8.4
        munch                   2.5.0
        nbclassic               0.2.5
        nbconvert               5.6.1
        nbformat                5.0.7
        nbresuse                0.3.3
        netCDF4                 1.5.5.1
        notebook                6.0.3
        nteract-on-jupyter      2.1.3
        numpy                   1.19.4
        oauthlib                3.0.1
        olefile                 0.46
        packaging               20.4
        pamela                  1.0.0
        pandas                  1.2.0
        pandocfilters           1.4.2
        parso                   0.7.1
        pexpect                 4.8.0
        pickleshare             0.7.5
        Pillow                  8.1.0
        pip                     20.1.1
        prometheus-client       0.8.0
        prompt-toolkit          3.0.5
        psutil                  5.7.2
        ptyprocess              0.6.0
        pycparser               2.20
        pycurl                  7.43.0.5
        Pygments                2.6.1
        PyJWT                   1.7.1
        pyOpenSSL               19.1.0
        pyparsing               2.4.7
        pyproj                  2.6.1.post1
        PyQt5                   5.12.3
        PyQt5-sip               4.19.18
        PyQtChart               5.12
        PyQtWebEngine           5.12.1
        pyrsistent              0.16.0
        PySocks                 1.7.1
        python-dateutil         2.8.1
        python-editor           1.0.4
        python-json-logger      0.1.11
        pytz                    2020.5
        pyzmq                   19.0.1
        rasterio                1.1.8
        requests                2.24.0
        Rtree                   0.9.7
        ruamel.yaml             0.16.6
        ruamel.yaml.clib        0.2.0
        scipy                   1.6.0
        Send2Trash              1.5.0
        setuptools              49.2.0.post20200712
        Shapely                 1.7.1
        six                     1.15.0
        sniffio                 1.2.0
        snuggs                  1.4.7
        SQLAlchemy              1.3.18
        terminado               0.8.3
        testpath                0.4.4
        tornado                 6.1
        tqdm                    4.55.1
        traitlets               4.3.3
        traittypes              0.2.1
        typing-extensions       3.7.4.3
        urllib3                 1.25.10
        wcwidth                 0.2.5
        webencodings            0.5.1
        Werkzeug                1.0.1
        wheel                   0.34.2
        widgetsnbextension      3.5.1
        xarray                  0.16.2
        zipp                    3.1.0

conda list:
        # packages in environment at /srv/conda/envs/notebook:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       0_gnu    conda-forge
        affine                    2.3.0                      py_0    conda-forge
        alembic                   1.4.2              pyh9f0ad1d_0    conda-forge
        anyio                     2.0.2            py37h89c1867_3    conda-forge
        async_generator           1.10                       py_0    conda-forge
        attrs                     19.3.0                     py_0    conda-forge
        babel                     2.9.0              pyhd3deb0d_0    conda-forge
        backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
        bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
        blinker                   1.4                        py_1    conda-forge
        boost-cpp                 1.72.0               h9359b55_3    conda-forge
        bqplot                    0.12.18            pyh9f0ad1d_0    conda-forge
        branca                    0.4.2              pyhd8ed1ab_0    conda-forge
        brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
        bzip2                     1.0.8                h7f98852_4    conda-forge
        ca-certificates           2020.6.20            hecda079_0    conda-forge
        cairo                     1.16.0            h488836b_1006    conda-forge
        certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
        certipy                   0.1.3                      py_0    conda-forge
        cffi                      1.14.0           py37hd463f26_0    conda-forge
        cfitsio                   3.470                hb418390_7    conda-forge
        cftime                    1.3.0            py37ha21ca33_0    conda-forge
        chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
        click                     7.1.2              pyh9f0ad1d_0    conda-forge
        click-plugins             1.1.1                      py_0    conda-forge
        cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
        cryptography              3.0              py37hb09aad4_0    conda-forge
        curl                      7.71.1               he644dc0_3    conda-forge
        cycler                    0.10.0                     py_2    conda-forge
        dbus                      1.13.18              hb2f20db_0    defaults
        decorator                 4.4.2                      py_0    conda-forge
        defusedxml                0.6.0                      py_0    conda-forge
        entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
        expat                     2.2.10               he6710b0_2    defaults
        fiona                     1.8.18           py37h527b4ca_0    conda-forge
        flask                     1.1.2              pyh9f0ad1d_0    conda-forge
        fontconfig                2.13.1            h1056068_1002    conda-forge
        freetype                  2.10.4               he06d7ca_0    conda-forge
        freexl                    1.0.6                h27cfd23_0    defaults
        gdal                      3.1.4            py37h2b22b9e_0    conda-forge
        geopandas                 0.8.1                      py_0    conda-forge
        geos                      3.8.1                he1b5a44_0    conda-forge
        geotiff                   1.6.0                h5d11630_3    conda-forge
        gettext                   0.19.8.1          hf34092f_1004    conda-forge
        giflib                    5.2.1                h516909a_2    conda-forge
        glib                      2.66.3               h58526e2_0    conda-forge
        gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
        gstreamer                 1.14.5               h36ae1b5_2    conda-forge
        hdf4                      4.2.13            h10796ff_1004    conda-forge
        hdf5                      1.10.6          nompi_h6a2412b_1113    conda-forge
        icu                       67.1                 he1b5a44_0    conda-forge
        idna                      2.10               pyh9f0ad1d_0    conda-forge
        importlib-metadata        1.7.0            py37hc8dfbb8_0    conda-forge
        importlib_metadata        1.7.0                         0    conda-forge
        ipykernel                 5.3.4            py37h43977f1_0    conda-forge
        ipyleaflet                0.13.5             pyhd8ed1ab_0    conda-forge
        ipython                   7.16.1           py37h43977f1_0    conda-forge
        ipython_genutils          0.2.0                      py_1    conda-forge
        ipywidgets                7.6.2              pyhd3deb0d_1    conda-forge
        itsdangerous              1.1.0                      py_0    conda-forge
        jedi                      0.17.2           py37hc8dfbb8_0    conda-forge
        jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
        jpeg                      9d                   h516909a_0    conda-forge
        json-c                    0.13.1            hbfbb72e_1002    conda-forge
        json5                     0.9.4              pyh9f0ad1d_0    conda-forge
        jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
        jupyter-offlinenotebook   0.1.0                    pypi_0    pypi
        jupyter_client            6.1.6                      py_0    conda-forge
        jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
        jupyter_server            1.1.4            py37h89c1867_0    conda-forge
        jupyter_telemetry         0.0.5                      py_0    conda-forge
        jupyterhub-base           1.1.0                    py37_2    conda-forge
        jupyterhub-singleuser     1.1.0                    py37_2    conda-forge
        jupyterlab                3.0.1              pyhd8ed1ab_0    conda-forge
        jupyterlab_server         2.0.0              pyhd8ed1ab_0    conda-forge
        jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
        kealib                    1.4.14               h0042707_0    conda-forge
        kiwisolver                1.3.1            py37hc928c03_0    conda-forge
        krb5                      1.17.1               hfafb76e_1    conda-forge
        lcms2                     2.11                 hcbb858e_1    conda-forge
        ld_impl_linux-64          2.34                 h53a641e_7    conda-forge
        libblas                   3.9.0                6_openblas    conda-forge
        libcblas                  3.9.0                6_openblas    conda-forge
        libclang                  10.0.1          default_hde54327_1    conda-forge
        libcurl                   7.71.1               hcdd3856_3    conda-forge
        libdap4                   3.20.6               h1d1bd15_1    conda-forge
        libedit                   3.1.20191231         h46ee950_1    conda-forge
        libevent                  2.1.10               hcdb4288_3    conda-forge
        libffi                    3.2.1             he1b5a44_1007    conda-forge
        libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
        libgdal                   3.1.4                h670eac6_0    conda-forge
        libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
        libgfortran5              9.3.0               he4bcb1c_17    conda-forge
        libglib                   2.66.3               hbe7bbb4_0    conda-forge
        libgomp                   9.3.0               h5dbcf3e_17    conda-forge
        libiconv                  1.16                 h516909a_0    conda-forge
        libkml                    1.3.0             hd79254b_1012    conda-forge
        liblapack                 3.9.0                6_openblas    conda-forge
        libllvm10                 10.0.1               he513fc3_3    conda-forge
        libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
        libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
        libpng                    1.6.37               hed695b0_2    conda-forge
        libpq                     12.3                 hfd2b0eb_3    conda-forge
        libsodium                 1.0.17               h516909a_0    conda-forge
        libspatialindex           1.9.3                he1b5a44_3    conda-forge
        libspatialite             5.0.0                h4dde289_0    conda-forge
        libssh2                   1.9.0                hab1572f_4    conda-forge
        libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
        libtiff                   4.2.0                hdc55705_0    conda-forge
        libuuid                   2.32.1            h14c3975_1000    conda-forge
        libuv                     1.39.0               h516909a_0    conda-forge
        libwebp-base              1.1.0                h516909a_3    conda-forge
        libxcb                    1.14                 h7b6447c_0    defaults
        libxkbcommon              0.10.0               he1b5a44_0    conda-forge
        libxml2                   2.9.10               h68273f3_2    conda-forge
        lz4-c                     1.9.2                he1b5a44_3    conda-forge
        mako                      1.1.0                      py_0    conda-forge
        markupsafe                1.1.1            py37h8f50634_1    conda-forge
        matplotlib                3.3.3            py37h89c1867_0    conda-forge
        matplotlib-base           3.3.3            py37h4f6019d_0    conda-forge
        mistune                   0.8.4           py37h8f50634_1001    conda-forge
        munch                     2.5.0                      py_0    conda-forge
        mysql-common              8.0.21                        2    conda-forge
        mysql-libs                8.0.21               hf3661c5_2    conda-forge
        nbclassic                 0.2.5              pyhd8ed1ab_0    conda-forge
        nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
        nbformat                  5.0.7                      py_0    conda-forge
        nbresuse                  0.3.3                      py_0    conda-forge
        ncurses                   6.2                  he1b5a44_1    conda-forge
        netcdf4                   1.5.5.1         nompi_py37hdbee05a_100    conda-forge
        nodejs                    14.11.0              h568c755_0    conda-forge
        notebook                  6.0.3            py37hc8dfbb8_1    conda-forge
        nspr                      4.29                 he1b5a44_1    conda-forge
        nss                       3.60                 hb5efdd6_0    conda-forge
        nteract_on_jupyter        2.1.3                      py_0    conda-forge
        numpy                     1.19.4           py37haa41c4c_2    conda-forge
        oauthlib                  3.0.1                      py_0    conda-forge
        olefile                   0.46               pyh9f0ad1d_1    conda-forge
        openjpeg                  2.3.1                hf7af979_3    conda-forge
        openssl                   1.1.1i               h7f98852_0    conda-forge
        packaging                 20.4               pyh9f0ad1d_0    conda-forge
        pamela                    1.0.0                      py_0    conda-forge
        pandas                    1.2.0            py37hdc94413_0    conda-forge
        pandoc                    2.10.1               h516909a_0    conda-forge
        pandocfilters             1.4.2                      py_1    conda-forge
        parso                     0.7.1              pyh9f0ad1d_0    conda-forge
        pcre                      8.44                 he1b5a44_0    conda-forge
        pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
        pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
        pillow                    8.1.0            py37he6b4880_0    conda-forge
        pip                       20.1.1                     py_1    conda-forge
        pixman                    0.38.0            h516909a_1003    conda-forge
        poppler                   0.89.0               h4190859_1    conda-forge
        poppler-data              0.4.10                        0    conda-forge
        postgresql                12.3                 h6303168_3    conda-forge
        proj                      7.1.1                h966b41f_3    conda-forge
        prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
        prompt-toolkit            3.0.5                      py_1    conda-forge
        psutil                    5.7.2            py37h8f50634_0    conda-forge
        ptyprocess                0.6.0                   py_1001    conda-forge
        pycparser                 2.20               pyh9f0ad1d_2    conda-forge
        pycurl                    7.43.0.5         py37hce7685b_2    conda-forge
        pygments                  2.6.1                      py_0    conda-forge
        pyjwt                     1.7.1                      py_0    conda-forge
        pyopenssl                 19.1.0                     py_1    conda-forge
        pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
        pyproj                    2.6.1.post1      py37h6415a23_3    conda-forge
        pyqt                      5.12.3           py37h89c1867_6    conda-forge
        pyqt-impl                 5.12.3           py37he336c9b_6    conda-forge
        pyqt5-sip                 4.19.18          py37hcd2ae1e_6    conda-forge
        pyqtchart                 5.12             py37he336c9b_6    conda-forge
        pyqtwebengine             5.12.1           py37he336c9b_6    conda-forge
        pyrsistent                0.16.0           py37h8f50634_0    conda-forge
        pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
        python                    3.7.8           h6f2ec95_0_cpython    conda-forge
        python-dateutil           2.8.1                      py_0    conda-forge
        python-editor             1.0.4                      py_0    conda-forge
        python-json-logger        0.1.11                     py_0    conda-forge
        python_abi                3.7                     1_cp37m    conda-forge
        pytz                      2020.5             pyhd8ed1ab_0    conda-forge
        pyzmq                     19.0.1           py37hac76be4_0    conda-forge
        qt                        5.12.9               h1f2b2cb_0    conda-forge
        rasterio                  1.1.8            py37h527b4ca_0    conda-forge
        readline                  8.0                  he28a2e2_2    conda-forge
        requests                  2.24.0             pyh9f0ad1d_0    conda-forge
        rtree                     0.9.7            py37h0b55af0_0    conda-forge
        ruamel.yaml               0.16.6           py37h8f50634_1    conda-forge
        ruamel.yaml.clib          0.2.0            py37h8f50634_1    conda-forge
        scipy                     1.6.0            py37h14a347d_0    conda-forge
        send2trash                1.5.0                      py_0    conda-forge
        setuptools                49.2.0           py37hc8dfbb8_0    conda-forge
        shapely                   1.7.1            py37hedb1597_1    conda-forge
        six                       1.15.0             pyh9f0ad1d_0    conda-forge
        sniffio                   1.2.0            py37hc8dfbb8_0    conda-forge
        snuggs                    1.4.7                      py_0    conda-forge
        sqlalchemy                1.3.18           py37h8f50634_0    conda-forge
        sqlite                    3.34.0               h74cdb3f_0    conda-forge
        terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
        testpath                  0.4.4                      py_0    conda-forge
        tiledb                    2.1.5                h17508cd_0    conda-forge
        tk                        8.6.10               hed695b0_0    conda-forge
        tornado                   6.1              py37h4abf009_0    conda-forge
        tqdm                      4.55.1             pyhd8ed1ab_0    conda-forge
        traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
        traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
        typing_extensions         3.7.4.3                    py_0    conda-forge
        tzcode                    2020f                h7f98852_0    conda-forge
        urllib3                   1.25.10                    py_0    conda-forge
        wcwidth                   0.2.5              pyh9f0ad1d_0    conda-forge
        webencodings              0.5.1                      py_1    conda-forge
        werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
        wheel                     0.34.2                     py_1    conda-forge
        widgetsnbextension        3.5.1            py37hc8dfbb8_1    conda-forge
        xarray                    0.16.2             pyhd8ed1ab_0    conda-forge
        xerces-c                  3.2.3                hfe33f54_1    conda-forge
        xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
        xorg-libice               1.0.10               h516909a_0    conda-forge
        xorg-libsm                1.2.3             h84519dc_1000    conda-forge
        xorg-libx11               1.6.12               h516909a_0    conda-forge
        xorg-libxext              1.3.4                h516909a_0    conda-forge
        xorg-libxrender           0.9.10            h516909a_1002    conda-forge
        xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
        xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
        xorg-xproto               7.0.31            h14c3975_1007    conda-forge
        xz                        5.2.5                h516909a_1    conda-forge
        zeromq                    4.3.2                he1b5a44_2    conda-forge
        zipp                      3.1.0                      py_0    conda-forge
        zlib                      1.2.11            h516909a_1006    conda-forge
        zstd                      1.4.8                hdf46e1d_0    conda-forge
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
243.d9d134ad2ffdfb9205b3.js:2 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at https://hub.gke2.mybinder.org/user/jupyter-widgets-ipyleaflet-uyxyynfv/lab/extensions/jupyter-leaflet/static/243.d9d134ad2ffdfb9205b3.js:2:3143
    at Function.C.extend (https://hub.gke2.mybinder.org/user/jupyter-widgets-ipyleaflet-uyxyynfv/lab/extensions/jupyter-leaflet/static/243.d9d134ad2ffdfb9205b3.js:2:3162)
    at Object.665 (https://hub.gke2.mybinder.org/user/jupyter-widgets-ipyleaflet-uyxyynfv/lab/extensions/jupyter-leaflet/static/665.3328989849f89dbc115a.js:1:4763)
    at j (https://hub.gke2.mybinder.org/user/jupyter-widgets-ipyleaflet-uyxyynfv/lab/extensions/jupyter-leaflet/static/remoteEntry.d7ecc23c8a9ea32680f5.js:1:795)
    at https://hub.gke2.mybinder.org/user/jupyter-widgets-ipyleaflet-uyxyynfv/lab/extensions/jupyter-leaflet/static/remoteEntry.d7ecc23c8a9ea32680f5.js:1:3893
    at Object.w.<computed> (https://hub.gke2.mybinder.org/user/jupyter-widgets-ipyleaflet-uyxyynfv/lab/extensions/jupyter-leaflet/static/remoteEntry.d7ecc23c8a9ea32680f5.js:1:9876)
    at j (https://hub.gke2.mybinder.org/user/jupyter-widgets-ipyleaflet-uyxyynfv/lab/extensions/jupyter-leaflet/static/remoteEntry.d7ecc23c8a9ea32680f5.js:1:795)
    at Object.8197 (https://hub.gke2.mybinder.org/user/jupyter-widgets-ipyleaflet-uyxyynfv/lab/extensions/jupyter-leaflet/static/138.cfc773cf0b77045b9fbb.js:1:59505)
    at j (https://hub.gke2.mybinder.org/user/jupyter-widgets-ipyleaflet-uyxyynfv/lab/extensions/jupyter-leaflet/static/remoteEntry.d7ecc23c8a9ea32680f5.js:1:795)
    at Module.4795 (https://hub.gke2.mybinder.org/user/jupyter-widgets-ipyleaflet-uyxyynfv/lab/extensions/jupyter-leaflet/static/138.cfc773cf0b77045b9fbb.js:1:43381)
(anonymous) @ 243.d9d134ad2ffdfb9205b3.js:2
jlab_core.3099b1be2bd042406f2c.js:2 Ignored setting registry preload errors. Array(1)
(anonymous) @ jlab_core.3099b1be2bd042406f2c.js:2
jlab_core.3099b1be2bd042406f2c.js:2 Ignored setting registry preload errors. Array(1)
(anonymous) @ jlab_core.3099b1be2bd042406f2c.js:2
jlab_core.3099b1be2bd042406f2c.js:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.3099b1be2bd042406f2c.js:2
static/components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full,Safe&amp;delayStartupUntil=configured:1 Uncaught SyntaxError: Unexpected token '<'
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught ReferenceError: MathJax is not defined
    at i._onLoad (jlab_core.3099b1be2bd042406f2c.js:2)
    at HTMLScriptElement.<anonymous> (jlab_core.3099b1be2bd042406f2c.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.3099b1be2bd042406f2c.js:2
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Ee.t.send (272.2a8425db7209008188fc.js:1)
    at Ie.t.send (272.2a8425db7209008188fc.js:1)
    at n.o (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Ee.t.send (272.2a8425db7209008188fc.js:1)
    at Ie.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._propagateEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Ee.t.send (272.2a8425db7209008188fc.js:1)
    at Ie.t.send (272.2a8425db7209008188fc.js:1)
    at n.o (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Ee.t.send (272.2a8425db7209008188fc.js:1)
    at Ie.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._propagateEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Ee.t.send (272.2a8425db7209008188fc.js:1)
    at Ie.t.send (272.2a8425db7209008188fc.js:1)
    at n.o (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.3099b1be2bd042406f2c.js:2
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Ee.t.send (272.2a8425db7209008188fc.js:1)
    at Ie.t.send (272.2a8425db7209008188fc.js:1)
    at n.o (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Ee.t.send (272.2a8425db7209008188fc.js:1)
    at Ie.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._propagateEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Uncaught Error: Cannot send
    at l.send (jlab_core.3099b1be2bd042406f2c.js:2)
    at e.send (272.2a8425db7209008188fc.js:1)
    at Yt.t.send (272.2a8425db7209008188fc.js:1)
    at Xt.t.send (272.2a8425db7209008188fc.js:1)
    at n.<anonymous> (138.cfc773cf0b77045b9fbb.js:1)
    at n.fire (243.d9d134ad2ffdfb9205b3.js:2)
    at n._fireDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at n._handleDOMEvent (243.d9d134ad2ffdfb9205b3.js:2)
    at HTMLDivElement.r (243.d9d134ad2ffdfb9205b3.js:2)
jlab_core.3099b1be2bd042406f2c.js:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.3099b1be2bd042406f2c.js:2
jlab_core.3099b1be2bd042406f2c.js:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.3099b1be2bd042406f2c.js:2
</pre>
</details>

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Fixes #9566
Followup on #8562
Changes solution in #9484

## Code changes

If we restarted a kernel, then quickly evaluated a lot of cells, we were often seeing the cells evaluated out of order. This came because the initial evaluations would be queued (because we had the kernel restarting sentinel in place), but later evaluations would happen synchronously, even if there were still messages queued. The logic is now changed to (almost) always queue a message if there are already queued messages waiting to be sent to preserve the message order.

One exception to this is the kernel info request when we are restarting. We redo the logic in #9484 to encode the exception in the _sendMessage function (rather than hacking around the conditions for queueing a message). This brings the exception closer to the logic it is working around, so it is a bit cleaner.

Also, we realize that the sendMessage `queue` parameter is really signifying when we are sending pending messages. As such, we always try to send those messages if we can.

Finally, we saw that there was a race condition between sending messages after a restart and when the websocket was reconnected, leading to some stalled initial message replies. We delete the logic that sends pending messages on shutdown_reply, since those pending messages will be more correctly sent when the websocket reconnects anyway. We also don’t worry about setting the kernel session there since the calling function does that logic.

### CODE REVIEW

**Comment by jasongrout** [comment]
From https://github.com/jupyterlab/jupyterlab/issues/9566#issuecomment-756441733:

> I tried the generated binder, and I could see once that all the cells were marked with * but not executed (and the kernel was idle), but couldn't reproduce while recording a GIF. Maybe you solved the out-of-order bug and this is another one?

@davidbrochart - apparently that "other one" isn't solved quite yet if you are still seeing it :).

But I think this does solve the out-of-order problem.

I think there still may be issues with the logic of #8562 - would like to look at that logic again at some point.

**Comment by jasongrout** [comment]
@davidbrochart - did you review the code as well?

**Comment by jasongrout** [comment]
The usage test failure looks unrelated:

```
[I 2021-01-08 00:45:50.061 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "./test_install/bin/jupyter-labhub", line 8, in <module>
    sys.exit(main())
  File "/home/runner/work/jupyterlab/jupyterlab/test_install/lib/python3.8/site-packages/jupyterlab/labhubapp.py", line 531, in main
    return OverrideSingleUserNotebookApp.launch_instance(argv)
  File "/home/runner/work/jupyterlab/jupyterlab/test_install/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 500, in launch_instance
    serverapp.start()
  File "/home/runner/work/jupyterlab/jupyterlab/test_install/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1966, in start
    self.start_app()
  File "/home/runner/work/jupyterlab/jupyterlab/test_install/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1931, in start_app
    self._handle_browser_opening()
  File "/home/runner/work/jupyterlab/jupyterlab/test_install/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 978, in _handle_browser_opening
    if self.starter_app:
  File "/home/runner/work/jupyterlab/jupyterlab/test_install/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 956, in starter_app
    return self.extension_manager.extension_points.get(name, None).app
AttributeError: 'NoneType' object has no attribute 'app'
+ kill 10128
./scripts/ci_script.sh: line 318: kill: (10128) - No such process
Error: Process completed with exit code 1.
```

**Comment by jasongrout** [comment]
The linkcheck failure also looks unrelated - a bunch of links have a `//` in them, apparently:

> FAILED docs/build/html/user/urls.html::/home/runner/work/jupyterlab/jupyterlab/docs/build/html/user/urls.html <a href=https://github.com/jupyterlab/jupyterlab//master/docs/source/user/urls.rst>

**Comment by jasongrout** [comment]
> The linkcheck failure also looks unrelated - a bunch of links have a `//` in them, apparently:

Link check failure addressed in https://github.com/jupyterlab/jupyterlab/pull/9572

**Comment by davidbrochart** [comment]
> @davidbrochart - did you review the code as well?

I don't think I can make a valuable review yet, I've never looked at jlab's code :smile:

File: packages/services/src/kernel/messages.ts [hunk 1]
```diff
@@ -1030,6 +1030,13 @@ export interface IExecuteRequestMsg extends IShellMessage<'execute_request'> {
   };
 }
 
+/**
+ * Test whether a kernel message is an `'execute_request'` message.
+ */
+export function isExecuteRequestMsg(msg: IMessage): msg is IExecuteRequestMsg {
```
Comment (jtpio) [inline packages/services/src/kernel/messages.ts:1036]: Looking at the current diff, is this function still needed?

Comment (jasongrout) [reply packages/services/src/kernel/messages.ts:1036]: Good point - not needed, but still useful and consistent with similar functions elsewhere. I was surprised it wasn't defined for consistency. If you want, I can delete it.

Comment (jasongrout) [reply packages/services/src/kernel/messages.ts]: Deleted...

**Comment by jasongrout** [comment]
@jtpio - just checking, was your comment an indication that you reviewed the PR as a whole?

**Comment by Zsailer** [comment]
@jasongrout, the failing test will be fixed by jupyter-server/jupyter_server#379. I'll make a patch release in a few minutes.

**Review by blink1073 — APPROVED** [review]
Looks good, thank you!

**Comment by blink1073** [comment]
I'll restart CI once there is a new server release.  Once the usage test passes, I'll merge an cut a release.

**Comment by Zsailer** [comment]
jupyter_server v.1.2.1 released.

**Comment by blink1073** [comment]
Good to go, thanks all!
