### PR TITLE
Fix shutdown kernel button in running panel

### LINKED ISSUE #16645: Shutdown item in running panel is broken
## Description

Currently the click on the shutdown button of an running panel item is broken.
This is a consequence of the tree view PR.

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Expected behavior

Shutdown buttons work

## Context

- Operating System and version:debian
- Browser and version: chrome
- JupyterLab version: current master

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #16645

## Code changes

Shutdown unconditionnally of the event status
Don't un-/collapse when clicking on the shutdown button
Show the shutdown button when the item gains focus

## User-facing changes

Shutdown kernel button works

## Backwards-incompatible changes

None

### CODE REVIEW

File: packages/running/src/index.tsx [hunk 1]
```diff
@@ -195,6 +195,10 @@ function Item(props: {
   collapseToggled: ISignal<Section, boolean>;
 }) {
   const { runningItem } = props;
+  // Use a ref instead of a state because the state does not have the time
+  // to update in the callbacks
+  const [collapsed, collapse] = React.useState(false);
```
Comment (JasonWeill) [inline packages/running/src/index.tsx:200]:
```suggestion
  const [collapsed, setCollapsed] = React.useState(false);
```

The usual React recommendation is to name the two values `[foo, setFoo]`. The `collapse`/`setCollapsed` function never gets called, so this is a minor suggestion.

**Review by JasonWeill — APPROVED** [review]
Thank you! I tested this locally and it works for me.
