### PR TITLE
Fixing dialog closing unexpectedly when typing in the textarea

### LINKED ISSUE #14511: Dialog closes unexpectedly when typing in the textarea
## Description

I'm working on a JupyterLab extension where I need to create a Dialog containing a `textarea` and several `input` boxes. I have implemented a custom class that `extends ReactWidget and implements Dialog.IBodyWidget<ReactWidget>`. I pass an instance of this class as the body parameter to the `showDialog` function. The dialog mechanism is functioning correctly, but I'm encountering an issue with the `textarea`. Whenever I click inside the `textarea`, type some text, and press "enter", it automatically closes the dialog as if I had pressed the "ok" button. I suspect this issue is related to event listeners.

## Reproduce

1. Create a new dialog class (I used: `extends ReactWidget and implements Dialog.IBodyWidget<ReactWidget>`).
2. In the `render(): JSX.Element` method add some `textarea`.
3. Try to add text into the `textarea` and then press "enter".

## Expected behavior

It should just add a new line instead of closing the dialog.

## Context

- Operating System and version: Linux 5.14.21
- Browser and version: Chrome 112
- JupyterLab version: 3.6.3

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /opt/conda/envs/jupyterlab-ext/bin
        /opt/conda/condabin
        /opt/conda/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /opt/conda/envs/jupyterlab-ext/bin
        /opt/conda/envs/jupyterlab-ext/lib/python311.zip
        /opt/conda/envs/jupyterlab-ext/lib/python3.11
        /opt/conda/envs/jupyterlab-ext/lib/python3.11/lib-dynload
        /opt/conda/envs/jupyterlab-ext/lib/python3.11/site-packages
        /tmp/myextension

sys.executable:
        /opt/conda/envs/jupyterlab-ext/bin/python

sys.version:
        3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]

platform.platform():
        Linux-5.14.21-150400.24.46-default-x86_64-with-glibc2.35

which -a jupyter:
        /opt/conda/envs/jupyterlab-ext/bin/jupyter
        /opt/conda/bin/jupyter

pip list:
        Package                       Version     Editable project location
        ----------------------------- ----------- -------------------------
        anyio                         3.6.2
        argon2-cffi                   21.3.0
        argon2-cffi-bindings          21.2.0
        arrow                         1.2.3
        asttokens                     2.2.1
        attrs                         22.2.0
        Babel                         2.12.1
        backcall                      0.2.0
        backports.functools-lru-cache 1.6.4
        beautifulsoup4                4.12.2
        binaryornot                   0.4.4
        bleach                        6.0.0
        boto3                         1.26.116
        botocore                      1.29.118
        brotlipy                      0.7.0
        certifi                       2022.12.7
        cffi                          1.15.1
        chardet                       5.1.0
        charset-normalizer            3.1.0
        click                         8.1.3
        comm                          0.1.3
        cookiecutter                  2.1.1
        cryptography                  40.0.2
        debugpy                       1.6.7
        decorator                     5.1.1
        defusedxml                    0.7.1
        deprecation                   2.1.0
        entrypoints                   0.4
        executing                     1.2.0
        fastjsonschema                2.16.3
        flit_core                     3.8.0
        fqdn                          1.5.1
        idna                          3.4
        importlib-metadata            6.6.0
        importlib-resources           5.12.0
        ipykernel                     6.22.0
        ipython                       8.13.1
        ipython-genutils              0.2.0
        isoduration                   20.11.0
        jedi                          0.18.2
        Jinja2                        3.1.2
        jinja2-time                   0.2.0
        jmespath                      1.0.1
        json5                         0.9.5
        jsonpointer                   2.3
        jsonschema                    4.17.3
        jupyter_client                8.2.0
        jupyter_core                  5.3.0
        jupyter-events                0.6.3
        jupyter_packaging             0.12.3
        jupyter_server                2.5.0
        jupyter_server_terminals      0.4.4
        jupyterlab                    3.5.3
        jupyterlab-pygments           0.2.2
        jupyterlab_server             2.22.1
        MarkupSafe                    2.1.2
        matplotlib-inline             0.1.6
        mistune                       2.0.5
        myextension                   0.1.0       /tmp/myextension
        nbclassic                     0.5.6
        nbclient                      0.7.4
        nbconvert                     7.3.1
        nbformat                      5.8.0
        nest-asyncio                  1.5.6
        notebook                      6.5.4
        notebook_shim                 0.2.3
        packaging                     23.1
        pandocfilters                 1.5.0
        parso                         0.8.3
        pexpect                       4.8.0
        pickleshare                   0.7.5
        pip                           23.1.2
        pkgutil_resolve_name          1.3.10
        platformdirs                  3.5.0
        prometheus-client             0.16.0
        prompt-toolkit                3.0.38
        psutil                        5.9.5
        ptyprocess                    0.7.0
        pure-eval                     0.2.2
        pycparser                     2.21
        Pygments                      2.15.1
        pyOpenSSL                     23.1.1
        pyrsistent                    0.19.3
        PySocks                       1.7.1
        python-dateutil               2.8.2
        python-json-logger            2.0.7
        python-slugify                8.0.1
        pytz                          2023.3
        PyYAML                        6.0
        pyzmq                         25.0.2
        requests                      2.29.0
        requests-futures              1.0.0
        rfc3339-validator             0.1.4
        rfc3986-validator             0.1.1
        s3transfer                    0.6.0
        Send2Trash                    1.8.2
        setuptools                    67.7.2
        six                           1.16.0
        sniffio                       1.3.0
        soupsieve                     2.3.2.post1
        stack-data                    0.6.2
        terminado                     0.17.1
        text-unidecode                1.3
        tinycss2                      1.2.1
        tomli                         2.0.1
        tomlkit                       0.11.8
        tornado                       6.3
        traitlets                     5.9.0
        typing_extensions             4.5.0
        Unidecode                     1.3.6
        uri-template                  1.2.0
        urllib3                       1.26.15
        wcwidth                       0.2.6
        webcolors                     1.13
        webencodings                  0.5.1
        websocket-client              1.5.1
        wheel                         0.40.0
        zipp                          3.15.0

conda list:
        # packages in environment at /opt/conda/envs/jupyterlab-ext:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       2_gnu    conda-forge
        anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
        argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
        argon2-cffi-bindings      21.2.0          py311hd4cff14_3    conda-forge
        arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
        asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
        attrs                     22.2.0             pyh71513ae_0    conda-forge
        babel                     2.12.1             pyhd8ed1ab_1    conda-forge
        backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
        backports                 1.0                pyhd8ed1ab_3    conda-forge
        backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
        beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
        binaryornot               0.4.4                      py_1    conda-forge
        bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
        boto3                     1.26.116                 pypi_0    pypi
        botocore                  1.29.118                 pypi_0    pypi
        brotlipy                  0.7.0           py311hd4cff14_1005    conda-forge
        bzip2                     1.0.8                h7f98852_4    conda-forge
        c-ares                    1.18.1               h7f98852_0    conda-forge
        ca-certificates           2022.12.7            ha878542_0    conda-forge
        certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
        cffi                      1.15.1          py311h409f033_3    conda-forge
        chardet                   5.1.0           py311h38be061_0    conda-forge
        charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
        click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
        comm                      0.1.3              pyhd8ed1ab_0    conda-forge
        cookiecutter              2.1.1              pyh6c4a22f_0    conda-forge
        cryptography              40.0.2          py311h9b4c7bb_0    conda-forge
        curl                      8.0.1                h588be90_0    conda-forge
        debugpy                   1.6.7           py311hcafe171_0    conda-forge
        decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
        defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
        deprecation               2.1.0              pyh9f0ad1d_0    conda-forge
        entrypoints               0.4                pyhd8ed1ab_0    conda-forge
        executing                 1.2.0              pyhd8ed1ab_0    conda-forge
        flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
        fqdn                      1.5.1                    pypi_0    pypi
        gettext                   0.21.1               h27087fc_0    conda-forge
        git                       2.40.1          pl5321h86e50cf_0    conda-forge
        icu                       70.1                 h27087fc_0    conda-forge
        idna                      3.4                pyhd8ed1ab_0    conda-forge
        importlib-metadata        6.6.0              pyha770c72_0    conda-forge
        importlib_metadata        6.6.0                hd8ed1ab_0    conda-forge
        importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
        ipykernel                 6.22.0             pyh210e3f2_0    conda-forge
        ipython                   8.13.1             pyh41d4057_0    conda-forge
        ipython_genutils          0.2.0                      py_1    conda-forge
        isoduration               20.11.0                  pypi_0    pypi
        jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
        jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
        jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
        jmespath                  1.0.1                    pypi_0    pypi
        json5                     0.9.5              pyh9f0ad1d_0    conda-forge
        jsonpointer               2.3                      pypi_0    pypi
        jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
        jupyter-packaging         0.12.3             pyha770c72_0    conda-forge
        jupyter_client            8.2.0              pyhd8ed1ab_0    conda-forge
        jupyter_core              5.3.0           py311h38be061_0    conda-forge
        jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
        jupyter_server            2.5.0              pyhd8ed1ab_0    conda-forge
        jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
        jupyterlab                3.5.3              pyhd8ed1ab_0    conda-forge
        jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
        jupyterlab_server         2.22.1             pyhd8ed1ab_0    conda-forge
        keyutils                  1.6.1                h166bdaf_0    conda-forge
        krb5                      1.20.1               h81ceb04_0    conda-forge
        ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
        libcurl                   8.0.1                h588be90_0    conda-forge
        libedit                   3.1.20191231         he28a2e2_2    conda-forge
        libev                     4.33                 h516909a_1    conda-forge
        libexpat                  2.5.0                hcb278e6_1    conda-forge
        libffi                    3.4.2                h7f98852_5    conda-forge
        libgcc-ng                 12.2.0              h65d4601_19    conda-forge
        libgomp                   12.2.0              h65d4601_19    conda-forge
        libiconv                  1.17                 h166bdaf_0    conda-forge
        libnghttp2                1.52.0               h61bc06f_0    conda-forge
        libnsl                    2.0.0                h7f98852_0    conda-forge
        libsodium                 1.0.18               h36c2ea0_1    conda-forge
        libsqlite                 3.40.0               h753d276_1    conda-forge
        libssh2                   1.10.0               hf14f497_3    conda-forge
        libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
        libuuid                   2.38.1               h0b41bf4_0    conda-forge
        libuv                     1.44.2               h166bdaf_0    conda-forge
        libzlib                   1.2.13               h166bdaf_4    conda-forge
        markupsafe                2.1.2           py311h2582759_0    conda-forge
        matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
        mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
        myextension               0.1.0                     dev_0    <develop>
        nbclassic                 0.5.6              pyh8b2e9e2_0    conda-forge
        nbclient                  0.7.4              pyhd8ed1ab_0    conda-forge
        nbconvert-core            7.3.1              pyhd8ed1ab_0    conda-forge
        nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
        ncurses                   6.3                  h27087fc_1    conda-forge
        nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
        nodejs                    18.15.0              h8d033a5_0    conda-forge
        notebook                  6.5.4              pyha770c72_0    conda-forge
        notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
        openssl                   3.1.0                hd590300_3    conda-forge
        packaging                 23.1               pyhd8ed1ab_0    conda-forge
        pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
        parso                     0.8.3              pyhd8ed1ab_0    conda-forge
        pcre2                     10.40                hc3806b6_0    conda-forge
        perl                      5.32.1          2_h7f98852_perl5    conda-forge
        pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
        pickleshare               0.7.5                   py_1003    conda-forge
        pip                       23.1.2             pyhd8ed1ab_0    conda-forge
        pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
        platformdirs              3.5.0              pyhd8ed1ab_0    conda-forge
        prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
        prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
        prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
        psutil                    5.9.5           py311h2582759_0    conda-forge
        ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
        pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
        pycparser                 2.21               pyhd8ed1ab_0    conda-forge
        pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
        pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
        pyrsistent                0.19.3          py311h2582759_0    conda-forge
        pysocks                   1.7.1              pyha2e5f31_6    conda-forge
        python                    3.11.3          h2755cc3_0_cpython    conda-forge
        python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
        python-fastjsonschema     2.16.3             pyhd8ed1ab_0    conda-forge
        python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
        python-slugify            8.0.1              pyhd8ed1ab_0    conda-forge
        python_abi                3.11                    3_cp311    conda-forge
        pytz                      2023.3             pyhd8ed1ab_0    conda-forge
        pyyaml                    6.0             py311hd4cff14_5    conda-forge
        pyzmq                     25.0.2          py311hd6ccaeb_0    conda-forge
        readline                  8.2                  h8228510_1    conda-forge
        requests                  2.29.0             pyhd8ed1ab_0    conda-forge
        requests-futures          1.0.0                    pypi_0    pypi
        rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
        rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
        s3transfer                0.6.0                    pypi_0    pypi
        send2trash                1.8.2              pyh41d4057_0    conda-forge
        setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
        six                       1.16.0             pyh6c4a22f_0    conda-forge
        sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
        soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
        stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
        terminado                 0.17.1             pyh41d4057_0    conda-forge
        text-unidecode            1.3                        py_0    conda-forge
        tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
        tk                        8.6.12               h27826a3_0    conda-forge
        tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
        tomlkit                   0.11.8             pyha770c72_0    conda-forge
        tornado                   6.3             py311h2582759_0    conda-forge
        traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
        typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
        typing_extensions         4.5.0              pyha770c72_0    conda-forge
        tzdata                    2023c                h71feb2d_0    conda-forge
        unidecode                 1.3.6              pyhd8ed1ab_0    conda-forge
        uri-template              1.2.0                    pypi_0    pypi
        urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
        wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
        webcolors                 1.13                     pypi_0    pypi
        webencodings              0.5.1                      py_1    conda-forge
        websocket-client          1.5.1              pyhd8ed1ab_0    conda-forge
        wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
        xz                        5.2.6                h166bdaf_0    conda-forge
        yaml                      0.2.5                h7f98852_2    conda-forge
        zeromq                    4.3.4                h9c3ff4c_1    conda-forge
        zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
        zlib                      1.2.13               h166bdaf_4    conda-forge
        zstd                      1.5.2                h3eb15da_6    conda-forge

conda env:
        name: jupyterlab-ext
        channels:
          - conda-forge
        dependencies:
          - _libgcc_mutex=0.1=conda_forge
          - _openmp_mutex=4.5=2_gnu
          - anyio=3.6.2=pyhd8ed1ab_0
          - argon2-cffi=21.3.0=pyhd8ed1ab_0
          - argon2-cffi-bindings=21.2.0=py311hd4cff14_3
          - arrow=1.2.3=pyhd8ed1ab_0
          - asttokens=2.2.1=pyhd8ed1ab_0
          - attrs=22.2.0=pyh71513ae_0
          - babel=2.12.1=pyhd8ed1ab_1
          - backcall=0.2.0=pyh9f0ad1d_0
          - backports=1.0=pyhd8ed1ab_3
          - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
          - beautifulsoup4=4.12.2=pyha770c72_0
          - binaryornot=0.4.4=py_1
          - bleach=6.0.0=pyhd8ed1ab_0
          - brotlipy=0.7.0=py311hd4cff14_1005
          - bzip2=1.0.8=h7f98852_4
          - c-ares=1.18.1=h7f98852_0
          - ca-certificates=2022.12.7=ha878542_0
          - certifi=2022.12.7=pyhd8ed1ab_0
          - cffi=1.15.1=py311h409f033_3
          - chardet=5.1.0=py311h38be061_0
          - charset-normalizer=3.1.0=pyhd8ed1ab_0
          - click=8.1.3=unix_pyhd8ed1ab_2
          - comm=0.1.3=pyhd8ed1ab_0
          - cookiecutter=2.1.1=pyh6c4a22f_0
          - cryptography=40.0.2=py311h9b4c7bb_0
          - curl=8.0.1=h588be90_0
          - debugpy=1.6.7=py311hcafe171_0
          - decorator=5.1.1=pyhd8ed1ab_0
          - defusedxml=0.7.1=pyhd8ed1ab_0
          - deprecation=2.1.0=pyh9f0ad1d_0
          - entrypoints=0.4=pyhd8ed1ab_0
          - executing=1.2.0=pyhd8ed1ab_0
          - flit-core=3.8.0=pyhd8ed1ab_0
          - gettext=0.21.1=h27087fc_0
          - git=2.40.1=pl5321h86e50cf_0
          - icu=70.1=h27087fc_0
          - idna=3.4=pyhd8ed1ab_0
          - importlib-metadata=6.6.0=pyha770c72_0
          - importlib_metadata=6.6.0=hd8ed1ab_0
          - importlib_resources=5.12.0=pyhd8ed1ab_0
          - ipykernel=6.22.0=pyh210e3f2_0
          - ipython=8.13.1=pyh41d4057_0
          - ipython_genutils=0.2.0=py_1
          - jedi=0.18.2=pyhd8ed1ab_0
          - jinja2=3.1.2=pyhd8ed1ab_1
          - jinja2-time=0.2.0=pyhd8ed1ab_3
          - json5=0.9.5=pyh9f0ad1d_0
          - jsonschema=4.17.3=pyhd8ed1ab_0
          - jupyter-packaging=0.12.3=pyha770c72_0
          - jupyter_client=8.2.0=pyhd8ed1ab_0
          - jupyter_core=5.3.0=py311h38be061_0
          - jupyter_events=0.6.3=pyhd8ed1ab_0
          - jupyter_server=2.5.0=pyhd8ed1ab_0
          - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
          - jupyterlab=3.5.3=pyhd8ed1ab_0
          - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
          - jupyterlab_server=2.22.1=pyhd8ed1ab_0
          - keyutils=1.6.1=h166bdaf_0
          - krb5=1.20.1=h81ceb04_0
          - ld_impl_linux-64=2.40=h41732ed_0
          - libcurl=8.0.1=h588be90_0
          - libedit=3.1.20191231=he28a2e2_2
          - libev=4.33=h516909a_1
          - libexpat=2.5.0=hcb278e6_1
          - libffi=3.4.2=h7f98852_5
          - libgcc-ng=12.2.0=h65d4601_19
          - libgomp=12.2.0=h65d4601_19
          - libiconv=1.17=h166bdaf_0
          - libnghttp2=1.52.0=h61bc06f_0
          - libnsl=2.0.0=h7f98852_0
          - libsodium=1.0.18=h36c2ea0_1
          - libsqlite=3.40.0=h753d276_1
          - libssh2=1.10.0=hf14f497_3
          - libstdcxx-ng=12.2.0=h46fd767_19
          - libuuid=2.38.1=h0b41bf4_0
          - libuv=1.44.2=h166bdaf_0
          - libzlib=1.2.13=h166bdaf_4
          - markupsafe=2.1.2=py311h2582759_0
          - matplotlib-inline=0.1.6=pyhd8ed1ab_0
          - mistune=2.0.5=pyhd8ed1ab_0
          - nbclassic=0.5.6=pyh8b2e9e2_0
          - nbclient=0.7.4=pyhd8ed1ab_0
          - nbconvert-core=7.3.1=pyhd8ed1ab_0
          - nbformat=5.8.0=pyhd8ed1ab_0
          - ncurses=6.3=h27087fc_1
          - nest-asyncio=1.5.6=pyhd8ed1ab_0
          - nodejs=18.15.0=h8d033a5_0
          - notebook=6.5.4=pyha770c72_0
          - notebook-shim=0.2.3=pyhd8ed1ab_0
          - openssl=3.1.0=hd590300_3
          - packaging=23.1=pyhd8ed1ab_0
          - pandocfilters=1.5.0=pyhd8ed1ab_0
          - parso=0.8.3=pyhd8ed1ab_0
          - pcre2=10.40=hc3806b6_0
          - perl=5.32.1=2_h7f98852_perl5
          - pexpect=4.8.0=pyh1a96a4e_2
          - pickleshare=0.7.5=py_1003
          - pip=23.1.2=pyhd8ed1ab_0
          - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
          - platformdirs=3.5.0=pyhd8ed1ab_0
          - prometheus_client=0.16.0=pyhd8ed1ab_0
          - prompt-toolkit=3.0.38=pyha770c72_0
          - prompt_toolkit=3.0.38=hd8ed1ab_0
          - psutil=5.9.5=py311h2582759_0
          - ptyprocess=0.7.0=pyhd3deb0d_0
          - pure_eval=0.2.2=pyhd8ed1ab_0
          - pycparser=2.21=pyhd8ed1ab_0
          - pygments=2.15.1=pyhd8ed1ab_0
          - pyopenssl=23.1.1=pyhd8ed1ab_0
          - pyrsistent=0.19.3=py311h2582759_0
          - pysocks=1.7.1=pyha2e5f31_6
          - python=3.11.3=h2755cc3_0_cpython
          - python-dateutil=2.8.2=pyhd8ed1ab_0
          - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
          - python-json-logger=2.0.7=pyhd8ed1ab_0
          - python-slugify=8.0.1=pyhd8ed1ab_0
          - python_abi=3.11=3_cp311
          - pytz=2023.3=pyhd8ed1ab_0
          - pyyaml=6.0=py311hd4cff14_5
          - pyzmq=25.0.2=py311hd6ccaeb_0
          - readline=8.2=h8228510_1
          - requests=2.29.0=pyhd8ed1ab_0
          - rfc3339-validator=0.1.4=pyhd8ed1ab_0
          - rfc3986-validator=0.1.1=pyh9f0ad1d_0
          - send2trash=1.8.2=pyh41d4057_0
          - setuptools=67.7.2=pyhd8ed1ab_0
          - six=1.16.0=pyh6c4a22f_0
          - sniffio=1.3.0=pyhd8ed1ab_0
          - soupsieve=2.3.2.post1=pyhd8ed1ab_0
          - stack_data=0.6.2=pyhd8ed1ab_0
          - terminado=0.17.1=pyh41d4057_0
          - text-unidecode=1.3=py_0
          - tinycss2=1.2.1=pyhd8ed1ab_0
          - tk=8.6.12=h27826a3_0
          - tomli=2.0.1=pyhd8ed1ab_0
          - tomlkit=0.11.8=pyha770c72_0
          - tornado=6.3=py311h2582759_0
          - traitlets=5.9.0=pyhd8ed1ab_0
          - typing-extensions=4.5.0=hd8ed1ab_0
          - typing_extensions=4.5.0=pyha770c72_0
          - tzdata=2023c=h71feb2d_0
          - unidecode=1.3.6=pyhd8ed1ab_0
          - urllib3=1.26.15=pyhd8ed1ab_0
          - wcwidth=0.2.6=pyhd8ed1ab_0
          - webencodings=0.5.1=py_1
          - websocket-client=1.5.1=pyhd8ed1ab_0
          - wheel=0.40.0=pyhd8ed1ab_0
          - xz=5.2.6=h166bdaf_0
          - yaml=0.2.5=h7f98852_2
          - zeromq=4.3.4=h9c3ff4c_1
          - zipp=3.15.0=pyhd8ed1ab_0
          - zlib=1.2.13=h166bdaf_4
          - zstd=1.5.2=h3eb15da_6
          - pip:
              - boto3==1.26.116
              - botocore==1.29.118
              - fqdn==1.5.1
              - isoduration==20.11.0
              - jmespath==1.0.1
              - jsonpointer==2.3
              - requests-futures==1.0.0
              - s3transfer==0.6.0
              - uri-template==1.2.0
              - webcolors==1.13
        prefix: /opt/conda/envs/jupyterlab-ext
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by Rishab87**
## References

Fixes #14511 

## Code changes
I've added test in my first commit as told by @krassowski in discussions of this issue. This test is failing which is the expected behaviour for now:

```bash
 ● @jupyterlab/apputils › Dialog › #handleEvent() › keydown › should not accept on enter key within textarea

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      213 |           }
      214 |   
    > 215 |           expect(dialog.isVisible).toBe(true);
          |                                    ^
      216 |   
      217 |           simulate(dialog.node, 'keydown', { key: 'Enter', keyCode: 13 });
      218 |   

      at Object.<anonymous> (test/dialog.spec.tsx:215:36)


 RUNS  test/sessioncontext.spec.ts
```

### CODE REVIEW

**Comment by krassowski** [comment]
The test looks good to me!

File: packages/apputils/src/dialog.tsx [hunk 1]
```diff
@@ -440,8 +440,8 @@ export class Dialog<T> extends Widget {
 
         if (activeEl instanceof HTMLButtonElement) {
           index = this._buttonNodes.indexOf(activeEl);
```
Comment (krassowski) [inline packages/apputils/src/dialog.tsx:442]: Can we now defined index as `const` here and remove line 439?

**Comment by krassowski** [comment]
It looks like test failures are related:

```
 FAIL  test/dialog.spec.tsx
  ● @jupyterlab/apputils › Dialog › #handleEvent() › keydown › should resolve with currently focused button

    thrown: undefined

      at _getError (../../node_modules/jest-circus/build/utils.js:424:18)
          at Array.map (<anonymous>)
```

and a number of tests timing out, e.g.:

```
  ● @jupyterlab/apputils › InputDialog › getBoolean() › should be false by default

    thrown: "Exceeded timeout of 10000 ms for a test.
```

I think that these tests may need work.

**Comment by Rishab87** [comment]
@krassowski, I've fixed tests timing out issue but but for thrown undefined I've observed few things:
- index was coming undefined in one case but then I used default value if index not present but still getting that thrown undefined error.
- after           simulate(dialog.node, 'keydown', { keyCode: 13 }); in should resolve with currently focused button test case I'm getting document active element as htmlBodyElement but inside main file I was getting htmlButtonElement as active for this test case.
 here is my current implementation:
 ```javascript
  case 13: {
        // Enter.
        event.stopPropagation();
        event.preventDefault();

        const activeEl = document.activeElement;
        let index:number | undefined = this._defaultButton;


        if (activeEl instanceof HTMLButtonElement) {
          index = this._buttonNodes.indexOf(activeEl);
          this.resolve(index !== -1 ? index : 0);
        } else if(!(activeEl instanceof HTMLTextAreaElement) || !activeEl){
          this.resolve(index !== undefined ? index : 0);        
        }
        break;
      }
```
I've tried many things but not able to resolve this test case, can you please guide me on this?

**Comment by krassowski** [comment]
Not a good idea immediately - if you could push your changes I can try to poke at it locally later

**Comment by Rishab87** [comment]
@krassowski , I've pushed the code

**Comment by Rishab87** [comment]
@krassowski , I've fixed the issue now all tests pass, the issue was because every test case needs to be resolved in jest otherwise it will throw undefined but if we resolve in case of this issue then dialog box will close which is not the expected behaviour so promise should not be resolved in this case so I added a generalized work around for this which can help in future test cases too where promises should not resolve.

**Comment by Rishab87** [comment]
@krassowski anything else I need to change here?

File: packages/apputils/test/dialog.spec.tsx [hunk 2]
```diff
@@ -178,6 +223,35 @@ describe('@jupyterlab/apputils', () => {
...
+          const promptPromise = dialog.launch();
+
+          await dialog.resolveFor(async () => {
+            const textarea = dialog.node.querySelector('textarea');
+            textarea!.focus();
+
+            simulate(dialog.node, 'keydown', { keyCode: 13 });
+
+            await new Promise(resolve => setTimeout(resolve, 50));
+          });
```
Comment (krassowski) [inline packages/apputils/test/dialog.spec.tsx:242]: If you undo your changes in `dialog.tsx`, does it pass, or does it fail?

Comment (krassowski) [reply packages/apputils/test/dialog.spec.tsx:242]: I just struggle to follow this test, it feels like we need to simplify the logic.

Comment (Rishab87) [reply packages/apputils/test/dialog.spec.tsx]: You're right, I've fixed it now and implemented a much simplified approach, I should've thought it carefully before pushing, now it works as expected

File: packages/apputils/src/dialog.tsx [hunk 3]
```diff
@@ -436,12 +436,14 @@ export class Dialog<T> extends Widget {
         event.preventDefault();
 
         const activeEl = document.activeElement;
-        let index: number | undefined;
+        let index: number | undefined = this._defaultButton;
 
         if (activeEl instanceof HTMLButtonElement) {
           index = this._buttonNodes.indexOf(activeEl);
+          this.resolve(index !== -1 ? index : 0);
+        } else if (!(activeEl instanceof HTMLTextAreaElement) || !activeEl) {
```
Comment (krassowski) [inline packages/apputils/src/dialog.tsx:444]: It is not immediately clear to me why there is `|| !activeEl` part in here. Would it still work without it?

Comment (Rishab87) [reply packages/apputils/src/dialog.tsx]: Yes it still works without it, made the changes

File: packages/apputils/src/dialog.tsx [hunk 4]
```diff
@@ -436,12 +436,14 @@ export class Dialog<T> extends Widget {
         event.preventDefault();
 
         const activeEl = document.activeElement;
-        let index: number | undefined;
+        let index: number | undefined = this._defaultButton;
 
         if (activeEl instanceof HTMLButtonElement) {
           index = this._buttonNodes.indexOf(activeEl);
+          this.resolve(index !== -1 ? index : 0);
```
Comment (krassowski) [inline packages/apputils/src/dialog.tsx:443]: Thinking about why index might be `-1`. This could be if the react body had a button which is not a button node. I think in that case we would not want to resolve either. Say if there was "Help" button in extension author's code.

File: packages/apputils/src/dialog.tsx [hunk 5]
```diff
@@ -436,12 +436,14 @@ export class Dialog<T> extends Widget {
         event.preventDefault();
 
         const activeEl = document.activeElement;
-        let index: number | undefined;
+        let index: number | undefined = this._defaultButton;
 
         if (activeEl instanceof HTMLButtonElement) {
           index = this._buttonNodes.indexOf(activeEl);
```
Comment (krassowski) [inline packages/apputils/src/dialog.tsx:442]: Index here is always overwritten, we may as well remove the assignment above to reduce cognitive complexity

```suggestion
          const index = this._buttonNodes.indexOf(activeEl);
```

File: packages/apputils/src/dialog.tsx [hunk 6]
```diff
@@ -436,12 +436,14 @@ export class Dialog<T> extends Widget {
         event.preventDefault();
 
         const activeEl = document.activeElement;
-        let index: number | undefined;
+        let index: number | undefined = this._defaultButton;
```
Comment (krassowski) [inline packages/apputils/src/dialog.tsx:439]:
```suggestion
```

File: packages/apputils/src/dialog.tsx [hunk 7]
```diff
@@ -436,12 +436,14 @@ export class Dialog<T> extends Widget {
...
 
         if (activeEl instanceof HTMLButtonElement) {
           index = this._buttonNodes.indexOf(activeEl);
+          this.resolve(index !== -1 ? index : 0);
+        } else if (!(activeEl instanceof HTMLTextAreaElement)) {
+          this.resolve(index !== undefined ? index : 0);
```
Comment (krassowski) [inline packages/apputils/src/dialog.tsx:445]: Index here is always `this._defaultButton` which is never undefined. Against, we can simplify the code:

```suggestion
          const index = this._defaultButton;
          this.resolve(index);
```

File: packages/apputils/src/dialog.tsx (hunk 4 above)
Comment (krassowski) [reply packages/apputils/src/dialog.tsx:443]: I will try that and see what tests on CI think:

```suggestion
          if (index !== -1) {
            this.resolve(index);
          }
```

**Review by krassowski — APPROVED** [review]
Thank you @Rishab87!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.3.x
