### PR TITLE
Focusin/out instead of focus/blur for notebook cells to allow events to bubble

### LINKED ISSUE #3531: Multiple active codemirror cells
Ran into a bug with codemirror focus this morning. Steps to reproduce:

1. Focus a cell (cell A).
2. Right-click on a *different* cell (cell B) to open a context menu.
3. Left click on that cell (cell B) to remove the context menu and focus it.

Both cell A and cell B will now have blinking cursors. With a bit of clicking around, I was able to get a third cell blinking as well.

cursors

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #3531. Alternative to #3537.

I still find this puzzling, but having a broader event listener for focus/blur (`focusin`/`focusout` bubbles, while `focus`/`blur` does not) allows us to catch some events in the event handlers that were not being caught before, and correctly blurs the CodeMirror instances.

@jasongrout, should we plan to have a post-beta-sit-down where we try to simplify, clean up, and write tests for cell focus and selection logic?

### CODE REVIEW

**Comment by jasongrout** [comment]
> @jasongrout, should we plan to have a post-beta-sit-down where we try to simplify, clean up, and write tests for cell focus and selection logic?

*absolutely*

**Comment by ian-r-rose** [comment]
Hold off on this for a moment...

**Comment by ian-r-rose** [comment]
Okay, this should be good to go, Travis willing.

File: packages/notebook/src/widget.ts [hunk 1]
```diff
@@ -1739,12 +1752,17 @@ class Notebook extends StaticNotebook {
     }
     this.deselectAll();
 
-    // `event.target` sometimes gives an orphaned node in Firefox 57.
+    // `event.target` sometimes gives an orphaned node in Firefox 57, which
+    // can have `null` anywhere in its parent tree. If we fail to find a
+    // cell using `event.taget`, try again using a `target reconstructed from
```
Comment (blink1073) [inline packages/notebook/src/widget.ts]: event.target* and a stray backtick  (same for the other docstring)

**Comment by blink1073** [comment]
Thanks!
