### PR TITLE
Fix inconsistent header state by specifying header node

### LINKED ISSUE #16021: Inconsistent listing header node checbox state
## Description

File Browser Dir listing header checbox is not working correctly due to click event listener added `listing.ts:2506`. So it is prevent header checkbox persist its state
image
image

## Reproduce

1. Go to 'File Browser'
2. Click on 'Listing Header Checkbox'
3. See error 'All checked but header'

## Expected behavior

It should check all

## Context

- Operating System and version: Linux Ubuntu 22.04
- Browser and version: Chrome 122
- JupyterLab version: 4.1.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by erkin98**
## References

Fixes #16021 

## Code changes

add `headerNode` param for `createCheckboxWrapperNode` options, which specify file browser dir listing checkbox header, prevent inconsistent state

## User-facing changes

[Screencast_20.03.2024_08:25:05.webm](https://github.com/jupyterlab/jupyterlab/assets/20378722/b89ffdcc-b027-4d48-b2ca-d4aa2878312e)

## Backwards-incompatible changes
 None

### CODE REVIEW

**Comment by erkin98** [comment]
please update snapshots

File: packages/filebrowser/src/listing.ts [hunk 1]
```diff
@@ -2307,7 +2307,8 @@ export namespace DirListing {
       narrow.textContent = '...';
       if (!hiddenColumns?.has('is_selected')) {
         const checkboxWrapper = this.createCheckboxWrapperNode({
-          alwaysVisible: true
+          alwaysVisible: true,
+          headerNode:true
```
Comment (krassowski) [inline packages/filebrowser/src/listing.ts:2311]: To satisfy the linter:

```suggestion
          headerNode: true
```

File: packages/filebrowser/src/listing.ts [hunk 2]
```diff
@@ -2493,6 +2494,7 @@ export namespace DirListing {
      */
     createCheckboxWrapperNode(options?: {
       alwaysVisible: boolean;
+      headerNode: boolean
```
Comment (krassowski) [inline packages/filebrowser/src/listing.ts:2497]: If we add `?` here this will allow us to backport it (as otherwise the new argument changes API in a breaking way).

```suggestion
      headerNode?: boolean
```

File: packages/filebrowser/src/listing.ts [hunk 3]
```diff
@@ -2503,9 +2505,11 @@ export namespace DirListing {
       // Prevent the user from clicking (via mouse, keyboard, or touch) the
       // checkbox since other code handles the mouse and keyboard events and
       // controls the checked state of the checkbox.
-      checkbox.addEventListener('click', event => {
-        event.preventDefault();
-      });
+      if (!options?.headerNode) {
+        checkbox.addEventListener('click', event => {
+            event.preventDefault()
```
Comment (krassowski) [inline packages/filebrowser/src/listing.ts:2510]: To satisfy the linter:

```suggestion
          event.preventDefault()
```

**Review by krassowski — COMMENTED** [review]
Thank you for the PR @erkin98! Some tiny suggestions on formatting and making the new argument optional.

Would you be interested in adding a test for selecting all checkboxes when clicking on the checkbox header? It would go somewhere here:

https://github.com/jupyterlab/jupyterlab/blob/5598b3ac105cd879c23e04ef6a8a677cf208cacc/packages/filebrowser/test/listing.spec.ts#L515

**Comment by erkin98** [comment]
> Thank you for the PR @erkin98! Some tiny suggestions on formatting and making the new argument optional.
> 
> Would you be interested in adding a test for selecting all checkboxes when clicking on the checkbox header? It would go somewhere here:
> 
> https://github.com/jupyterlab/jupyterlab/blob/5598b3ac105cd879c23e04ef6a8a677cf208cacc/packages/filebrowser/test/listing.spec.ts#L515

absolutely!

**Comment by erkin98** [comment]
> Thank you for the PR @erkin98! Some tiny suggestions on formatting and making the new argument optional.
> 
> Would you be interested in adding a test for selecting all checkboxes when clicking on the checkbox header? It would go somewhere here:
> 
> https://github.com/jupyterlab/jupyterlab/blob/5598b3ac105cd879c23e04ef6a8a677cf208cacc/packages/filebrowser/test/listing.spec.ts#L515

Hey, @krassowski , doesn't these tests cover what you've asked?
> 
> https://github.com/jupyterlab/jupyterlab/blob/5598b3ac105cd879c23e04ef6a8a677cf208cacc/packages/filebrowser/test/listing.spec.ts#L695

**Comment by krassowski** [comment]
It partially dies, but my point is that it clearly was not checking whether the header box was getting checked, right?

**Comment by erkin98** [comment]
> It partially does, but my point is that it clearly was not checking whether the header box was getting checked, right?

got u @krassowski , no worries, i'll cover

**Review by krassowski — APPROVED** [review]
Thank you @erkin98!

**Comment by erkin98** [comment]
> Thank you @erkin98!

i'll do more, no worries
