### PR TITLE
Fix restart and run all for text files with a code console.

### LINKED ISSUE #5935: Kernel->Restart Kernel and Run All doesn't work for text files
RE https://github.com/jupyterlab/jupyterlab/issues/5579, the kernel option for Restart Kernel & Run All Cells doesn't work.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #5935

### CODE REVIEW

**Comment by gnestor** [comment]
LGTM! I tried this out in master and it seems to be working without an error 🤷‍♂️ But it's definitely working in this PR. And the code is cleaned up a bit more 👍

File: packages/fileeditor-extension/src/index.ts [hunk 1]
```diff
@@ -735,24 +735,24 @@ function activate(
...
-          if (restarted) {
-            void commands.execute(CommandIDs.runAllCode);
-          }
-          return restarted;
-        });
+        const console = consoleTracker.find(
+          console => console.console.session.path === current.context.path
+        );
+        if (console) {
+          return console.session.restart().then(restarted => {
```
Comment (jasongrout) [inline packages/fileeditor-extension/src/index.ts]: Here you use `console.session`, but above you use `console.console.session`. Is there a reason for using one or the other? Can we just use one for consistency?

Comment (jasongrout) [reply packages/fileeditor-extension/src/index.ts]: in the isEnabled we use `console.session`, so perhaps that has two votes here...

Comment (jasongrout) [reply packages/fileeditor-extension/src/index.ts]: (oh, I guess it actually uses `c.console.session`, which is equivalent to `console.console.session`...)

Comment (ian-r-rose) [reply packages/fileeditor-extension/src/index.ts]: No, no reason. I think at some point we discussed removing the one from the `widget` because it was confusing, but never wound up doing that.

**Comment by jasongrout** [comment]
This works great for me, even when I follow my reproduction instructions from the issue. Thanks!

Will merge when tests pass.

**Comment by jasongrout** [comment]
There was a timeout on the windows test which seems completely unrelated.
