### PR TITLE
Fix stdin order

### LINKED ISSUE #4071: ipdb command output is all concatenated instead of being between calls
When in the interactive ipdb terminal, the output for the command is being concatenated at the top instead of in the order that the terminal should actually show it - example below, ctlr = 'CT1' and fields = ['els_notify'].  Currently looks like:

```
'CT1'
['els_notify']
ipdb> ctlr
ipdb> fields
```
Expectation is:
```
ipdb> ctlr
'CT1'
ipdb> fields
['els_notify']
```

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #4071

```python
a = input('a')
print('hi a:', a)
b = input('b')
print('hi b:', b)
c = input('c')
print('hi c:', c)
```

Before:
image

After:
image

### CODE REVIEW

File: packages/outputarea/src/widget.ts [hunk 1]
```diff
@@ -73,11 +77,6 @@ const STDIN_PROMPT_CLASS = 'jp-Stdin-prompt';
  */
 const STDIN_INPUT_CLASS = 'jp-Stdin-input';
 
-/**
- * The class name added to stdin rendered text nodes.
- */
-const STDIN_RENDERED_CLASS = 'jp-Stdin-rendered';
```
Comment (ian-r-rose) [inline packages/outputarea/src/widget.ts]: Good catch.

File: packages/outputarea/src/widget.ts [hunk 2]
```diff
@@ -301,6 +297,20 @@ export class OutputArea extends Widget {
...
+    /**
+     * Wait for the stdin to complete, add it to the model (so it persists)
+     * and remove the stdin widget.
+     */
+    input.value.then(value => {
+      // Use stdin as the stream so it does not get combined with stdout.
+      this.model.add({
+        output_type: 'stream',
+        name: 'stdin',
+        text: value
```
Comment (ian-r-rose) [inline packages/outputarea/src/widget.ts]: I think that `text: value` could use a linebreak ('value + `\n`'). Otherwise the resulting stream output can run together:
image
