### PR TITLE
Fixes contextual help attachment logic

### LINKED ISSUE #13822: Contextual help does not work on JupyterLab 4.0.0a32
## Description

Contextual help does not work on JupyterLab 4.0.0a32

image

## Reproduce

1. Open a notebook
2. Through the context menu, open the contextual help
3. Type code in a cell that call a function. You normally should see some help - but it does not work.

## Expected behavior

Contextual help works

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 4.0.0a32

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by JasonWeill**
## References

Fixes #13822.

## Code changes

Waits for the cell to be ready before attaching the contextual help handler.

## User-facing changes

Before the change, contextual help does not appear

image

After the change, contextual help appears

image

NOTE: Using the exact code as in the "before" screen shot, I still don't see the contextual help appear after this patch.

## Backwards-incompatible changes

None

### CODE REVIEW

File: packages/inspector-extension/src/index.ts [hunk 1]
```diff
@@ -270,7 +270,9 @@ const notebooks: JupyterFrontEndPlugin<void> = {
 
       // Listen for active cell changes.
       parent.content.activeCellChanged.connect((sender, cell) => {
-        handler.editor = cell && cell.editor;
+        cell?.ready.then(() => {
+          handler.editor = cell && cell.editor;
```
Comment (fcollonval) [inline packages/inspector-extension/src/index.ts:274]: I would add a check to avoid race condition in case the active cell changes quickly. And we can drop the test on `cell` as the `then` clause will not be triggered if `cell` is `null`.

```suggestion
          if (cell === parent.content.activeCell) {
            handler.editor = cell!.editor;
          }
```

**Review by fcollonval — CHANGES_REQUESTED** [review]
Thanks @JasonWeill I have one suggestion.

**Review by fcollonval — COMMENTED** [review]
Testing on Binder, there is still an issue at initial page load:

contextual-help

**Review by fcollonval — APPROVED** [review]
Thanks @JasonWeill
