### PR TITLE
fixes #6850 #6851: always use kernel display_name in statusbar

### LINKED ISSUE #6580: Navigating back to parent directory in file browser is not possible with keyboard.
From Web4All Hackathon https://github.com/diagram-codesprint/jupyterlab/issues/5
**Describe the bug**
After navigating to a sub-directory, I cannot navigate back to the parent directory using the back button or arrow keys.  This is an accessibility issue for users who only use the keyboard.

**To Reproduce**
1. Navigate to the file browser.
2. Navigate to a sub-directory.
3. There's no way to navigate back to the parent directory with keyboard.

**Expected behavior**
I should be able to use either the left arrow or backspace to navigate back up to the parent directory.

**Desktop (please complete the following information):**

- OS: macOS Mojave (10.14.4)
- Browser Chrome 4.0.3729.131
- JupyterLab 1.0.0a3

### LINKED ISSUE #6850: Kernel name changes in the statusbar
**Kernel name changes in the statusbar**
After an IPython notebook is opened, the statusbar shows the kernel name "Python3", then if I switch to another tab and switch back, the kernel name becomes "Python 3"

**Expected behavior**
The statusbar always shows the `display_name` in the metadata of the notebook, instead of 
first showing the `name`, then showing the `display_name`.

**Screenshots**
After the notebook is opened
image
After switch to another tab and switch back
image
Notebook metadata
image

### PR DESCRIPTION
**Pull request by telamonian**
Also removes capitalization change of kernel display_name.

## References

#6850 
#6851

## Code changes

Gets kernel specs as a promise, sets kernel `display_name` as part of the resolution.

## User-facing changes

The kernel name in the statusbar will always match the kernel name in the launcher (and elsewhere), and the capitalization will be the same.

## Backwards-incompatible changes

None

### CODE REVIEW

File: packages/statusbar/src/defaults/kernelStatus.tsx [hunk 1]
```diff
@@ -183,8 +181,11 @@ export namespace KernelStatus {
       const oldState = this._getAllState();
       const { newValue } = change;
       if (newValue !== null) {
-        this._kernelStatus = newValue.status;
-        this._kernelName = newValue.model.name.toLowerCase();
+        newValue.getSpec().then(spec => {
+          // sync setting of status and display name
+          this._kernelStatus = newValue.status;
+          this._kernelName = spec.display_name;
```
Comment (ian-r-rose) [inline packages/statusbar/src/defaults/kernelStatus.tsx]: We should probably call `_triggerChange` here as well, since this will be updated after the `_triggerChange` called below.  Maybe the below `_triggerChanged` should be moved inside of the `else` block as well.

Comment (ian-r-rose) [reply packages/statusbar/src/defaults/kernelStatus.tsx]: A shame that this function is async, but I see no way around it.

Comment (telamonian) [reply packages/statusbar/src/defaults/kernelStatus.tsx]: done

**Comment by telamonian** [comment]
@ian-r-rose I'm still trying to grok async/promise and the whole weird [JS event loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop). Things that I have learned since I read your comments:

1. There's no such thing as multithreading (which does seem like a massive missed oportunity).
2. The `then` clause of a function call that returns a promise gets shoved onto the message queue, then its surrounding scope immediately resumes.
3. The `then` clause is [guaranteed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#Guarantees) to be called not until *at least* the end of the surrounding scope and the stack that created it.

Is that more or less correct? 

I suppose point 2. covers the misunderstanding I had that you pointed out above. I had originally thought that execution would pause at the `then` (while, presumably, another thread ran) until the promise was resolved, then would resume *at the point* in the code where the `then` clause was created.

**Comment by ian-r-rose** [comment]
> @ian-r-rose I'm still trying to grok async/promise and the whole weird [JS event loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop). Things that I have learned since I read your comments:
> 
>     1. There's no such thing as multithreading (which does seem like a massive missed oportunity).

Right, there is no such thing as multithreading in Javascript, except in limited ways using Web Workers. I believe there are specs being worked out around webassembly, but I don't really know the latest on that.

>     2. The `then` clause of a function call that returns a promise gets shoved onto the message queue, then its surrounding scope immediately resumes.

Yes, the `.then` clause happens asynchronously, some time after it is declared in your function scope. You don't really have any guarantees as to *when* that will be.

>     3. The `then` clause is [guaranteed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#Guarantees) to be called not until _at least_ the end of the surrounding scope and the stack that created it.

Right.
> Is that more or less correct?
:+1: 

> I suppose point 2. covers the misunderstanding I had that you pointed out above. I had originally thought that execution would pause at the `then` (while, presumably, another thread ran) until the promise was resolved, then would resume _at the point_ in the code where the `then` clause was created.

Right, excecution of the single thread *does not pause* to wait for a `then` clause to execute. Same goes for an `await` statement, even though it's syntax is written to kind-of look more like synchronous code.
