### PR TITLE
Fix session context error handling

### LINKED ISSUE #8247: Session Errors Should Trigger State Change
## Description
When we hit an error while changing kernels in `SessionContext`, we should emit state changes so listeners can update their display state.

## Reproduce
1 . Add an error in `KernelManager.start_kernel()`
2. Start a Kernel
3. The error dialog is displayed, and the kernel status in the status bar and toolbar stays at "Starting"

### PR DESCRIPTION
**Pull request by blink1073**
## References
Fixes #8247

## Code changes
Internal cleanup in Session Context to handle session errors, triggering proper state changes.

## User-facing changes
During a failed kernel startup, the proper kernel state is shown in the UI.

## Backwards-incompatible changes
None.

### CODE REVIEW

File: packages/services/src/kernel/default.ts [hunk 1]
```diff
@@ -1420,7 +1420,10 @@ export class KernelConnection implements Kernel.IKernelConnection {
       .catch(error => {
         // Log any errors in handling the message, thus resetting the _msgChain
         // promise so we can process more messages.
-        console.error(error);
+        // Ignore the "Canceled" errors that are thrown during kernel dispose.
+        if (error.message.startsWith('Canceled future for ')) {
```
Comment (jasongrout) [inline packages/services/src/kernel/default.ts:1424]:
```suggestion
        if (error.message.startsWith('Cancelled future for ')) {
```

**Comment by blink1073** [comment]
@meeseeksdev please backport to 2.1.x
