### PR TITLE
Fix WebSocket `_onWSClose` handler: do not ignore close codes

### LINKED ISSUE #18189: WebSocket _onWSClose Handler Ignores Close Codes
# WebSocket _onWSClose Handler Ignores Close Codes

## Summary
The kernel WebSocket `_onWSClose` handler blindly reconnects on all close events without checking the close code, causing unnecessary reconnections on normal closures and potentially infinite loops.

## Affected Code
- Package: `@jupyterlab/services`
- File: `packages/services/src/kernel/default.ts`
- Similar issue in: `packages/services/src/terminal/default.ts`

## Bug: _onWSClose Doesn't Check Close Codes

**Location:** `_onWSClose` handler (around line 1806-1810)

```typescript
private _onWSClose = (evt: Event) => {
  if (!this.isDisposed) {
    this._reconnect();
  }
};
```

**Problem:** The handler receives a `CloseEvent` with properties (`code`, `reason`, `wasClean`) but ignores them completely. It blindly reconnects on ALL close events, even when:
- Close code 1000 (normal closure) - should NOT reconnect
- Close code 1001 (going away) - should NOT reconnect  
- Close code 1011 (server error) - might be appropriate to reconnect
- Close code 1006 (abnormal closure) - appropriate to reconnect

**Comparison:** The `earlyClose` handler (used before WebSocket opens) is smarter - it calls `getKernelModel()` to check if the kernel is actually dead before reconnecting. The `_onWSClose` handler loses this intelligence.

### User-Visible Symptoms
1. Unnecessary reconnection attempts when server gracefully closes connection
2. Wastes CPU/network resources on reconnections that shouldn't happen
3. May cause infinite reconnection loops in certain scenarios
4. Confusing console messages about connection loss when closure was intentional

### Reproduction Scenarios
- **Normal shutdown**: Server sends close code 1000 (normal closure) but client tries to reconnect
- **Server maintenance**: Server sends close code 1001 (going away) but client keeps reconnecting
- **Authentication failure**: Server closes connection, client reconnects without fixing auth issue

## Proposed Fix
```typescript
private _onWSClose = (evt: CloseEvent) => {
  if (this.isDisposed) {
    return;
  }
  
  // Check if this was a normal closure
  if (evt.code === 1000 || evt.code === 1001) {
    // Normal closure or going away - don't reconnect
    this._updateConnectionStatus('disconnected');
    return;
  }
  
  // For abnormal closures, check kernel status before reconnecting
  // (similar to earlyClose behavior)
  if (evt.code === 1006 || !evt.wasClean) {
    // Could optionally call getKernelModel() here like earlyClose does
    this._reconnect();
  }
};
```

## Additional Context

The same bugs exist in `TerminalConnection`:
- `packages/services/src/terminal/default.ts` lines 323-337 (Bug #1)
- `packages/services/src/terminal/default.ts` lines 304-321 (Bug #2)

The terminal implementation does at least log the close code:
```typescript
private _onWSClose = (event: CloseEvent) => {
  console.warn(`Terminal websocket closed: ${event.code}`);
  if (!this.isDisposed) {
    this._reconnect();
  }
};
```

## Environment
- JupyterLab version: Latest (as of Dec 2025)
## Additional Context

The same bug exists in `TerminalConnection`:
- `packages/services/src/terminal/default.ts` lines 304-321
- 1001: Going Away  
- 1006: Abnormal Closure (no close frame received)
- 1011: Server Error
- 1015: TLS Handshake Failure

## Related Code
The `earlyClose` handler shows the intended pattern - checking actual kernel state:

```typescript
const earlyClose = async (evt: Event) => {
  if (alreadyCalledOnclose) {
    return;
  }
  alreadyCalledOnclose = true;
  await getKernelModel(evt);  // Checks if kernel is actually dead
  return;
};
```

This intelligence should be preserved in `_onWSClose`.

### PR DESCRIPTION
**Pull request by Akshitguptaa**
## References

Fixes #18189

## Code changes

Modified the `_onWSClose` handler in both `packages/services/src/kernel/default.ts` and `packages/services/src/terminal/default.ts`.

Previously, these handlers blindly attempted to reconnect on *any* WebSocket close event. This caused unnecessary reconnection loops even when the connection was closed gracefully (e.g., during a manual kernel shutdown).

**Changes implemented:**
* Updated the `_onWSClose` signature to accept `CloseEvent` instead of generic `Event` to access the `.code` property.
* Added a check for standard close codes `1000` (Normal Closure) and `1001` (Going Away).
* If a normal close code is detected, the handler now correctly stops the reconnection process.

## User-facing changes

Users will no longer experience unnecessary reconnection attempts (or infinite "Reconnecting..." loops) when a kernel or terminal is gracefully shut down.

**Debugger Screenshots** 
https://postimg.cc/dhCh0FRw

## Backwards-incompatible changes

None.

### CODE REVIEW

**Review by jianyexi — APPROVED** [review]

**Comment by jianyexi** [comment]
@Akshitguptaa thanks for fixing this issue, can we merge this to unblock our component

File: packages/services/src/kernel/default.ts
Comment (krassowski) [inline packages/services/src/kernel/default.ts]:
```suggestion
    const earlyClose = async (evt: CloseEvent | ErrorEvent) => {
```

File: packages/services/src/kernel/default.ts [hunk 1]
```diff
@@ -1810,10 +1810,17 @@ export class KernelConnection implements Kernel.IKernelConnection {
   /**
    * Handle a websocket close event.
    */
-  private _onWSClose = (evt: Event) => {
-    if (!this.isDisposed) {
-      this._reconnect();
+  private _onWSClose = (evt: CloseEvent) => {
```
Comment (krassowski) [inline packages/services/src/kernel/default.ts]:
```suggestion
  private _onWSClose = (evt: CloseEvent | ErrorEvent) => {
```

File: packages/services/src/kernel/default.ts
Comment (krassowski) [inline packages/services/src/kernel/default.ts]:
```suggestion
    const getKernelModel = async (evt: CloseEvent | ErrorEvent) => {
```

File: packages/services/src/kernel/default.ts [hunk 2]
```diff
@@ -1482,7 +1482,7 @@ export class KernelConnection implements Kernel.IKernelConnection {
         if (model?.execution_state === 'dead') {
           this._updateStatus('dead');
         } else {
-          this._onWSClose(evt);
+          this._onWSClose(evt as CloseEvent);
```
Comment (krassowski) [inline packages/services/src/kernel/default.ts]: The `evt` was too generic indeed, but it can also be an `ErrorEvent`.

```suggestion
          this._onWSClose(evt);
```

**Review by krassowski — COMMENTED** [review]
A minor note on type correctness; for the operations, did you test the behavior with various kinds of kernel restarts and network issues? I know that it should work, but I the error codes sent are not always what they should be so just wanted to know how much testing this had.

**Comment by Akshitguptaa** [comment]
@krassowski  Thanks! I applied the type suggestions. 
I also verified locally that manual shutdowns, kernel restarts, and network drops all behave exactly as expected now without throwing any console errors.

**Review by jianyexi — APPROVED** [review]

**Comment by jianyexi** [comment]
@krassowski Could you please review this again? We’re hoping to merge it as soon as possible since our VSCode extension relies on it.

**Comment by jianyexi** [comment]
@krassowski Friendly ping — the author has addressed your review feedback and confirmed testing across manual shutdowns, kernel restarts, and network drops. This PR has been waiting ~3 weeks since the last update. Could you take another look when you get a chance? We have a downstream VSCode extension component blocked on this fix. Thanks!

**Comment by krassowski** [comment]
Thank you for the ping. Is it possible to replicate the error in pure JupyterLab easily? That would make testing this PR easier. Also, could you add a unit test for the proposed change?

**Comment by jianyexi** [comment]
@krassowski Thanks for the feedback! I've reproduced the issue locally and prepared unit tests.

### Reproducing in JupyterLab

I set up a mock WebSocket server that sends close code `1000` (Normal Closure) to simulate a graceful server shutdown, then connected using the same `ws` library JupyterLab uses:

```
Step 7: Mock server closing with code 1000 (Normal Closure)...
Step 8: Client received close event: code=1000, reason="Normal closure"
  [Mock Server] Connection #2   <-- unnecessary reconnection!
  [Client] Reconnected! (should NOT have happened for code 1000)

BUG CONFIRMED: Server closed with code 1000,
but the client reconnected because _onWSClose ignores close codes.
```

The mock server received **2 connections** — the original plus an unnecessary reconnection triggered by `_onWSClose` blindly calling `_reconnect()`.

### Unit test results

I wrote unit tests against the actual `KernelConnection` class using `KernelTester`.

**Before fix** (current `main` behavior — reconnects on every close):
```
Connection statuses after close(1000): [ 'connecting', 'connected' ]  ❌
Connection statuses after close(1001): [ 'connecting', 'connected' ]  ❌
Tests: 2 failed, 1 passed
```

**After fix** (normal closures correctly go to 'disconnected'):
```
Connection statuses after close(1000): [ 'disconnected' ]  ✅
Connection statuses after close(1001): [ 'disconnected' ]  ✅
√ should auto-reconnect on default websocket close (no code)
√ should not reconnect on normal WebSocket closure (code 1000)
√ should not reconnect on WebSocket going away (code 1001)
√ should reconnect on abnormal WebSocket closure (code 1011)
Tests: 4 passed
```

### Important fix: `instanceof CloseEvent` doesn't work in Node.js

During testing I found the current `evt instanceof CloseEvent` check **always returns false** in the Node.js test environment because `CloseEvent` is not a global in Node.js — the `ws` library creates its own internal `CloseEvent` class:

```
> typeof CloseEvent   // 'undefined' in Node.js v22
> e.constructor.name  // 'CloseEvent' (ws library's internal class)
> 'code' in e         // true ✅ (works everywhere)
```

I've pushed the fix and unit tests to my fork: https://github.com/jianyexi/jupyterlab/commit/5933dee87096892a73f15e5494802aa3228afbe3

Changes:
1. **`packages/services/src/kernel/default.ts`**: Replace `evt instanceof CloseEvent` with `'code' in evt`
2. **`packages/services/test/utils.ts`**: Add `closeWithCode(code, reason)` helper to `SocketTester`
3. **`packages/services/test/kernel/ws_close_codes.spec.ts`**: 4 unit tests for close code handling

@Akshitguptaa feel free to cherry-pick commit `5933dee` from https://github.com/jianyexi/jupyterlab/tree/fix/websocket-close-codes into your PR branch, or I can open a PR against your fork if that's easier.

**Comment by Akshitguptaa** [comment]
@jianyexi Thanks for putting together the unit tests! I have cherry picked the commit to this branch so we can get this merged.

@krassowski  Unit tests have now been added and verified by @jianyexi. Let us know if everything looks good to go!

**Comment by jianyexi** [comment]
@krassowski Gentle ping — the unit tests and reproduction steps you requested have been added (commit cherry-picked by @Akshitguptaa). The PR now includes 4 tests covering close codes 1000, 1001, 1011, and default close. Also fixed an \instanceof CloseEvent\ issue that didn't work in Node.js tests. Would you be able to take a look when you get a chance? Thanks!

**Review by krassowski — APPROVED** [review]
Thank you, let's try it.
