### PR TITLE
Fix race condition renaming unnamed files on first save

### LINKED ISSUE #17896: Server error when renaming untitled notebook
## Description

When creating a new `Untitled.ipynb` notebook and saving it, a dialog opens up and asks to rename it. When choosing a new name, e.g. `foo.ipynb`, the notebook is renamed but an error appears in the server.

## Reproduce

1. Launch `jupyter lab` in the terminal.
2. Create a new notebook from the launcher.
3. Save it by pressing Ctrl-s.
4. A pop-up window appears asking to rename the file, rename it to `foo.ipynb`.
5. See the error in the terminal:
<details><summary>Terminal Output</summary>
<pre>
[I 2025-09-17 17:17:11.871 ServerApp] Saving file at /Untitled.ipynb
[E 2025-09-17 17:17:11.926 ServerApp] Uncaught exception POST /api/contents/Untitled.ipynb/checkpoints?1758122231910 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='POST', uri='/api/contents/Untitled.ipynb/checkpoints?1758122231910', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_server/services/contents/handlers.py", line 358, in post
        checkpoint = await ensure_async(cm.create_checkpoint(path))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 197, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_server/services/contents/manager.py", line 1083, in create_checkpoint
        return await self.checkpoints.create_checkpoint(self, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_server/services/contents/filecheckpoints.py", line 146, in create_checkpoint
        return await self.checkpoint_model(checkpoint_id, dest_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_server/services/contents/filecheckpoints.py", line 156, in checkpoint_model
        stats = await run_sync(os.stat, os_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/anyio/to_thread.py", line 56, in run_sync
        return await get_async_backend().run_sync_in_worker_thread(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 2476, in run_sync_in_worker_thread
        return await future
               ^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 967, in run
        result = context.run(func, *args)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/david/tmp/jupyterlab/.ipynb_checkpoints/Untitled-checkpoint.ipynb'
[W 2025-09-17 17:17:11.931 ServerApp] wrote error: 'Unhandled error'
    Traceback (most recent call last):
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_server/services/contents/handlers.py", line 358, in post
        checkpoint = await ensure_async(cm.create_checkpoint(path))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 197, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_server/services/contents/manager.py", line 1083, in create_checkpoint
        return await self.checkpoints.create_checkpoint(self, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_server/services/contents/filecheckpoints.py", line 146, in create_checkpoint
        return await self.checkpoint_model(checkpoint_id, dest_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/jupyter_server/services/contents/filecheckpoints.py", line 156, in checkpoint_model
        stats = await run_sync(os.stat, os_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/anyio/to_thread.py", line 56, in run_sync
        return await get_async_backend().run_sync_in_worker_thread(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 2476, in run_sync_in_worker_thread
        return await future
               ^^^^^^^^^^^^
      File "/home/david/micromamba/envs/jupyterlab-tmp/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 967, in run
        result = context.run(func, *args)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/david/tmp/jupyterlab/.ipynb_checkpoints/Untitled-checkpoint.ipynb'
[E 2025-09-17 17:17:11.933 ServerApp] {
      "Host": "localhost:8889",
      "Accept": "*/*",
      "Referer": "http://localhost:8889/lab/tree/Untitled.ipynb",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0"
    }
[E 2025-09-17 17:17:11.933 ServerApp] 500 POST /api/contents/Untitled.ipynb/checkpoints?1758122231910 (9cd958133b2d42dba6e751887e4db360@127.0.0.1) 18.03ms referer=http://localhost:8889/lab/tree/Untitled.ipynb
</pre>
</details>

## Expected behavior

No error in the server.

## Context

- Operating System and version: Linux Ubuntu 24.04
- Browser and version: Firefox 142.0.1
- JupyterLab version: 4.4.7

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

### PR DESCRIPTION
**Pull request by shreve**
## References

Fixes #17896

## Code changes

Await `createCheckpoint()` to ensure it is completed first before performing rename when saving a file.

## User-facing changes

This does not fix a user-facing issue.

## Backwards-incompatible changes

This does not change Jupyter APIs. It technically does change the return value of the Save command callback, but I do not believe this is used.

### CODE REVIEW

File: packages/docmanager-extension/src/index.tsx [hunk 1]
```diff
@@ -1097,7 +1097,7 @@ function addCommands(
             await context.save();
 
             if (!widget?.isDisposed) {
-              return context!.createCheckpoint();
+              return await context!.createCheckpoint();
```
Comment (krassowski) [inline packages/docmanager-extension/src/index.tsx]: Should the checkpoint be created before or after rename? Since it is created after save it seems like it should be also created after rename?

Comment (krassowski) [reply packages/docmanager-extension/src/index.tsx]: Though maybe there would be some value in keeping a checkpoint early in case if the rename operation leads to an issue with the file?

Comment (shreve) [reply packages/docmanager-extension/src/index.tsx]: I think I agree more with your 2nd comment. I don't see a huge difference in that order of operations because rename includes renaming all checkpoints, but the rename of the file happens first, so if that fails or corrupts the notebook, we'd still have a backup checkpoint.

https://github.com/jupyter-server/jupyter_server/blob/987ebdd5e188cdc49751b01a0d6782d686492a53/jupyter_server/services/contents/manager.py#L491-L495

Comment (shreve) [reply packages/docmanager-extension/src/index.tsx]: Actually, the code is cleaner to pull the rename up into the try block anyway. We might as well be consistent and create the checkpoint as the final step in saving.
