### PR TITLE
Don't append content in rendered output upon rerendering.

### LINKED ISSUE #6497: when using pymc3 progress bar doesn't overwrite itself
Bug Description

In the previous version of jupyter lab the progress bar presented by the pymc3 module behaved as a normal slider. It now prints 100 times once for each percentage point. I have attached a screenshot of the current behaviour.
Screenshot_2019-06-06_19-19-18

### LINKED ISSUE #6505: Incremental text output is broken
**Describe the bug**

In JupyterLab master, if you run code that adds new text output, you get the existing output appending again and again.

**To Reproduce**

Open notebook and type the code:

Screen Shot 2019-06-07 at 9 36 41 PM

**Expected behavior**

Screen Shot 2019-06-07 at 9 39 37 PM

What is really weird is that if you open the *same* notebook in classic, with the output saved, it is fixed. Somehow, the output data is the same, it is how we display it.

### PR DESCRIPTION
**Pull request by ian-r-rose**
## References

Fixes #6497, fixes #6505.

I would consider this a bug in the rendermime library that was uncovered by some of the less-aggressive updating of outputs in #6304.

## Code changes

Empties any existing DOM node content in our existing renderers before re-rendering.

## User-facing changes

Fixes re-displaying of already displayed data.

## Backwards-incompatible changes

Possible backwards-incompatible behavior of re-rendering for subclasses of `RenderedCommon` if they were updating existing DOM nodes.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Thanks, we should check to make sure that updatable outputs continue to work without needlessly creating/destroying DOM nodes.

**Comment by ian-r-rose** [comment]
The VDOM renderer already overrides this method, which is, I believe, the only place where this comes up in core JLab. I'd be surprised if many subclasses of this which use this (incorrect, IMHO) behavior exist in the wild.

**Comment by ian-r-rose** [comment]
Yes, a quick look over our existing renderers indicates that this really only comes up with the plain text renderer.

File: packages/rendermime/src/widgets.ts [hunk 1]
```diff
@@ -63,10 +63,21 @@ export abstract class RenderedCommon extends Widget
...
+   * this method.
    */
   async renderModel(model: IRenderMime.IMimeModel): Promise<void> {
     // TODO compare model against old model for early bail?
 
+    // Empty any existing content in the node from previous renders
+    while (this.node.firstChild) {
+      this.node.removeChild(this.node.firstChild);
+    }
+
```
Comment (jasongrout) [inline packages/rendermime/src/widgets.ts]: Is it easier to just do `this.node.textContent=''`?

File: packages/rendermime/src/widgets.ts [hunk 2]
```diff
@@ -63,10 +63,21 @@ export abstract class RenderedCommon extends Widget
    * @param model - The mime model to render.
    *
    * @returns A promise which resolves when rendering is complete.
+   *
+   * #### Notes
+   * If the DOM node for this widget already has content, it is emptied
+   * before rendering. Subclasses that do not want this behavior
+   * (if, for instance, they are using DOM diffing), should override
+   * this method.
```
Comment (jasongrout) [inline packages/rendermime/src/widgets.ts]: override this method and *not* call `super.renderModel()` :).

File: packages/rendermime/src/widgets.ts (hunk 1 above)
Comment (jasongrout) [reply packages/rendermime/src/widgets.ts]: huh, https://stackoverflow.com/questions/3955229/remove-all-child-elements-of-a-dom-node-in-javascript indicates your method (or maybe equivalently `this.node.firstChild.remove()`?) may be faster, and possibly more correct if there is, for example, svg content.

Comment (ian-r-rose) [reply packages/rendermime/src/widgets.ts]: Yes, I was looking at the same post. I otherwise don't have any reason to chose one method over the other.

**Comment by ian-r-rose** [comment]
I'm trying to track down the commit that introduced this -- it doesn't look like it was #6304.

**Comment by ian-r-rose** [comment]
The culprit is #6426, which switched the text renderer to append `<pre>` nodes rather than setting the inner HTML.

I still think this is a reasonable fix, since calling `renderModel` on a mimebundle should return the same rendered content regardless of the starting node, in my opinion.

**Comment by blink1073** [comment]
Agreed, thanks!

**Comment by jasongrout** [comment]
> The culprit is #6426, which switched the text renderer to append `<pre>` nodes rather than setting the inner HTML.

Ah, my bad. Thanks for finding this!
