### PR TITLE
Rendered codemirror widget

### LINKED ISSUE #25: Make notebook have only one active editor at a time
Currently there are massive slowdowns (see #15) which could be mitigated by having only one active editor in a notebook.

- [ ] When an editor receives focus in a notebook in edit mode, a codemirror widget is constructed and displayed with the current content (or maybe a single codemirror is kept around and reused...)
- [ ] When the editor blurs, the codemirror editor is replaced with a rendered version of the editor contents.

### LINKED ISSUE #679: Allow copying of previous console inputs
This is a follow-up to #355, but to strictly track the copying of *previous inputs* in the console.  As illustrated here:

img

after selecting previous inputs, neither `Cmd-C` nor menu-based copy work.

@blink1073 [explained](https://github.com/jupyter/jupyterlab/issues/355#issuecomment-239061807) the problem.

Making this a separate issue as #355 also covered the notebook, outputs, etc.  The only thing left to try and fix is the copying of *inputs* and only in the console.

### LINKED ISSUE #816: Slow Repaint, Screen 1/3 white when scrolling a notebook
I'm experiencing extremely slow repaint on recent Jupyterlab, in particular in notebook, 

Hard to record but still: 

https://youtu.be/172Mmr8VjXE

With a casual scrolling I (especially scrolling up) I get up to 1/3 of my screen not repainted using a "standard" notebook with only ~30 cells, and only text output which is max ~10 lines. 

The repainting issue does not seem to appear in the classic notebook app, or at least much less and only for codemirror text.

Am I the only one that experiences that ? It seem to me that's is recent as I don't remember having seen that. Machine is not under normal usage load and only Notebook-Lab seem to suffer as well at full window resize when there is a notebook open, but there I guess there is a lot of relayout to do.

### LINKED ISSUE #958: Client performance when moving notebook panels
Moving panels around in my browser appears to be more performance intensive than I would have expected. I can easily push chrome to 100% usage by dragging borders between panels around. Is this expected?

I'm moving a notebook and a terminal to reproduce the issue.

Migrating here from https://github.com/phosphorjs/phosphor/issues/148

### PR DESCRIPTION
**Pull request by blink1073**
Makes the codemirror widget render itself statically when not focused.
Maintains cursor position on click behavior.

Fixes #25. Fixes #816.  Fixes #958.  Fixes #679.

single-codemirror

single-codemirror-perf

### CODE REVIEW

File: src/codemirror/widget.ts [hunk 1]
```diff
@@ -62,9 +76,34 @@ class CodeMirrorWidget extends Widget {
...
+   *
+   * #### Notes
+   * This method implements the DOM `EventListener` interface and is
+   * called in response to events on the notebook panel's node. It should
+   * not be called directly by user code.
+   */
+  handleEvent(event: Event): void {
+    switch (event.type) {
+    case 'focus':
+      this._evtFocus(event as MouseEvent);
```
Comment (jasongrout) [inline src/codemirror/widget.ts]: Should be FocusEvent (https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L2542)

File: src/codemirror/widget.ts [hunk 2]
```diff
@@ -62,9 +76,34 @@ class CodeMirrorWidget extends Widget {
...
+      break;
+    case 'blur':
+      this._evtBlur(event as MouseEvent);
```
Comment (jasongrout) [inline src/codemirror/widget.ts]: Should also be FocusEvent: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L2455

File: src/codemirror/widget.ts [hunk 3]
```diff
@@ -62,9 +76,34 @@ class CodeMirrorWidget extends Widget {
...
+    default:
+      break;
+    }
+  }
+
+  /**
    * A message handler invoked on an `'after-attach'` message.
    */
   protected onAfterAttach(msg: Message): void {
+    this.node.addEventListener('focus', this, true);
```
Comment (jasongrout) [inline src/codemirror/widget.ts]: What is the advantage of having `this` instead of calling `_evtFocus` directly? Why have an extra level of indirection?

File: src/codemirror/widget.ts [hunk 4]
```diff
@@ -102,6 +149,31 @@ class CodeMirrorWidget extends Widget {
     this._editor.focus();
   }
 
+  /**
+   * Handle `focus` events for the widget.
+   */
+  private _evtFocus(event: MouseEvent): void {
```
Comment (jasongrout) [inline src/codemirror/widget.ts]: FocusEvent

File: src/codemirror/widget.ts [hunk 5]
```diff
@@ -102,6 +149,31 @@ class CodeMirrorWidget extends Widget {
...
+    this._rendered.hide();
+    this._live.show();
+    this._editor.focus();
+  }
+
+  /**
+   * Handle `blur` events for the widget.
+   */
+  private _evtBlur(event: MouseEvent): void {
```
Comment (jasongrout) [inline src/codemirror/widget.ts]: FocusEvent

File: src/codemirror/widget.ts [hunk 6]
```diff
@@ -102,6 +149,31 @@ class CodeMirrorWidget extends Widget {
...
+    if (this.node.contains(event.relatedTarget as HTMLElement)) {
+      return;
+    }
+    this._live.hide();
+    this._rendered.show();
+    CodeMirror.runMode(this._editor.getDoc().getValue(),
```
Comment (jasongrout) [inline src/codemirror/widget.ts]: Should this be done before the node is shown? Or does it require the node to be in the DOM?

**Comment by jasongrout** [comment]
Also, if I'm reading the Codemirror code correctly, we should probably determine if we should do something intelligent with changing the cursor/selection depending on where the focusing click/touch happened: https://github.com/codemirror/CodeMirror/blob/master/src/edit/CodeMirror.js#L158

**Comment by jasongrout** [comment]
Actually, I wonder if we can re-se the exact same event (maybe with the target changed), so that our manual focus event has the same x,y coordinates, etc., using something like https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events.

**Comment by jasongrout** [comment]
Thanks for working on this! I was going to work on it soon - I was doing some work in the Console the other day and it was soooo sloooow with lots of cells!

File: src/codemirror/widget.ts (hunk 3 above)
Comment (blink1073) [inline src/codemirror/widget.ts]: This is a convention we use in all of our widgets.  It avoids having to call `.bind()`, and it gives us a central place to log events in tests.

File: src/codemirror/widget.ts (hunk 2 above)
Comment (blink1073) [inline src/codemirror/widget.ts]: Fixed both, thanks.

**Comment by blink1073** [comment]
This is working quite well now, the only thing left to do is try and trigger the cursor event on the editor after it is shown.

File: src/codemirror/widget.ts (hunk 3 above)
Comment (jasongrout) [inline src/codemirror/widget.ts]: Thanks. That explanation is worthy of an entry in https://github.com/jupyterlab/jupyterlab/blob/master/tutorial/patterns.md.

**Comment by jasongrout** [comment]
What about line numbering? Will the static versions display line numbers if they are enabled?

File: src/codemirror/widget.ts [hunk 7]
```diff
@@ -39,48 +54,171 @@ class CodeMirrorWidget extends Widget {
...
+      this._lastMouseDown = null;
+      return;
+    }
+    this._static.hide();
+    this._live.show();
+    if (this._lastMouseDown) {
+      let x = this._lastMouseDown.clientX;
+      let y = this._lastMouseDown.clientY;
+      let pos = editor.coordsChar({ left: x, top: y });
+      editor.getDoc().setCursor(pos);
```
Comment (jasongrout) [inline src/codemirror/widget.ts]: Just curious why you moved away from simulating the click event on the codemirror. For simplicity?

Comment (blink1073) [inline src/codemirror/widget.ts]: We can't use the `MouseEvent` constructor in IE and it would still require some hackery of `target`, this is straightforward and uses the existing API.

Comment (jasongrout) [inline src/codemirror/widget.ts]: > We can't use the MouseEvent constructor in IE 

Oh, good to know!

> and it would still require some hackery of target, this is straightforward and uses the existing API.

Definitely. +1.

Thanks!

**Comment by jasongrout** [comment]
Line numbers look harder: https://github.com/codemirror/CodeMirror/issues/3364

**Comment by jasongrout** [comment]
Though this indicates that we could probably do it using a callback given to runMode: http://stackoverflow.com/questions/14237361/use-codemirror-for-standalone-syntax-highlighting-with-line-numbers

**Comment by jasongrout** [comment]
That said, I'm okay with merging this without line numbers and making an issue for supporting line numbers. Going afk for a few minutes, but will finish reviewing it soon.

**Comment by blink1073** [comment]
I tried implementing the line numbers, but we'd have to completely reimplement `runMode` the way it is structured, plus we'd have to figure out how to handle the styling of those line numbers.  I'd say let's save it for future work.

**Comment by jasongrout** [comment]
A trailing newline in a cell seems to be ignored when rendering it, meaning that if your cell ends in a newline, there is a jump when focusing/unfocusing.
newline

**Comment by blink1073** [comment]
In order to fix that we'd have to write our own `runMode`.  I think we should merge this as is and I'll create the issue to track what needs to be fixed by our our renderer method.

**Comment by jasongrout** [comment]
> In order to fix that we'd have to write our own runMode. I think we should merge this as is and I'll create the issue to track what needs to be fixed by our our renderer method.

Yep, it looks like this line in CodeMirror (https://github.com/codemirror/CodeMirror/blob/96cd8885ad759350273c71235493f6b225590442/src/line/line_data.js#L92) adds a zero-width space if the line is blank, so the line isn't truly empty. Interestingly, our rendered output has a trailing newline text node, but I think the `<pre>` ignores it?

**Comment by jasongrout** [comment]
Thanks again. If you could take care of the remaining MouseEvent -> FocusEvent changes, I'll merge.

**Comment by blink1073** [comment]
Fixed, and opened #1128 to track the follow-on issues.

**Comment by jasongrout** [comment]
Awesome, thanks!
