### PR TITLE
Fix dialog interactions

### LINKED ISSUE #5: UI should indicate keyboard focus
Like for example creating a new notebook:

screen shot 2016-06-04 at 11 08 00

I have no clue if I have focus to rename, chose the kernel, if enter will cancel or validate.
And `Tab`/`shift-tab` key should cycle through these.

### LINKED ISSUE #1001: Fix keyboard interactions for dialogs
Using one of the dialogs with a keyboard is terrible right now:
- [ ] Focused items should be indicated visually - remove all the `outline:none` CSS. See https://github.com/jupyter/jupyterlab/issues/911 for suggestions on this.
- [ ] Tabbing should focus items in the dialog: right now buttons set the tabIndex to -1.
- [ ] Tabbing should not focus items outside the modal. It seems that we have several options here:
  - remove the tabIndex for every item outside the dialog while the dialog is up
  - capture tab/shift-tab on the first/last controls in the dialog and explicitly set the focus to cycle only in controls in the dialog
  - capture tab/shift-tab in the entire dialog, and handle all focus

See also https://github.com/jupyter/jupyterlab/issues/911 for other accessibility issues.

### LINKED ISSUE #1275: Restart Kernel dialog should get focus
Pressing `Esc`, `0 0` will bring up the Restart Kernel dialog but it doesn't have focus so AFAICS you have to then manually click either OK or Cancel?

It would be good if the OK button could get focus so you could restart a kernel with `Esc`, `0 0`, `Enter`.

Presumably, having already pressed `Esc`, `0 0` you're pretty sure you want to restart so it would be better to have the OK button have focus by default rather than the Cancel button.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #1275.  Fixes #1001.  Fixes #5.   <--- Wowzers!

Uses recommendations from #911, specifically https://www.smashingmagazine.com/2014/09/making-modal-windows-better-for-everyone/

- [x] Focused items are indicated visually - removes all the `outline:none` CSS. 
- [x] Tabbing focuses items in the dialog.
- [x] The dialog has an immediately focused element.
- [x] The dialog focuses the previously active element after closing.
- [x] Clicking in the overlay area dismisses the dialog.
- [x] Tabbing does not focus items outside the modal. 

This does not yet address ARIA compatibility explicitly.

cc @annabu @jasongrout 

dialog-interaction

### CODE REVIEW

**Comment by blink1073** [comment]
cc @cameronoelsen

**Comment by annabu** [comment]
Demo looks a little weird to me - which element does focusing take you to right away? It should be the text input in the middle. Maybe set an autofocus there so the flow makes more sense. 

Also, as an FYI - having placeholder text as a label is a bad practice. Users lose context when they're focused in. Adding text labels outside of the input is highly recommended.

**Comment by blink1073** [comment]
Hi @annabu, thanks for the further feedback.  I agree that in this case the input field should be the one selected.  I'll add an option to the dialog opener to override the default behavior of "focus the last button".  Let's save the wider issue of improving individual dialogs for another PR.  I opened https://github.com/jupyterlab/jupyterlab/issues/1311 to track it.

File: src/dialog/index.ts [hunk 1]
```diff
@@ -363,12 +413,27 @@ class Dialog extends Panel {
...
+    let candidateSelectors = [
+      'input',
+      'select',
+      'a[href]',
+      'textarea',
+      'button',
+      '[tabindex]',
+    ].join(',');
+
+    this._first = this.node.querySelectorAll(candidateSelectors)[0] as HTMLElement;
```
Comment (ivanov) [inline src/dialog/index.ts]: are we always guaranteed to find something that fits this criteria? In other words, might `this.node.querySelectorAll(candidateSelectors)` ever return nothing?

Comment (blink1073) [inline src/dialog/index.ts]: If there were no buttons we could hit this point.  Should we enforce that there always be one button?

Comment (ivanov) [inline src/dialog/index.ts]: I would think so. One way of doing this would be to have a `(x)` to close any modal.

**Comment by blink1073** [comment]
@annabu, here's what it looks like now when it pops up:

screen shot 2016-11-28 at 3 48 34 pm
