### PR TITLE
HoverBox refactor

### LINKED ISSUE #1766: When a completer is inside an editor that has a scrollbar, its anchor logic fails.
completer

@sccolbert suggests using`fixed` position for the completer along with listening to *all* `document` scroll events. Currently, the `HoverBox` calculation results in an `absolute` position based on only one `anchor` node's scrolls.

### PR DESCRIPTION
**Pull request by afshin**
Fixes #1766.

### CODE REVIEW

**Comment by blink1073** [comment]
I think we should move hoverbox to CodeEditor now that it depends on it for more than a simple interface that we could inline, since it can't be in core utils.

File: src/completer/widget.ts [hunk 1]
```diff
@@ -436,15 +436,18 @@ class CompleterWidget extends Widget {
       return;
     }
 
+    const editor = this._editor;
     const { coords, charWidth, lineHeight } = model.original;
+    const position = editor.getPositionAt(model.cursor.start);
+    const anchor = editor.getCoordinateForPosition(position) as ClientRect;
```
Comment (blink1073) [inline src/completer/widget.ts]: Should we just use `ClientRect` for this in the base interface?

Comment (afshin) [inline src/completer/widget.ts]: I would suggest doing that, but I wanted to discuss first and confirm it's a good idea.
