### PR TITLE
Phosphor 0.7 upgrade fixes

### LINKED ISSUE #1216: Gap Between tab and widget for text editor.
In v0.8.0-21-gb5f25b0, I see the following only for text editor:

screen shot 2016-11-04 at 10 40 54

### PR DESCRIPTION
**Pull request by afshin**
- [x] Activates widgets that are added to the main area. (Fixes https://github.com/jupyterlab/jupyterlab/issues/1217)
- [x] Fixes tab layout:

**before:**
old tab layout

**after:**
new tab layout

- [x] Fixes space above console:

**before:**
console before

**after:**
screen shot 2016-11-10 at 11 41 45 pm

- [x] Fixes #1216 space above text editor:

**before:**
text editor before

**after:**
text editor after

- [x] Fixes overlay being covered up by landing:

**before:**

**after:**

### CODE REVIEW

**Comment by sccolbert** [comment]
Should we unconditionally activate? Or break it out into a separate method, and rely on the person calling `addToMainArea` to activate? The reason I have them separate is so you can mimic the `Open link in new tab" style of interaction, where a tab is added and loaded in the background. Unconditionally activating makes that impossible.

File: src/application/shell.ts [hunk 1]
```diff
@@ -97,7 +97,16 @@ class ApplicationShell extends Widget {
 
     let topPanel = this._topPanel = new Panel();
     let hboxPanel = this._hboxPanel = new BoxPanel();
-    let dockPanel = this._dockPanel = new DockPanel();
+    let dockPanel = this._dockPanel = new DockPanel({
+      renderer: {
+        createTabBar: () => {
+          let bar = new TabBar();
+          bar.addClass('jp-mod-top');
```
Comment (sccolbert) [inline src/application/shell.ts]: Why do you need this class here? You know that `p-DockPanel-tabBar` will be at the top, so you can just use that selector.

Comment (afshin) [inline src/application/shell.ts]: There are styles that @ellisonbg wrote for `p-mod-top` and `p-mod-bottom` when they both existed and I think the idea was to have both types available in the UI, but that we were only using the top ones for now. So instead of deleting those selectors in the stylesheet, I opted to add them in our custom `shell.ts`.

File: src/application/tabs.css [hunk 2]
```diff
@@ -99,18 +99,18 @@
...
-.p-TabBar.p-mod-bottom .p-TabBar-tab {
+.p-TabBar.jp-mod-bottom .p-TabBar-tab {
   border-top: none;
 }
 
 
-.p-TabBar.p-mod-top .p-TabBar-tab:first-child,
-.p-TabBar.p-mod-bottom .p-TabBar-tab:first-child {
+.p-TabBar.jp-mod-top .p-TabBar-tab:first-child,
+.p-TabBar.jp-mod-bottom .p-TabBar-tab:first-child {
```
Comment (sccolbert) [inline src/application/tabs.css]: All of these leading selectors with `p-mod-top` can be replaced by `.p-DockPanel-tabBar`, and then you dont need the custom renderer.

File: src/application/tabs.css [hunk 3]
```diff
@@ -125,18 +125,18 @@
   color: var(--jp-ui-font-color0);
 }
 
-.p-TabBar.p-mod-top .p-TabBar-tab.p-mod-current,
-.p-TabBar.p-mod-bottom .p-TabBar-tab.p-mod-current {
+.p-TabBar.jp-mod-top .p-TabBar-tab.p-mod-current,
+.p-TabBar.jp-mod-bottom .p-TabBar-tab.p-mod-current {
```
Comment (sccolbert) [inline src/application/tabs.css]: are we actually using bottom tabs anywhere?

File: src/application/tabs.css (hunk 2 above)
Comment (afshin) [inline src/application/tabs.css]: For now, I think I should leave them to apply to all tabs unless we find that we need to be more restrictive.

**Comment by afshin** [comment]
@sccolbert For the time being, I'd rather emulate the exact behavior we had to start with, re: `activate()` of new tabs, with the understand that a more nuanced behavior is now possible.

File: src/application/tabs.css [hunk 4]
```diff
@@ -37,110 +38,53 @@
...
-
-
-.p-TabBar-tab:hover:not(.p-mod-current) {
-  background: var(--jp-layout-color1);
-}
-
-
-.p-TabBar.p-mod-top .p-TabBar-tab,
-.p-TabBar.p-mod-bottom .p-TabBar-tab {
+.p-TabBar .p-TabBar-tab {
```
Comment (sccolbert) [inline src/application/tabs.css]: the leading `.p-TabBar` is now redundant AFAICT

File: src/application/tabs.css [hunk 5]
```diff
@@ -37,110 +38,53 @@
...
+  border: var(--jp-border-width) solid var(--jp-border-color1);
   border-bottom: none;
+  position: relative;
+  overflow: visible;
 }
 
 
-.p-TabBar.p-mod-bottom .p-TabBar-tab {
-  border-top: none;
+.p-TabBar .p-TabBar-tab:hover:not(.p-mod-current) {
```
Comment (sccolbert) [inline src/application/tabs.css]: ditto

File: src/application/tabs.css (hunk 4 above)
Comment (afshin) [inline src/application/tabs.css]: Ah, I was wondering about that. I'll try without and see.

**Comment by sccolbert** [comment]
fair enough.

**Comment by jasongrout** [comment]
> Should we unconditionally activate? Or break it out into a separate method, and rely on the person calling addToMainArea to activate? The reason I have them separate is so you can mimic the `Open link in new tab" style of interaction, where a tab is added and loaded in the background. Unconditionally activating makes that impossible.

Is this the same topic as on issue https://github.com/jupyterlab/jupyterlab/pull/1233?

**Comment by sccolbert** [comment]
@jasongrout yep - same topic.

**Comment by afshin** [comment]
@sccolbert @jasongrout I changed activation semantics to require explicit activation.

**Comment by blink1073** [comment]
Looks good, thanks!
