### PR TITLE
Fix keyboard navigation (tab trap) for terminal

### LINKED ISSUE #18704: Terminal cannot be navigated via keyboard
## Description

Currently when opens a new terminal and the terminal window receives focus, it is not possible to navigate outside of the terminal using only the keyboard. The terminal is currently a tab trap.

Image

## Reproduce

1. Open a new terminal
2. Press `Esc` or `Tab` to attempt to navigate out of the terminal

## Expected behavior

- Pressing `Esc` when the terminal is in focus should move the focus to the terminal widget.
- Afterwards, pressing `Tab` should move focus to the next element and not the terminal input area.

## Context

- Operating System and version: Arch Linux
- Browser and version: Chromium v146.0.7680.153
- JupyterLab version: 4.5.5

### PR DESCRIPTION
**Pull request by IsabelParedes**
## References

- Fixes #18704
- Partially related to #17423

## Code changes

- Copy the `keydown` event logic from the Console widget
- Add event handling for `Escape` and `Enter` key presses
- Style the outline of the terminal when it is focused

### Before

- Cannot escape terminal

term_before

### After

- When the terminal text area is focused, pressing `Escape` **twice** moves focus to the terminal view port
  - this also enables scrolling the terminal output with Up/Down arrows
- When the terminal view port is focused,
  - pressing `Tab` moves focus to the next element and **not** the terminal input area
  - pressing `Enter` moves focus to the terminal input area

[term_after2.webm](https://github.com/user-attachments/assets/f4e24837-5a6e-4c69-b35a-104278f928ad)

## Backwards-incompatible changes

None

## AI usage

- YES: Some or all of the content of this PR was generated by AI.
- YES: The human author has carefully reviewed this PR and run this code (keep this PR "draft" until the answer is YES)
- AI tools and models used: GPT-5.3 Codex

### CODE REVIEW

**Comment by IsabelParedes** [comment]
Ready for a review. Thanks!

File: packages/terminal/src/widget.ts [hunk 1]
```diff
@@ -495,6 +503,49 @@ export class Terminal extends Widget implements ITerminal.ITerminal {
...
 
+  /**
+   * Handle the `keydown` event for the widget.
+   */
+  private _evtKeyDown(event: KeyboardEvent): void {
+    const xtermViewport = this._term.element?.querySelector(
+      '.xterm-viewport'
+    ) as HTMLElement | null;
+    const xtermTextarea = this._term.textarea;
+    const activeElement = document.activeElement as HTMLElement | null;
```
Comment (krassowski) [inline packages/terminal/src/widget.ts:572]: This looks fragile, I think we will need to add an integration test (galata/playwright) ensuring that this works as it may break on any xterm.js upgrade otherwise.

**Comment by krassowski** [comment]
Ok, now we can escape terminal, can we still escape `vim` though?

File: packages/terminal/src/widget.ts (hunk 1 above)
Comment (IsabelParedes) [reply packages/terminal/src/widget.ts:572]: Good point. I'll add a test.

**Comment by IsabelParedes** [comment]
> Ok, now we can escape terminal, can we still escape `vim` though?

Yes, but not with `Esc`.

Pressing `Ctrl` + `[` is supposedly the same as `Esc`. Then the user can quit vim as usual.

**Comment by IsabelParedes** [comment]
WIP: Looking into pressing `Esc` twice to escape the terminal.

File: packages/terminal/src/widget.ts [hunk 2]
```diff
@@ -34,6 +34,11 @@ const TERMINAL_CLASS = 'jp-Terminal';
  */
 const TERMINAL_BODY_CLASS = 'jp-Terminal-body';
 
+/**
+ * The delay in milliseconds to reset the escape key press.
+ */
+const ESCAPE_FOCUS_DELAY_MS = 350;
```
Comment (IsabelParedes) [inline packages/terminal/src/widget.ts:40]: I added this delay and a timer to keep track of when the Escape key is pressed twice.

Maybe this is not the best solution so I am open to other alternatives if you know of something better.

I considered registering `Esc` + `Esc` as an actual shortcut and then we wouldn't need a custom timer, but since this is very specific for `xterm` then having it as a global shortcut doesn't make much sense.

Let me know what you think :)

**Comment by IsabelParedes** [comment]
New changes:

- `Escape` needs to be pressed twice to move the focus

vim_focus

Ready for another review. Thanks!

**Review by krassowski — COMMENTED** [review]
If we decide to use double Escape, should we:
- add `aria-describedby` documenting the escape mechanism
- on pressing first Esc show "Press Esc twice to blur terminal" on statusbar (or elsewhere in the UI)?

The wording of SC here is:

> If keyboard focus can be moved to a component of the page using a [keyboard interface](https://www.w3.org/WAI/WCAG21/Understanding/no-keyboard-trap.html#dfn-keyboard-interface), then focus can be moved away from that component using only a keyboard interface, and, **if it requires more than unmodified arrow or tab keys or other standard exit methods, the user is advised of the method for moving focus away**.

**Comment by IsabelParedes** [comment]
New changes:
- Pressing `Esc` only once triggers the display of the hint in the status bar.

escape_hint

**Comment by IsabelParedes** [comment]
Ready for another review. Thanks!

File: packages/terminal-extension/src/index.ts [hunk 3]
```diff
@@ -176,6 +186,23 @@ function activate(
...
   });
+  const escapeHintStatus = statusBar
+    ? new EscapeHintStatus({
+        text: trans.__('Press Escape twice to leave terminal focus.')
+      })
+    : null;
+  let clearEscapeHintTimeout: number | null = null;
+
+  if (statusBar && escapeHintStatus) {
+    console.log('registering escape hint status item');
```
Comment (krassowski) [inline packages/terminal-extension/src/index.ts]:
```suggestion
```

**Review by krassowski — COMMENTED** [review]
Code looks good, I will ask copilot to have a look too

**Comment by IsabelParedes** [comment]
Addressed review comments and retested. Ready for another review. Thanks!

**Review by krassowski — APPROVED** [review]
This looks good to me, tested on Binder with `pyvim` (`pip install pyvim`). Thank you!
