### PR TITLE
SVG namespace. Fixes #6295.

### LINKED ISSUE #6295: _repr_svg_ broken WRT classic notebook
The `_repr_svg_` rendering seem to be incorrect:

Screen Shot 2019-05-01 at 9 20 19 PM

Works in classic notebook (taken from ipython-in-depth tutorial)

```
from IPython.display import (
    display_svg
)
class MyCircle(object):

    def __init__(self, center=(0.0,0.0), radius=1.0, color='blue'):
        self.center = center
        self.radius = radius
        self.color = color
        
    def _repr_svg_(self):
        return """<svg width="100px" height="100px">
           <circle cx="50" cy="50" r="20" stroke="black" stroke-width="1" fill="blue"/>
        </svg>"""

display_svg(MyCircle())
```

Both in latest alpha and 0.35.

### PR DESCRIPTION
**Pull request by zerline**
## References 
Fixes #6295 

## Code changes

Add _xmlns_ attribute to the _svg_ tag if it not yet present.

### CODE REVIEW

File: packages/rendermime/src/renderers.ts [hunk 1]
```diff
@@ -418,6 +418,12 @@ export function renderSVG(options: renderSVG.IRenderOptions): Promise<void> {
     return Promise.resolve(undefined);
   }
 
+  // Add missing SVG namespace (if actually missing)
+  var patt = '<svg[^>]+xmlns=[^>]+svg';
```
Comment (blink1073) [inline packages/rendermime/src/renderers.ts]: Can you please change this to `const patt`?  The lint checker is failing on this line.

**Comment by jasongrout** [comment]
Looks like the test failure is not related to this PR. Thanks!
