### PR TITLE
Debugger: Show cell execution count in breakpoint/call stack/source panel

### LINKED ISSUE #17847: Debugger: show cell index instead of tmp filenames for breakpoints/callstack/source
### Problem

When setting breakpoints for cells or looking at cell source and callstack from the debugger, it does not give an informative name. It shows a filename like `/tmp/ipykernel_1549658/3160684747.py` which is not sensible for a normal human 😄 

Image

I don't know if it's an ipykernel specific issue, I suspect fixing this would require changing both ipykernel and JupyterLab? Maybe @JohanMabille you would have some thought?

### Proposed Solution

I'd like to suggest to apply the same as what was done for IPython's tracebacks (callstacks and tracebacks are somewhat very similar, right?) and do a pass of formatting in order to make it more readable.

See how IPython shows friendly info about the trace coming from the notebook: `Cell In[2], line 1`, and `Cell In[1], line 2, in foo()`

Image

The only difference with the IPython traceback I can think of would be that during a debugger session, one cell will not be done executed yet, so it should show as `Cell In[*], line x` in the breakpoint list/stack frames etc.

### Additional context

See the implementation of IPython tracebacks: https://github.com/ipython/ipython/pull/13043 and https://github.com/ipython/ipython/pull/13088

### PR DESCRIPTION
**Pull request by arjxn-py**
## References

Shall fix #17847 

This PR improves the breakpoint list UI by displaying the execution count of the cell (e.g., 	`[12]`, `[*]`) instead of the long source path.

## User-facing changes

https://github.com/user-attachments/assets/cd73c628-afd8-40f0-b968-be22e70b93a4

### CODE REVIEW

File: packages/debugger-extension/src/index.ts [hunk 1]
```diff
@@ -616,14 +616,22 @@ const sidebar: JupyterFrontEndPlugin<IDebugger.ISidebar> = {
   id: '@jupyterlab/debugger-extension:sidebar',
   description: 'Provides the debugger sidebar.',
   provides: IDebuggerSidebar,
-  requires: [IDebugger, IEditorServices, ITranslator],
+  requires: [
+    IDebugger,
+    IEditorServices,
+    ITranslator,
+    INotebookTracker,
```
Comment (krassowski) [inline packages/debugger-extension/src/index.ts]: Requiring `INotebookTracker` would mean it would not work in an app which only offers Console, right?

Could the required information be extracted from `app.shell.currentWidget`? If not, maybe `INotebookTracker` could be optional?

Comment (arjxn-py) [reply packages/debugger-extension/src/index.ts]: Thanks for the quick review.

I'll be in favour of making `INotebookTracker` optional since I don't think the required information be extracted from `app.shell.currentWidget` as it'll only give me active widget but i also need to know when it's changed

**Comment by arjxn-py** [comment]
@krassowski This is ready for another review, I also had a question that I wanted to share the `resolveExecutionDisplay` logic so that I could reuse it - I am not sure in which file should I do it. I would be glad to know what you think. Thanks.

File: packages/debugger/src/panels/breakpoints/body.tsx [hunk 2]
```diff
@@ -85,61 +109,110 @@ const BreakpointsComponent = ({
...
   };
+
+  const execDisplay = resolveExecutionDisplay();
+
+  console.log(
+    '[BreakpointComponent] Resolved execution display for breakpoint:',
+    breakpoint,
+    '->',
+    execDisplay
+  );
```
Comment (krassowski) [inline packages/debugger/src/panels/breakpoints/body.tsx]: Can you remove this log or change it to `console.debug`?

File: packages/debugger/src/panels/breakpoints/body.tsx [hunk 3]
```diff
@@ -85,61 +109,110 @@ const BreakpointsComponent = ({
...
+      panel.content.widgets.forEach(cell => {
+        if (cell.model.type !== 'code') {
+          return;
+        }
+
+        const code = cell.model.sharedModel.getSource();
+        const codeId = config.getCodeId(code, kernelName);
+
+        if (codeId && codeId === breakpoint.source?.path) {
+          const codeCell = cell.model as ICodeCellModel;
```
Comment (krassowski) [inline packages/debugger/src/panels/breakpoints/body.tsx]: You can use [`isCodeCellModel()`](https://jupyterlab.readthedocs.io/en/stable/api/functions/cells.isCodeCellModel.html) type guard

File: packages/debugger/src/panels/breakpoints/body.tsx [hunk 4]
```diff
@@ -13,33 +15,53 @@ export class BreakpointsBody extends ReactWidget {
...
    *
    * @param model The model for the breakpoints.
+   * @param notebookTracker The notebook tracker.
+   * @param config The debugger configuration.
    */
-  constructor(model: IDebugger.Model.IBreakpoints) {
+  constructor(
+    model: IDebugger.Model.IBreakpoints,
+    config: IDebugger.IConfig,
+    notebookTracker?: INotebookTracker
```
Comment (krassowski) [inline packages/debugger/src/panels/breakpoints/body.tsx]: Instead of passing the `config` and `notebookTracker`, could we add an optional method `getDisplayName()` to `IDebugger.Model.IBreakpoints` and implement it in the `BreakpointsModel` class? This would be desirable because it avoids adding positional arguments to constructors of exported components such as `BreakpointsBody`  here (which be hard to remove/refactor later due to our API stability promise).

**Review by krassowski — COMMENTED** [review]
Looks good The `js-debugger` test failures are relevant:

```
Error: test/debugger.spec.ts(121,36): error TS2345: Argument of type '{ service: DebuggerService; callstackCommands: { continue: string; terminate: string; next: string; stepIn: string; stepOut: string; evaluate: string; registry: CommandRegistry; }; breakpointsCommands: { ...; }; editorServices: { ...; }; }' is not assignable to parameter of type 'IOptions'.
  Type '{ service: DebuggerService; callstackCommands: { continue: string; terminate: string; next: string; stepIn: string; stepOut: string; evaluate: string; registry: CommandRegistry; }; breakpointsCommands: { ...; }; editorServices: { ...; }; }' is missing the following properties from type 'IOptions': notebookTracker, config
```

Please consider my proposal to move the logic to ` IDebugger.Model.IBreakpoints` instead to refine API surface.

File: packages/debugger/src/panels/breakpoints/body.tsx [hunk 5]
```diff
@@ -85,61 +109,110 @@ const BreakpointsComponent = ({
...
-      : breakpointSourcePath;
+  const resolveExecutionDisplay = (): string | null => {
+    let display: string | null = null;
+
+    notebookTracker?.forEach(panel => {
+      const kernelName = panel.sessionContext.session?.kernel?.name ?? '';
+      panel.content.widgets.forEach(cell => {
+        if (cell.model.type !== 'code') {
+          return;
+        }
```
Comment (martinRenou) [inline packages/debugger/src/panels/breakpoints/body.tsx]: If we had a way to make those real for-loops, we wouldn't have to loop over all open notebook cells:

```suggestion
    for (const panel of notebookTracker) {
      const kernelName = panel.sessionContext.session?.kernel?.name ?? '';
      for (const cell of panel.content.widgets) {
        if (cell.model.type !== 'code') {
          continue;
        }
        
        // when you found what you're looking for, return!
        // that way you stop the loops as soon as you found it
```

I am not even sure we can do this though?

Comment (krassowski) [reply packages/debugger/src/panels/breakpoints/body.tsx]: `notebookTracker.find` will short-circuit on the first truthy result. But maybe `IWidgetTracker` should implement  iterator protocol to make it easier to work with loops.

Comment (martinRenou) [reply packages/debugger/src/panels/breakpoints/body.tsx]: > But maybe IWidgetTracker should implement iterator protocol

Reading the code, I was also thinking about this. Would that be a sensible thing to add as part of this PR? Or do you think it should be done separately?

Comment (krassowski) [reply packages/debugger/src/panels/breakpoints/body.tsx]: I would do it separately just for visibility in the changelog.

**Comment by krassowski** [comment]
The tests need fixing here:

```
Error: test/debugger.spec.ts(121,36): error TS2345: Argument of type '{ service: DebuggerService; callstackCommands: { continue: string; terminate: string; next: string; stepIn: string; stepOut: string; evaluate: string; registry: CommandRegistry; }; breakpointsCommands: { ...; }; editorServices: { ...; }; }' is not assignable to parameter of type 'IOptions'.
  Type '{ service: DebuggerService; callstackCommands: { continue: string; terminate: string; next: string; stepIn: string; stepOut: string; evaluate: string; registry: CommandRegistry; }; breakpointsCommands: { ...; }; editorServices: { ...; }; }' is missing the following properties from type 'IOptions': notebookTracker, config
```

File: packages/debugger/src/panels/breakpoints/body.tsx (hunk 4 above)
Comment (arjxn-py) [reply packages/debugger/src/panels/breakpoints/body.tsx]: Done @krassowski I have moved the logic to models in [f40204b](https://github.com/jupyterlab/jupyterlab/pull/17881/commits/f40204b16a216af705b63f8d4ed62555974d7f23)

**Comment by arjxn-py** [comment]
Hi @krassowski, I have made the suggested changes - Can you please approve the CI run?

**Comment by krassowski** [comment]
Test expectations need to be updated:

```
Error:   1) [documentation] › test/documentation/debugger.test.ts:301:7 › Debugger › Breakpoints panel ────
    Error: expect(received).toMatch(expected)

    Expected pattern: /ipykernel.*\/\d+.py/
    Received string:  "Cell [1]"
```

https://github.com/jupyterlab/jupyterlab/blob/86ca405689b984c3c1c9b6957cebbad8db312693/galata/test/documentation/debugger.test.ts#L347-L349

https://github.com/jupyterlab/jupyterlab/blob/86ca405689b984c3c1c9b6957cebbad8db312693/galata/test/documentation/debugger.test.ts#L318-L319

Once this is done I can update the snapshots.

**Comment by krassowski** [comment]
bot please update documentation snapshots

**Comment by krassowski** [comment]
<s>One more here:

https://github.com/jupyterlab/jupyterlab/blob/d056e5c79a1732ea096d66e97090ffb48e01541b/galata/test/jupyterlab/debugger.test.ts#L34-L46

of note only one of these needs to be updated because one is using a notebook and the other a script.</s>

Done in [88bde80](https://github.com/jupyterlab/jupyterlab/pull/17881/commits/88bde80ee2086488f8dacda9ff19e5ff7211a000)

**Comment by krassowski** [comment]
Hmm, could it be no snapshots cover breakpoints in notebooks?

**Comment by krassowski** [comment]
@arjxn-py the test failure appears real - there is no breakpoint icon on the gutter in the Source panel:

image

Is it because Source panel identifies the path to the source as `Cell [*]`?

I am suspicious that the changes here may have caused it:

image

Maybe there needs to be a separate attribute `label` and path kept unchanged

**Comment by arjxn-py** [comment]
Thanks @krassowski, Yes the `EditorHandler` couldn't resolve the correct place to put breakpoint in the sources gutter, I figured that it also has nothing to do with the path being shown to the user - so I didn't go in the direction to create a new attribute `label` - but I hope that the test pass now since when I tested locally the breakpoint is showing in the gutter too.

**Comment by arjxn-py** [comment]
I tried inspecting the visual regression failure but couldn't know anything substantial, as far as I saw most of the tests are timing out which I am unaware of why 😕 

However I can confirm that breakpoint is showing up in the sources gutter

**Comment by krassowski** [comment]
Yes, the test failures might be unrelated to this PR, see https://github.com/jupyterlab/jupyterlab/issues/17955. I think maybe we could pin ipykernel down to the previous version on CI for now to enable merging PRs? If you agree feel welcome to open a PR.

**Comment by arjxn-py** [comment]
Thanks for the lead, yes I agree to pin ipykernel down for the CI for now - I can open a PR soonish

File: packages/debugger/src/panels/breakpoints/model.ts [hunk 6]
```diff
@@ -81,14 +87,50 @@ export class BreakpointsModel implements IDebugger.Model.IBreakpoints {
 
   /**
    * Restore a map of breakpoints.
-   *
-   * @param breakpoints The map of breakpoints
```
Comment (krassowski) [inline packages/debugger/src/panels/breakpoints/model.ts:85]: Let's keep `@param` here

File: packages/debugger/src/panels/breakpoints/model.ts [hunk 7]
```diff
@@ -2,13 +2,19 @@
...
+import { INotebookTracker } from '@jupyterlab/notebook';
+import { isCodeCellModel } from '@jupyterlab/cells';
 
 /**
  * A model for a list of breakpoints.
  */
 export class BreakpointsModel implements IDebugger.Model.IBreakpoints {
+  constructor(
+    private config: IDebugger.IConfig,
+    private notebookTracker: INotebookTracker | null
```
Comment (krassowski) [inline packages/debugger/src/panels/breakpoints/model.ts]: The convention in this codebase is to prefix private methods with `_`


```suggestion
    private _config: IDebugger.IConfig,
    private _notebookTracker: INotebookTracker | null
```

File: packages/debugger/src/panels/breakpoints/model.ts [hunk 8]
```diff
@@ -81,14 +87,50 @@ export class BreakpointsModel implements IDebugger.Model.IBreakpoints {
...
+            } else if (cell.model.executionCount === null) {
+              display = `Cell [ ]`;
+            } else {
+              display = `Cell [${cell.model.executionCount}]`;
+            }
+          }
+        }
+      });
+    });
+
```
Comment (krassowski) [inline packages/debugger/src/panels/breakpoints/model.ts:130]: Let's avoid spamming the console:

```suggestion
```

File: packages/debugger/src/panels/breakpoints/model.ts [hunk 9]
```diff
@@ -81,14 +87,50 @@ export class BreakpointsModel implements IDebugger.Model.IBreakpoints {
...
+    let display = breakpoint.source?.path ?? '';
+
+    this.notebookTracker.forEach(panel => {
+      const kernelName = panel.sessionContext.session?.kernel?.name ?? '';
+      panel.content.widgets.forEach(cell => {
+        if (cell.model.type !== 'code') return;
+
+        const code = cell.model.sharedModel.getSource();
+        const codeId = this.config?.getCodeId(code, kernelName);
```
Comment (krassowski) [inline packages/debugger/src/panels/breakpoints/model.ts]:
```suggestion
    if (!this._notebookTracker || !this._config) {
      return breakpoint.source?.path ?? '';
    }

    let display = breakpoint.source?.path ?? '';

    this._notebookTracker.forEach(panel => {
      const kernelName = panel.sessionContext.session?.kernel?.name ?? '';
      panel.content.widgets.forEach(cell => {
        if (cell.model.type !== 'code') return;

        const code = cell.model.sharedModel.getSource();
        const codeId = this._config?.getCodeId(code, kernelName);
```

File: packages/debugger/src/panels/callstack/model.ts [hunk 10]
```diff
@@ -4,14 +4,22 @@
...
+import { isCodeCellModel } from '@jupyterlab/cells';
+import { INotebookTracker } from '@jupyterlab/notebook';
 
 /**
  * A model for a callstack.
  */
 export class CallstackModel implements IDebugger.Model.ICallstack {
+  constructor(
+    private config: IDebugger.IConfig,
+    private notebookTracker: INotebookTracker | null
```
Comment (krassowski) [inline packages/debugger/src/panels/callstack/model.ts]:
```suggestion
    private _config: IDebugger.IConfig,
    private _notebookTracker: INotebookTracker | null
```

File: packages/debugger/src/panels/callstack/model.ts [hunk 11]
```diff
@@ -63,6 +71,41 @@ export class CallstackModel implements IDebugger.Model.ICallstack {
...
+
+    let display = frame.source?.path ?? '';
+
+    this.notebookTracker.forEach(panel => {
+      const kernelName = panel.sessionContext.session?.kernel?.name ?? '';
+      panel.content.widgets.forEach(cell => {
+        if (cell.model.type !== 'code') return;
+
+        const code = cell.model.sharedModel.getSource();
+        const codeId = this.config.getCodeId(code, kernelName);
```
Comment (krassowski) [inline packages/debugger/src/panels/callstack/model.ts]:
```suggestion
    if (!this._notebookTracker || !this._config) {
      return frame.source?.path ?? '';
    }

    let display = frame.source?.path ?? '';

    this._notebookTracker.forEach(panel => {
      const kernelName = panel.sessionContext.session?.kernel?.name ?? '';
      panel.content.widgets.forEach(cell => {
        if (cell.model.type !== 'code') return;

        const code = cell.model.sharedModel.getSource();
        const codeId = this._config.getCodeId(code, kernelName);
```

File: packages/debugger/src/panels/sources/model.ts [hunk 12]
```diff
@@ -73,6 +114,8 @@ export class SourcesModel implements IDebugger.Model.ISources {
     SourcesModel,
     IDebugger.Source | null
   >(this);
+  private notebookTracker?: INotebookTracker;
+  private config?: IDebugger.IConfig;
```
Comment (krassowski) [inline packages/debugger/src/panels/sources/model.ts]:
```suggestion
  private _notebookTracker?: INotebookTracker;
  private _config?: IDebugger.IConfig;
```

File: packages/debugger/src/panels/sources/model.ts [hunk 13]
```diff
@@ -16,6 +18,8 @@ export class SourcesModel implements IDebugger.Model.ISources {
    */
   constructor(options: SourcesModel.IOptions) {
     this.currentFrameChanged = options.currentFrameChanged;
+    this.notebookTracker = options.notebookTracker ?? undefined;
+    this.config = options.config;
```
Comment (krassowski) [inline packages/debugger/src/panels/sources/model.ts]:
```suggestion
    this._notebookTracker = options.notebookTracker ?? undefined;
    this._config = options.config;
```

File: packages/debugger/src/panels/sources/model.ts [hunk 14]
```diff
@@ -64,6 +68,43 @@ export class SourcesModel implements IDebugger.Model.ISources {
...
+      return display;
+    }
+
+    this.notebookTracker.forEach(panel => {
+      const kernelName = panel.sessionContext.session?.kernel?.name ?? '';
+      panel.content.widgets.forEach(cell => {
+        if (cell.model.type !== 'code') return;
+
+        const code = cell.model.sharedModel.getSource();
+        const codeId = this.config!.getCodeId(code, kernelName);
```
Comment (krassowski) [inline packages/debugger/src/panels/sources/model.ts]:
```suggestion
    if (!this._notebookTracker || !this._config || !frame.source?.path) {
      return display;
    }

    this._notebookTracker.forEach(panel => {
      const kernelName = panel.sessionContext.session?.kernel?.name ?? '';
      panel.content.widgets.forEach(cell => {
        if (cell.model.type !== 'code') return;

        const code = cell.model.sharedModel.getSource();
        const codeId = this._config!.getCodeId(code, kernelName);
```

File: packages/debugger/src/model.ts [hunk 15]
```diff
@@ -22,12 +23,17 @@ export class DebuggerModel implements IDebugger.Model.IService {
...
+    notebookTracker: INotebookTracker | null
+  ) {
+    this.breakpoints = new BreakpointsModel(config, notebookTracker);
+    this.callstack = new CallstackModel(config, notebookTracker);
     this.variables = new VariablesModel();
     this.sources = new SourcesModel({
-      currentFrameChanged: this.callstack.currentFrameChanged
+      currentFrameChanged: this.callstack.currentFrameChanged,
+      notebookTracker: notebookTracker,
+      config: config
```
Comment (krassowski) [inline packages/debugger/src/model.ts]: Let's use IOptions object, all models are part of public API and IOptions allows us to add/deprecate/remove arguments easily between versions

```suggestion
  constructor(options: DebuggerModel.IOptions) {
    this.breakpoints = new BreakpointsModel(config, notebookTracker);
    this.callstack = new CallstackModel(config, notebookTracker);
this.variables = new VariablesModel();
this.sources = new SourcesModel({
      currentFrameChanged: this.callstack.currentFrameChanged,
      notebookTracker: options.notebookTracker,
      config: options.config
```

File: packages/debugger/src/panels/breakpoints/model.ts (hunk 8 above)
Comment (arjxn-py) [reply packages/debugger/src/panels/breakpoints/model.ts:130]: Ahh sorry, I meant to remove it before merging - i must have missed it in my revision.

**Comment by arjxn-py** [comment]
Thanks for the super nice review @krassowski, I have merged your suggestions.Sorry for the bits and pieces I left behind before your review.

File: packages/debugger/src/model.ts (hunk 15 above)
Comment (arjxn-py) [reply packages/debugger/src/model.ts]: Thanks, Done in [1992584](https://github.com/jupyterlab/jupyterlab/pull/17881/commits/1992584d9655e62504ede06f342e792a9a55c548)

File: packages/debugger/src/panels/breakpoints/model.ts [hunk 16]
```diff
@@ -2,13 +2,19 @@
...
+import { INotebookTracker } from '@jupyterlab/notebook';
+import { isCodeCellModel } from '@jupyterlab/cells';
 
 /**
  * A model for a list of breakpoints.
  */
 export class BreakpointsModel implements IDebugger.Model.IBreakpoints {
+  constructor(
+    private _config: IDebugger.IConfig,
+    private _notebookTracker: INotebookTracker | null
```
Comment (krassowski) [inline packages/debugger/src/panels/breakpoints/model.ts]: Apologies I missed this before, but can we use `IOptions` pattern for `BreakpointsModel` and `CallstackModel` too?

Comment (arjxn-py) [reply packages/debugger/src/panels/breakpoints/model.ts]: No worries, I should not have assumed I could leave the other models as it is - thanks for pointing. Done in [917d2fe](https://github.com/jupyterlab/jupyterlab/pull/17881/commits/917d2fe6f8e8b5fbf4072674b63797ccd7e06533)
