### PR TITLE
Fix visual tests, allow to disable termianal cursor blinking

### LINKED ISSUE #15510: Flaky `Linux Tests / Linux (examples, 3.11) (pull_request)` test (concurrency again?)
```
   Failed tasks:
   
   - @jupyterlab/example-federated-core:build
```

is quite a common sight. The errors appear to be:

```
> @jupyterlab/example-federated-core@3.1.0-alpha.4 clean
> rimraf static

[Error: ENOTEMPTY: directory not empty, rmdir '/home/runner/work/jupyterlab/jupyterlab/examples/federated/core_package/static'] {
  errno: -39,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: '/home/runner/work/jupyterlab/jupyterlab/examples/federated/core_package/static'
}
npm ERR! Lifecycle script `clean` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @jupyterlab/example-federated-core@3.1.0-alpha.4 
npm ERR!   at location: /home/runner/work/jupyterlab/jupyterlab/examples/federated/core_package 

> @jupyterlab/example-federated:build
```

Since the dir is randomly not empty I wonder if there is a concurrency issue.

```
> @jupyterlab/example-federated-md@3.1.0-alpha.4 clean
> rimraf ../labextensions/@jupyterlab/example-federated-md


Compilation starting…


Compilation finished

asset index_js.c1fca9fa40bd61ce1e64.js 40.1 KiB [emitted] [immutable] 1 related asset
asset remoteEntry.1729fb3087a9b82d8a96.js 30.7 KiB [emitted] [immutable] (name: @jupyterlab/example-federated-md) 1 related asset
asset mime_js.4c8744bf4c422256868a.js 3.02 KiB [emitted] [immutable] 1 related asset
asset middle_package_index_js-_59440.82a93d7e0ad3717e3a77.js 2.01 KiB [emitted] [immutable] 1 related asset
asset middle_package_index_js-_59441.8d450ce4d138189cc9a9.js 2.01 KiB [emitted] [immutable] 1 related asset
orphan modules 105 KiB (javascript) 168 bytes (consume-shared) [orphan] 23 modules
runtime modules 21.1 KiB 12 modules
built modules 504 bytes (consume-shared) 30.5 KiB (javascript) 84 bytes (share-init) [built]
  consume-shared-module modules 504 bytes
    modules by path consume shared module (default) @jupyterlab/ 336 bytes 8 modules
    modules by path consume shared module (default) @lumino/*.0 (singleton) 126 bytes 3 modules
    consume shared module (default) react@^18.2.0 (singleton) 42 bytes [built] [code generated]
  javascript modules 30.5 KiB
    modules by path ../ 24.2 KiB 6 modules
    modules by path ./*.js 6.29 KiB 2 modules
    container entry 42 bytes [built] [code generated]
  provide-module modules 84 bytes
    provide shared module (default) @jupyterlab/example-federated-md@3.1.0-alpha.4 = ./index.js 42 bytes [built] [code generated]
    provide shared module (default) @jupyterlab/example-federated-middle@3.0.3-alpha.3 = ../middle_package/index.js 42 bytes [built] [code generated]

WARNING in ./index.js
Module Warning (from ../../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/runner/work/jupyterlab/jupyterlab/examples/federated/md_package/index.js.map' file: Error: ENOENT: no such file or directory, open '/home/runner/work/jupyterlab/jupyterlab/examples/federated/md_package/index.js.map'
 @ container entry ./extension[0] ./index[0]

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

```

### PR DESCRIPTION
**Pull request by krassowski**
## References

- Fixes #15510
- A large step towards #15372: solves most flaky tests but does not address some underlying problems with galata, which are tackled in #15375

## Code changes

- add `performance.throttleNetwork` galata helper and use it to solve flakiness of completer test when trying to catch the loading indicator,
- move code for documentation tests which required serial mode from "general" to dedicated "overview" file, make them run in serial
- make customization docs tests run in serial
- mock the terminal `tree` command output for terminal snapshot
- switch to data directory in a few places to avoid `test-` directories form concurrent tests showing up in the snapshots

## User-facing changes

We always supported `cursorBlink` in API but it was not exposed. This PR adds it to user-facing schema. We need it for tests, and for accessibility, but we should remove it from backport and only release in 4.1.

Screenshot from 2023-12-13 01-11-50

## Backwards-incompatible changes

None

### CODE REVIEW

File: galata/src/helpers/performance.ts [hunk 1]
```diff
@@ -40,6 +40,22 @@ export class PerformanceHelper {
...
+    downloadThroughput: number;
+    uploadThroughput: number;
+    latency: number;
+  }): Promise<CDPSession> {
+    const cdpSession = await this.page.context().newCDPSession(this.page);
+    await cdpSession.send('Network.emulateNetworkConditions', {
+      offline: false,
+      ...config
+    });
+    return cdpSession;
```
Comment (fcollonval) [inline galata/src/helpers/performance.ts:56]: What about returning `null` in case the browser does not support CDP? As this may hit maintainer in the future if they turn on another browser.

```suggestion
  }): Promise<CDPSession | null> {
    const browserName = this.page.context().browser().browserType().name();
    if (browserName === 'chromium') {
      const cdpSession = await this.page.context().newCDPSession(this.page);
      await cdpSession.send('Network.emulateNetworkConditions', {
        offline: false,
        ...config
      });
      return cdpSession;
    }
    console.log('Browser does not support throttling network');
    return null;
```

File: galata/test/jupyterlab/completer.test.ts [hunk 2]
```diff
@@ -71,13 +71,22 @@ test.describe('Completer', () => {
...
+      });
+
       await page.keyboard.press('Tab');
       completer = page.locator(COMPLETER_SELECTOR);
       await completer.waitFor();
       await page.waitForSelector('.jp-Completer-loading-bar');
       await page.waitForSelector('.jp-Completer-loading-bar', {
         state: 'detached'
       });
+      await session.detach();
```
Comment (fcollonval) [inline galata/test/jupyterlab/completer.test.ts:89]:
```suggestion
      await session?.detach();
```

**Review by fcollonval — COMMENTED** [review]
Awesome :rocket:
Thanks @krassowski 

I have a minor suggestion. Otherwise it is good for me.

**Comment by jtpio** [comment]
Thank you @krassowski!!

File: galata/src/helpers/performance.ts (hunk 1 above)
Comment (krassowski) [reply galata/src/helpers/performance.ts:56]: Thanks!

I was quite confused by the docs saying it is chromium only but then not describing whether it will throw, or work as a no-op and forget to tackle it in the end. Your solution works great for now.

Comment (fcollonval) [reply galata/src/helpers/performance.ts]: I agree the doc is not clear about what to expect for non-chromium browser.

Thanks for applying the suggestion

**Comment by krassowski** [comment]
In one run these two failed, on re-run they passed. I think these will be addressed by https://github.com/jupyterlab/jupyterlab/pull/15375.

```
Notice:   2 failed
    [jupyterlab] › test/jupyterlab/debugger.test.ts:123:7 › Debugger Tests › Start debug session (Script) 
    [jupyterlab] › test/jupyterlab/notebook-run.test.ts:33:7 › Notebook Run › Run Notebook and capture cell outputs 
```

Good to merge?

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.0.x
