### PR TITLE
Fix running tab console error and faq command id usage 

### LINKED ISSUE #1571: Cannot read property 'children' of undefined
This line gives an error on Windows, presumably because terminals are disabled there:

https://github.com/jupyterlab/jupyterlab/blob/12d081814ba8bfaea55fc65639796d37770fc0ad/src/running/index.ts#L254

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #1571.  Also fixes a use of a command string in the FAQ plugin.

### CODE REVIEW

File: src/faq/widget.ts [hunk 1]
```diff
@@ -10,6 +10,10 @@ import {
 } from 'phosphor/lib/ui/vdom';
 
 import {
+  CommandIDs as AboutCommandIds
```
Comment (afshin) [inline src/faq/widget.ts]: Could you change this to `AboutCommandIDs` since that's what all the other command ID vars look like?

Or do you think we should change all of them from `FooIDs` to `FooIds`?
