### PR TITLE
[HTML] external links should add rel="noopener"

### LINKED ISSUE #5655: [HTML] external links should add rel="noopener" for security reason
**Describe the bug**

All external links generated from user land can be a security hole when lack `rel="noopener"`

**To Reproduce**

1. In Code Cell, input below code:

```python
from IPython.core.display import HTML
HTML('<a href="http://a-hacker.com">link</a>')
```
or below

```python
%%html
<a href="http://a-hacker.com">link</a>
```

2. Run and see output:

```html
<a href="http://a-hacker.com" target="_blank">link</a>
```

3. You see a `target="_blank"` added

This way it's violate the lighthouse rule:

https://developers.google.com/web/tools/lighthouse/audits/noopener

And maybe a security problem:

https://mathiasbynens.github.io/rel-noopener/

**Expected behavior**

If append a `target="_blank"` for link, should also add

`rel="noopener"` or  `rel="noopener noreferrer"`

**Desktop (please complete the following information):**

- JupyterLab [0.35]

**Additional context**
There're maybe same issues with `window.open` method, as stated:

https://developer.mozilla.org/en-US/docs/Web/API/Window/open#noopener

So `window.open` should pass on `"noopener"` as third argument for the same reason.

### PR DESCRIPTION
**Pull request by futurist**
Fixes #5655 

**Screenshots**
If applicable, add before and after screenshots to help show the issue being fixed, or the appearance of a new feature.

image

### CODE REVIEW

File: packages/docmanager-extension/src/index.ts [hunk 1]
```diff
@@ -473,7 +473,7 @@ function addCommands(
       }
 
       return docManager.services.contents.getDownloadUrl(path).then(url => {
-        window.open(url, '_blank');
+        window.open(url, '_blank', 'noopener');
```
Comment (afshin) [inline packages/docmanager-extension/src/index.ts]: I think what needs to happen is that the window return by your `window.open(...)` call needs to have its `opener` attribute set to `null`, because I don't think the third argument takes `noopener`.
```typescript
const opened = window.open();
opened.opener = null;
opened.location = url;
```

cf. https://mathiasbynens.github.io/rel-noopener/

Comment (futurist) [reply packages/docmanager-extension/src/index.ts]: Yes, this should be a safer way. Another thing: is `docManager.services.contents.getDownloadUrl` can be treated as safe? thus no need to consider the issue 5655?

Comment (futurist) [reply packages/docmanager-extension/src/index.ts]: Hi @afshin , for more secure, I've add the lines in your comment, see the new commit.

File: packages/docmanager-extension/src/index.ts [hunk 2]
```diff
@@ -473,7 +473,9 @@ function addCommands(
       }
 
       return docManager.services.contents.getDownloadUrl(path).then(url => {
-        window.open(url, '_blank');
+        const opened = window.open('', '_blank', 'noopener');
```
Comment (afshin) [inline packages/docmanager-extension/src/index.ts]: The second and third arguments here should be removed. `_blank` is the default second argument anyway and `noopener` is handled by setting it to `null` in your next line anyway  :)
