### PR TITLE
Prevent widget closure when Save As is cancelled

### LINKED ISSUE #17944: Pressing Cancel in `Save As` dialog when closing dirty files still closes the file's widget
## Description

When I try to close a notebook or a file with unsaved changes, I get a Dialog asking if I want to save the changes. Clicking on `Save As` opens the dialog shown below (similar to the usual `Save As` workflow).

Image

However, clicking `Cancel` here closes the document's widget even though the changes were not saved. 

## Reproduce
1. Open any read-only notebook or other document (to ensure the Close operation tries to use `Save As` and not `Save`).
2. Make some changes.
3. Try to close the document with unsaved changes.
4. Choose `Save As` in the opened Dialog.
5. Choose `Cancel` in the Save As Dialog.

## Expected behavior

Ideally, the document widget should not close unless the `Save As` or `Save` operation is successfully completed.

P.S. the relevant code can be found [here](https://github.com/jupyterlab/jupyterlab/blob/8e70045584a7c517841ab37c2782c574c4999519/packages/docmanager/src/widgetmanager.ts#L330) in `docmanager/src/widgetmanager.ts`.
If I'm not wrong, `widget.dispose()` is executed irrespective of the outcome of `context.saveAs()`.

### PR DESCRIPTION
**Pull request by Darshan808**
### Problem
When closing a dirty file and choosing "Save As", clicking Cancel in either the file picker or overwrite dialog would still close the widget and lose unsaved changes.

### Changes
- Changed `Context.saveAs()` to return `Promise<boolean>` instead of `Promise<void>`
- Returns `false` when user cancels, `true` on successful save
- Updated all tests to verify the new boolean return behavior

## Backwards-incompatible changes
- Changed `Context.saveAs()` return type from `Promise<void>` to `Promise<boolean>`

An alternative approach would have been to reject the promise on cancellation (matching the existing Doc). However, returning a boolean seems neater option. Open to feedback on this.

### CODE REVIEW

File: packages/docregistry/src/context.ts [hunk 1]
```diff
@@ -289,22 +289,23 @@ export class Context<
   /**
    * Save the document to a different path chosen by the user.
    *
-   * It will be rejected if the user abort providing a new path.
+   * Returns true if the file was successfully saved, false if the operation was cancelled
```
Comment (krassowski) [inline packages/docregistry/src/context.ts]: One concern would be whether extension/users authors have sufficient information to discriminate between:
- save not being performed because user cancelled a dialog 
- save failing because there was an issue on the server

I think with the current implementation the former case will return `false` and latter - rather than throwing - will return `true`, which is ok but not great. This is because `this.save()` and `this._finishSaveAs(newPath)` handle any exceptions themselves.

I think that at a minimum we should document the behaviour of this PR better.

```suggestion
   * Returns false if the operation was cancelled by the user.
   *
   * If operation proceeds but fails due to a content manager error,
   * the return value will still be ``true``, but the actual result can be monitored
   * by listening to the {@link saveState} signal. 
```

Comment (krassowski) [reply packages/docregistry/src/context.ts]: The alternative would be to return an object (rather than `boolean`) which would include flags like:

```ts
{
  cancelled?: boolean;
  error?: Error
}
``` 

but I am not sure if this is a good idea.

Comment (krassowski) [reply packages/docregistry/src/context.ts]: What do you think @Darshan808?

Comment (Darshan808) [reply packages/docregistry/src/context.ts]: I see what you’re saying. But in your latter suggestion, how would users know whether the save actually succeeded? If an internal error occurred during `this.save()` that didn’t get thrown, the returned object might look like:
```ts
{
  cancelled: false,
  error: undefined
}
```
which would effectively be equivalent to returning `{ success: true }`.

So I think it might be clearer to go with your initial suggestion of documenting the behavior better.

Comment (krassowski) [reply packages/docregistry/src/context.ts]: Well the idea then would be to duplicate the internal logic changing it so that it does throw an error, which I don't like very much either.
