### PR TITLE
Remove Brainf... parser

### LINKED ISSUE #14373: Brainf... is listed as syntax highlight option
## Description

Brainf... should not be listed in the text file editor syntax highlight option.

That condition is not working

https://github.com/jupyterlab/jupyterlab/blob/25658adabce206725cafe42161181ba43ae87bcd/packages/fileeditor-extension/src/index.ts#L403

this is likely a consequence of

https://github.com/jupyterlab/jupyterlab/pull/13639

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #14373

## Code changes

Remove Brainf... parser. User that wants it can create an extension.

## User-facing changes

Brainf... won't be highlighted any longer.

## Backwards-incompatible changes

None

### CODE REVIEW

File: packages/fileeditor-extension/src/index.ts [hunk 1]
```diff
@@ -405,10 +405,6 @@ function activate(
               return aName.localeCompare(bName);
             })
             .forEach(spec => {
-              // Avoid mode name with a curse word.
-              if (spec.name.indexOf('brainf') === 0) {
```
Comment (krassowski) [inline packages/fileeditor-extension/src/index.ts:409]: Is it just missing `toLowerCase`?

My slight preference would be to keep the mode, but fix this check.
