### PR TITLE
Utilize ObservableMap in models and rendermime

### LINKED ISSUE #1139: The RendererMime system should allow renderers to gracefully fail
Right now, if a renderer is tasked with rendering an output, processing stops. We should make it so that the renderer can give up, and the rendermime system will continue processing the output.

### LINKED ISSUE #1697: Access an output's `metadata` property from a rendermime renderer?
`IPython.display.JSON` accepts an `expanded` argument but AFAIK a renderer doesn't have access to the `metadata` property of an output, only the `data` property. 

I'd like to do something similar with the new `IPython.display.GeoJSON` that would [allow users to configure Leaflet from the display class](https://github.com/ipython/ipython/pull/10288).

I'd also appreciate any advice about how to approach this in the classic notebook.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #1139.  Fixes #1697.

- Renderers now take live objects that have observable `.data` and `.metadata`.
- The output model logic is moved to `rendermime/outputmodel` because an "OutputWidget" is *just* a rendermime output.
- Uses the `ObservableMap` to make an `ObservableJSON` subclass which powers the `ObservableJSONWidget` (was the `Metadata.Editor`).
- Cleans up the `OutputAreaModel`/`OutputAreaWidget` interfaces so that the execution takes place on the widget, and is the only thing that has the concept of the `stdin` handling.
- Converts the notebook and cell metadata to `ObservableJSON`.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Cool, I would love to help review this probably won't happen until Friday-ish.

File: src/rendermime/index.ts [hunk 1]
```diff
@@ -496,3 +549,58 @@ namespace RenderMime {
...
+    default:
+      break;
+    }
+    return convertBundle(bundle || {});
+  }
+
+  /**
+   * Convert a mime bundle to mime data.
+   */
+  function convertBundle(bundle: nbformat.IMimeBundle): JSONObject {
```
Comment (vidartf) [inline src/rendermime/index.ts]: This function was exposed in #1469. Is this functionality now exposed somewhere else?

Comment (blink1073) [inline src/rendermime/index.ts]: Re-exposed in 91d54fc.

**Comment by vidartf** [comment]
It is also slightly confusing that there is both `nbformat.IMimeBundle` and `RenderMime.IMimeBundle`, c.f. jupyter/nbformat#68. According to that issue, `nbformat.IMimeBundle` should probably be renamed (attachments will also be of this type?), but I don't have a constructive suggestion for what to call it.

File: src/rendermime/index.ts (hunk 1 above)
Comment (vidartf) [inline src/rendermime/index.ts]: Looking at my dependence on this function again, it might simply be enough to expose `getData()`, as this now calls `convertBundle()` before returning. My dependencies all called them in sequence.

**Comment by blink1073** [comment]
Perhaps call the one in rendermime `IObservableMimeData`?

File: src/rendermime/index.ts (hunk 1 above)
Comment (blink1073) [inline src/rendermime/index.ts]: Yeah, that was how we were using it internally as well.

**Comment by blink1073** [comment]
Or `IMimeModel`?

**Comment by blink1073** [comment]
model :allthethings:

File: src/common/observablevector.ts [hunk 2]
```diff
@@ -322,6 +330,11 @@ class ObservableVector<T> extends Vector<T> implements IObservableVector<T> {
    */
   set(index: number, value: T): void {
     let oldValues = [this.at(index)];
+    // Bail if the value does not change.
+    let itemCmp = this._itemCmp;
+    if (itemCmp(oldValues[0], value)) {
```
Comment (ian-r-rose) [inline src/common/observablevector.ts]: Should `itemCmp` also be used for `ObservableVector.remove`?

Comment (blink1073) [inline src/common/observablevector.ts]: Hmm, that's tricky.  `removal` implies strict equality in my mind.

Comment (sccolbert) [inline src/common/observablevector.ts]: I use `removeFirstOf` which is by-value and `removeFirstWhere` which by-cmp-fn in phosphor 1.0 algos

Comment (sccolbert) [inline src/common/observablevector.ts]: But in this case, I'm with `ian-r-rose` I think `itemCmp` should be used in remove, because this should work:

```
let thing1 = someThing;
let thing2 = someThingEqualToThing1;
vector.set(0, thing1);
vector.set(0, thing2);
vector.remove(thing2); // thing1 still at 0
```

Comment (sccolbert) [inline src/common/observablevector.ts]: alternatively, you could actually *do* the swap in `set`, but only emit if there is a change. That would make my example work, but I could maybe craft another that wouldn't

**Comment by gnestor** [comment]
@blink1073 You are a force of nature!

**Comment by blink1073** [comment]
Ha, I started pulling a thread and holy cow...

**Comment by blink1073** [comment]
This is done.  I would have written a shorter letter, but I did not have the time. - Blaise Pascal

**Comment by ian-r-rose** [comment]
I have discovered a truly marvelous code review, which this margin is too narrow to contain.

File: src/rendermime/rendermime.ts [hunk 3]
```diff
@@ -0,0 +1,510 @@
...
+
+  /**
+   * Add a renderer by mimeType.
+   *
+   * @param item - A renderer item.
+   *
+   * @param index - The optional order index.
+   *
+   * ####Notes
+   * Negative indices count from the end, so -1 refers to the penultimate index.
```
Comment (afshin) [inline src/rendermime/rendermime.ts]: `penultimate` is second-to-last. Is this correct?

File: src/tooltip/model.ts [hunk 4]
```diff
@@ -0,0 +1,202 @@
+// Copyright (c) Jupyter Development Team.
```
Comment (afshin) [inline src/tooltip/model.ts]: This whole file is gone now in `master`. What's the best way to keep the new pattern in master? Since there's no rebase required for this PR to go in, I'm not sure.

**Comment by afshin** [comment]
In. Sane.
