### PR TITLE
Fix enabling of commands in last cell

### LINKED ISSUE #3782: Can't create a view for cell output for the last cell in a notebook
This works for all other cells, but not the last cell.

Since I'm making videos anyway :-)  :

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #3782

### CODE REVIEW

File: packages/notebook-extension/src/index.ts [hunk 1]
```diff
@@ -708,8 +708,6 @@ function addCommands(app: JupyterLab, services: ServiceManager, tracker: Noteboo
     if (!isEnabled()) { return false; }
     const { notebook } = tracker.currentWidget;
     const index = notebook.activeCellIndex;
-    // Can't run above if we are at the top of a notebook.
-    if (index === notebook.widgets.length - 1) { return false; }
```
Comment (ian-r-rose) [inline packages/notebook-extension/src/index.ts]: This got mistakenly refactored  at some point. The intention was to have *different* logic for `Run All Above` and `Run All Below`, so that the command was only enabled if the selected cell *had* cells above or below.

**Comment by choldgraf** [comment]
thx for the fast turnaround on this :-)

**Comment by ian-r-rose** [comment]
Cf. https://github.com/jupyterlab/jupyterlab/commit/a47bb82a6cdd0ca4bb080b0d95850312a20d6f6e#diff-99391d69c6c39feb5f1b6b2dfc20ec92R702

**Comment by ian-r-rose** [comment]
Ack, I think this was the wrong fix!

**Comment by blink1073** [comment]
My mistake, I thought the issues were orthogonal. I told Darian this was good to go and we could address the above/below separately.

**Comment by ian-r-rose** [comment]
No worries, I can submit a PR for it.
