### PR TITLE
Fix for settings editor not hiding error messages once fixed by user

### LINKED ISSUE #6601: Settings editor does not clear JSON5 errors when fixed
1. Go to the Advanced settings editor, perhaps to the keyboard shortcut page
2. Type some invalid JSON5 (like `{`)
3. Notice the error message below the editor. Notice you also can't save since it is invalid JSON5
4. Fix the error (like make the text `{}`). Notice that you can now save, as it is valid JSON5, but the error message is still displayed below.

The error message should be cleared when the JSON5 validates.

### PR DESCRIPTION
**Pull request by mbektasbbg**
- adds ability to customize initial content shown in Inspector Panel component
- fixes error messages not disappearing when issues in JSON input are cleared by user

fixes #6601

### CODE REVIEW

File: packages/inspector/src/inspector.ts [hunk 1]
```diff
@@ -115,18 +128,24 @@ export class InspectorPanel extends Panel
     this.source = null;
   }
 
-  private _content: Widget = Private.defaultContent();
+  /**
+   * Generate content widget from string
+   */
+  private static generateContentWidget(message: string): Widget {
```
Comment (jasongrout) [inline packages/inspector/src/inspector.ts]: Our convention is that private methods start with underscore.

File: packages/settingeditor/src/inspector.ts [hunk 2]
```diff
@@ -76,7 +78,10 @@ class InspectorConnector extends DataConnector<
         const errors = this._validate(request.text);
 
         if (!errors) {
-          return resolve(null);
+          return resolve({
+            data: { 'text/markdown': 'No errors found' },
```
Comment (jasongrout) [inline packages/settingeditor/src/inspector.ts]: Does `text/plain` work here? Seems like it would be slightly less processing if we don't claim it is markdown.

Comment (mbektasbbg) [reply packages/settingeditor/src/inspector.ts]: @jasongrout I tried `text/plain` but it caused vertical alignment issues

File: packages/inspector/src/inspector.ts (hunk 1 above)
Comment (mbektasbbg) [reply packages/inspector/src/inspector.ts]: updated with the fix

**Comment by jasongrout** [comment]
Thanks! Looks good, and test failures seem very much unrelated.
