### PR TITLE
Token refactor/cleanup

### LINKED ISSUE #6302: Put token definitions in submodule
## Problem description:
The plugin/token system as it is used today has one annoying issue: When declaring an optional dependency, or writing a plugin that will replace another existing plugin, you normally end up importing the *entire* lib package just for the token definition. This might end up making dead code elimination / three-shaking harder, and in general just feels wrong. A better pattern might be to standardize on declaring tokens in "./tokens.ts", which should only import typings, if anything (in addition to `Token` of course).

### Advantages:
- Easy to find which tokens each package define.
- Allow to import tokens without importing package logic (helping optimizers?).
- We can still re-export tokens in index (but should we?).

### Disadvantages:
- Will either split Token definition from interface declaration OR interface declaration from implementation. This might end up being an advantage, but it might also be a disadvantage in some cases.
- Some extra churn for the refactoring.

## Initial proposal:

- For each package, move all token definitions to `./tokens.ts`.
- Also move the interface declarations for the token to `./tokens.ts`.
- Re-export tokens from `./index.ts` to avoid breaking imports outside of core, but change all cross-package imports in core to import from the sub-modules.
- Change cookiecutters / examples to import from sub-modules to establish the pattern for new packages.

### LINKED ISSUE #6333: Interfaces extending class with private props
**Describe the bug**
When working on #6302, I tried to make an extension that would replace the document manager by providing the `IDocumentManager` token. So I make a new class that implements the interface, but immediately get hit by the error:

```ts
error TS2420: Class 'MyDocumentManager' incorrectly implements interface 'IDocumentManager'.
  Types have separate declarations of a private property '_findContext'.
```

It is not an alternative to not declare it, as it will then complain about the missing private property (!).

**To Reproduce**

Any interface declaration extending a class definition with private properties will throw this error, e.g.:
```ts
interface ISecrectInterface {};

class A {
  private _method(): ISecrectInterface {
    return {};
  }
}

interface IA extends A {};

class B implements IA {
  
}

```

**Expected behavior**
Exported interfaces, and especially token interfaces, should not include any private property declaration.

### PR DESCRIPTION
**Pull request by vidartf**
## References

Fixes #6302.
Fixes #6333.

## Code changes

1. Refactored tokens to mainly reside in submodule `./tokens.ts` of the package. Some exceptions exist, e.g. when the tokens were nested in a namespace.
2. Replaced the pattern `export interface IMyToken extends DefaultImplementationClass {}` with explicit iterfaces, ref #6333. Alternatively, these could have used `... implements PublicShape<DefaultImplementationClass> {}`. 

## User-facing changes

There should be no use-facing changes.

## Backwards-incompatible changes

Some submodules were deleted as their entire content was moved into tokens.ts:
- console/lib/tracker
- filebrowser/lib/factory
- terminal/lib/constants

Some tokens were moved from one submodule to another.

Tokens should still be available in `index.ts`.

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks! It's too bad that now we are encouraging people to import from a subdirectory, `/lib/tokens`, but I don't see a way around it.

**Comment by blink1073** [comment]
@jasongrout, they can still grab the token from the top level import.

**Comment by jasongrout** [comment]
> @jasongrout, they can still grab the token from the top level import.

Right. But which do we encourage?

**Comment by blink1073** [comment]
I think it is fine to import from lib internally and in the examples.  It is bound to happen whenever you have more than one module in a package.

File: packages/fileeditor-extension/src/index.ts [hunk 1]
```diff
@@ -9,9 +9,11 @@ import {
 
 import { ICommandPalette, InstanceTracker } from '@jupyterlab/apputils';
 
-import { CodeEditor, IEditorServices } from '@jupyterlab/codeeditor';
+import { CodeEditor } from '@jupyterlab/codeeditor/lib/editor';
```
Comment (jasongrout) [inline packages/fileeditor-extension/src/index.ts]: Why are we importing this from `/lib/editor` instead of just the root package?

File: packages/notebook-extension/src/index.ts [hunk 2]
```diff
@@ -18,7 +18,9 @@ import {
 
 import { CodeCell } from '@jupyterlab/cells';
 
-import { CodeEditor, IEditorServices } from '@jupyterlab/codeeditor';
+import { CodeEditor } from '@jupyterlab/codeeditor/lib/editor';
```
Comment (jasongrout) [inline packages/notebook-extension/src/index.ts]: Same question as above - why aren't we importing this from the package root?

File: packages/fileeditor-extension/src/index.ts (hunk 1 above)
Comment (jasongrout) [reply packages/fileeditor-extension/src/index.ts]: Checking into it - nothing in `/lib/codeeditor` depends on other things in the code editor package, so it's technically valid to import from `/lib/editor`. However, is it necessary and do we want to encourage it? I think our convention is that it's okay to import from `/lib/tokens`. If we start importing from other files like this, it opens up users doing it, which then makes an implicit backwards compatibility issue if we want to refactor things.

Comment (vidartf) [reply packages/fileeditor-extension/src/index.ts]: This might have slipped in as I was testing something. The use of `defaultConfig` does introduce some cross-extension dependency, but I don't really see a clean solution for it (and this doesn't really do anything to help it).

**Comment by vidartf** [comment]
Note: I'm running some local tests to see if this PR actually helps in replacing core extensions, so please hold off on merging until I self-review as well :)

**Comment by vidartf** [comment]
> If we start importing from other files like this, it opens up users doing it, which then makes an implicit backwards compatibility issue if we want to refactor things.

Note: If we are saying users should not import from `lib`, I do not think we are really communicating this clearly. I didn't know this was policy. Maybe we could rename `lib` to `_internal`? That way we can avoid a future break like pip had, when they explicitly made all their stuff internal. We would then have to special case the tokens file somehow of course, but that is manageable and cleaner.

**Comment by saulshanabrook** [comment]
> Thanks! It's too bad that now we are encouraging people to import from a subdirectory, /lib/tokens, but I don't see a way around it.

Yeah this is a bit concerning. 

This seems like a perfect case for tree shaking. Maybe we could just get that working as we believe it should instead of introducing this change?

**Comment by blink1073** [comment]
👍 to rename to `_lib`.  Now that we emit ES6 modules, this should work for us and others: https://webpack.js.org/guides/tree-shaking/

**Comment by vidartf** [comment]
Just a FYI: I have a PR adding the `sideEffects` field to package.jsons in progress.

**Comment by vidartf** [comment]
@saulshanabrook Wrt. to tree-shaking: Many of the lab "library" packages have side effects in their "index.ts" by importing css. I think it should be an "official" way to import tokens without pulling in the CSS of the core implementation.

**Comment by blink1073** [comment]
That brings up a good point: should CSS only be imported by extensions?  It seems so.

**Comment by vidartf** [comment]
Further note on three-shaking: Unless all the dependencies of the core packages are side-effect free (and correctly mark themselves as such in package.json), we won't be able to correctly shake them.

**Comment by saulshanabrook** [comment]
Another option is to not import css but have a separate assets folder that you specify in the jupyterlab section of the package json. This would be beneficial also because it would be easier to package with roll-up or more standard es6 processing pipelines that are not webpack.

**Comment by saulshanabrook** [comment]
Another option is to not import css but have a separate assets folder that you specify in the jupyterlab section of the package json. This would be beneficial also because it would be easier to package with roll-up or more standard es6 processing pipelines that are not webpack.

**Comment by vidartf** [comment]
Another use case to keep in mind: nbdime currently imports `nbformat` from coreutils. Because of this, the nbdime bundle includes the full moment.js of 500k in its bundle. If we would ever plan to deploy nbdime to e.g. github, we would have to do a custom build config where we shim out these things.

**Comment by blink1073** [comment]
We can use `data-fns` now which is significantly smaller and supports tree-shaking

https://github.com/you-dont-need/You-Dont-Need-Momentjs#brief-comparison
https://github.com/you-dont-need/You-Dont-Need-Momentjs#time-from-now
https://github.com/you-dont-need/You-Dont-Need-Momentjs#format

**Comment by jasongrout** [comment]
@vidartf - what is the status of this now?

**Comment by blink1073** [comment]
Looks great, thanks!

**Comment by vidartf** [comment]
I think this can be reviewed based on the goals as discussed in the call yesterday. It now does what the PR said it would do, and I will follow up with other PRs for adding the `sideEffects` config, and for removing CSS imports in favor of the `style` config.

**Comment by vidartf** [comment]
Ah spotty internet gives time travel capabilities :)

**Comment by blink1073** [comment]
> 
> 
> I think this can be reviewed based on the goals as discussed in the call yesterday. It now does what the PR said it would do, and I will follow up with other PRs for adding the `sideEffects` config, and for removing CSS imports in favor of the `style` config.

I'll get right on that :wink:
