### PR TITLE
Fix native context menu blocked even when context menu is suppressed

### LINKED ISSUE #18738: Right-click copy/paste still broken in code cells even after disabling context menu
Disabling the JupyterLab context menu (added in #17352) does not restore native browser right-click in code cells. It only works in output cells.
Steps to reproduce

Open a notebook
Disable the JupyterLab context menu via command palette → unchecking "Enable Context Menu"
Select some text in a code cell
Right-click

Expected behavior
Native browser context menu appears with Copy/Paste options.
Actual behavior
Nothing happens. The selection is lost and no menu appears. Right-click works correctly in output cells but not in code cells.

Context
This makes the "Disable Context Menu" feature only half-useful. The whole point of disabling it is to get copy/paste back via right-click. Code cells are where you actually write code — that's exactly where you need it most.
The root cause appears to be CodeMirror intercepting the right-click event independently of JupyterLab's context menu layer. This needs to be fixed at the CodeMirror integration level.
Environment

JupyterLab version: 4.5.6
Jupyter Notebook version: 7.5.5
OS: Ubuntu 24.04
Browser: chrome

### PR DESCRIPTION
**Pull request by utsav-develops**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/18738

Fixes the native context menu being unconditionally blocked in `_evtContextMenuCapture` (`widget.ts`), which caused the suppress guard in `evtContextMenu` (`frontend.ts`) to never have any effect.

Builds on / completes the fix started in #17352, which missed the suppress logic in evtContextMenu.
## Code changes

In `_evtContextMenuCapture` in `widget.ts`, added a check using the same `suppressContextMenu` logic before calling `event.preventDefault()`:

```ts
if (!suppressContextMenu(event.target as HTMLElement)) {
  event.preventDefault();
}
```

This mirrors the existing helper:

```ts
export function suppressContextMenu(element: HTMLElement): boolean {
  return element.closest('[data-jp-suppress-context-menu]') !== null;
}
```

The root cause is that `_evtContextMenuCapture` runs in the capture phase, before `evtContextMenu` in `frontend.ts` ever fires. Any suppress guard placed only in `evtContextMenu` is therefore unreachable for this code path — `preventDefault()` has already been called.

## User-facing changes

The text editor will now correctly show the native browser context menu when `Enable Context Menu` is disabled. No visual changes to the default JupyterLab context menu behavior.

## Backwards-incompatible changes

None. The change only affects elements that have explicitly opted in to suppressing the JupyterLab context menu via `data-jp-suppress-context-menu`.

## AI usage
- **NO**: Some or all of the content of this PR was generated by AI.
- **YES**: The human author has carefully reviewed this PR and run this code.
- AI tools and models used: Claude Sonnet 4.6

### CODE REVIEW

File: packages/notebook/src/widget.ts
Comment (krassowski) [inline packages/notebook/src/widget.ts:1]: It looks like this needs a lint pass:

```
+ jlpm run prettier:check
Checking formatting...
[warn] packages/notebook/src/widget.ts
[warn] Code style issues found in 1 file. Run Prettier with --write to fix.
+ echo 'Please run `jlpm run prettier` locally and push changes'
Please run `jlpm run prettier` locally and push changes
```

and as Copilot says, a test would be great.

**Review by krassowski — COMMENTED** [review]
Thank you for opening the PR - I manually confirmed that this fixes the issue, but it would be great to have that tested on CI too.

**Review by utsav-develops — COMMENTED** [review]
Lint test pass

File: packages/notebook/src/widget.ts [hunk 1]
```diff
@@ -2838,7 +2838,9 @@ export class Notebook extends StaticNotebook {
     if (widget && widget.editorWidget?.node.contains(target)) {
       // Prevent CodeMirror from focusing the editor.
       // TODO: find an editor-agnostic solution.
-      event.preventDefault();
+      if (!target.closest('[data-jp-suppress-context-menu]')) {
```
Comment (krassowski) [inline packages/notebook/src/widget.ts:2841]: For posterity, this works because when context menu is disabled what really happens is `jp-suppress-context-menu` gets set on the DOM root:

https://github.com/jupyterlab/jupyterlab/blob/ae16b7a05665030d2626df0ecc632a722481a521/packages/application-extension/src/index.tsx#L1859-L1869

**Review by krassowski — APPROVED** [review]
Thank you! An integration test would ensure that this does not regress in the future, so yes, it would be ideal - you could add it in a follow-up to avoid blocking this one.
