### PR TITLE
Fix app example

### LINKED ISSUE #6413: Example tester not catching errors
**Describe the bug**
The example tester isn't catching the console errors in the app example, which is missing a required extension.

**To Reproduce**

1. Go to 'examples/app'
2. Run `jlpm build`
3. Run `python main.py`
4.  Note the console errors

**Expected behavior**
Console errors are caught in CI, example app works.

### PR DESCRIPTION
**Pull request by blink1073**
## References
Fixes #6413

## Code changes
Updates the app example and the example tester.  Also makes sure no errors are logged by the application during the run (for `browser_check` as well).

## User-facing changes
Example app works properly.

## Backwards-incompatible changes
Removes `defaultWorkspace` from `JupyterFrontEnd.IPaths` and from the server.

### CODE REVIEW

**Comment by blink1073** [comment]
Note to self:

- import `logging` in browser_check
- Fix lint:
```
/home/vsts/work/1/s/examples/app/index.js
  11:39  error  Parsing error: Unexpected token function
```
- Print the name of the app we are running and figure out why logs are out of order
- Solve the intermittent build problems like:
https://dev.azure.com/jupyterlab/jupyterlab/_build/results?buildId=1837

```
>> starting app
>> Example started!
/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/chrome-example-test.js:61
  throw up;
  ^

Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/node_modules/puppeteer/lib/Connection.js:182:12)
    at ExecutionContext.evaluateHandle (/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/node_modules/puppeteer/lib/ExecutionContext.js:106:44)
    at ExecutionContext.<anonymous> (/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/node_modules/puppeteer/lib/helper.js:111:23)
    at ExecutionContext.evaluate (/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/node_modules/puppeteer/lib/helper.js:111:23)
    at DOMWorld.evaluate (/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.content (/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/node_modules/puppeteer/lib/Page.js:612:49)
    at Page.<anonymous> (/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/node_modules/puppeteer/lib/helper.js:111:23)
    at main (/opt/hostedtoolcache/Python/3.5.5/x64/share/jupyter/lab/example_test/chrome-example-test.js:51:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[E 18:18:57.381 ExampleCheckApp] Command '['node', 'chrome-example-test.js', 'http://127.0.0.1:8888/foo/?token=15aa7b1508b988f9cd4d0b8f9f057e0615db981e57c2f5d6']' returned non-zero exit status 1
[I 18:18:57.381 ExampleCheckApp] Shutting down 0 kernels
```

**Comment by blink1073** [comment]
Todo: save an error state instead exiting on error so the chrome test can complete.

File: examples/chrome-example-test.js [hunk 1]
```diff
@@ -22,7 +22,11 @@ async function main() {
     const text = msg.text();
     console.log(`>> ${text}`);
     if (msg.type() === 'error') {
-      errored = true;
+      // On initial load, the workspace 404 is expected.
```
Comment (afshin) [inline examples/chrome-example-test.js]: This is not a very satisfying solution, so I'm not sure whether we should handle it this way.

Another option we have is actually writing a file called `fooexample-94b7.jupyterlab-workspace` which contains `{"data":{},"metadata":{"id":"/foo/example"}}` into `examples/app/build/workspaces` when `main.py` runs so that it never 404s.

Comment (blink1073) [reply examples/chrome-example-test.js]: I'm happy to have this be the place we identify known issues rather than add hacks to the examples.

Comment (afshin) [reply examples/chrome-example-test.js]: If we change the behavior of `jupyterlab_server` as per this PR, we can avoid this special-case behavior.

https://github.com/jupyterlab/jupyterlab_server/pull/64

File: packages/filebrowser-extension/src/index.ts [hunk 2]
```diff
@@ -319,8 +319,7 @@ function activateBrowser(
 
 function activateShareFile(
   app: JupyterFrontEnd,
-  factory: IFileBrowserFactory,
-  resolver: IWindowResolver
```
Comment (ian-r-rose) [inline packages/filebrowser-extension/src/index.ts]: This also needs to be removed from the plugin `requires` above.

**Comment by afshin** [comment]
> @afshin does this also address #6408?

Sadly, no. That issue remains.

I'll try with a sterile environment to see if I can reproduce your error.

File: packages/filebrowser-extension/src/index.ts (hunk 2 above)
Comment (afshin) [reply packages/filebrowser-extension/src/index.ts]: Good point.

**Comment by afshin** [comment]
@ian-r-rose We needed to update `jupyterlab_server` ... you may not have the right one, which means you may be getting a `404` for your JS bundle, hence that message.

**Comment by ian-r-rose** [comment]
Ah good point

**Comment by blink1073** [comment]
Merge time, excellent :Keanu air guitar:
