### PR TITLE
Fix directory browsing

### LINKED ISSUE #6898: #6841 broke the filebrowser w.r.t. directories
In the latest build of master, the filebrowser is broken. You can't navigate to more than one level of directory by double clicking. For example, if I try to navigate to `git/jupyterlab` by first double clicking on `git` and then double clicking on `jupyterlab`, I get this error message:

image

Reverting this line from #6841 to `item.name` fixes it:

https://github.com/jupyterlab/jupyterlab/blob/cf8a33f597f258473c2ef541d0f9b8e608d5a4cd/packages/filebrowser/src/listing.ts#L925

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Fixes #6898
Fixes an error with #6841

## Code changes

filebrowser model cd handles relative paths, and item.path never starts with a root /, so add one.

## User-facing changes

This lets the filebrowser browser more than one directory level deep.

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @telamonian

File: packages/filebrowser/src/listing.ts [hunk 1]
```diff
@@ -922,7 +922,7 @@ export class DirListing extends Widget {
     this._onItemOpened.emit(item);
     if (item.type === 'directory') {
       this._model
-        .cd(item.path)
+        .cd(`/${item.path}`)
```
Comment (telamonian) [inline packages/filebrowser/src/listing.ts]: Does it make sense to ensure the leading slash here?

```typescript
.cd('/' + PathExt.normalize(item.path))
```

Comment (jasongrout) [reply packages/filebrowser/src/listing.ts]: `item.path` documentation says it never has a leading slash: https://github.com/jupyterlab/jupyterlab/blob/e7c8c9ac5eb6a2c22cf5b3070a2926e8b0f44b62/packages/services/src/contents/index.ts#L50

**Comment by telamonian** [comment]
The other thing to consider is if we should add a leading slash in the `'filebrowser:open'` command as well:

https://github.com/jupyterlab/jupyterlab/blob/cf8a33f597f258473c2ef541d0f9b8e608d5a4cd/packages/filebrowser-extension/src/index.ts#L531-L536

**Comment by jasongrout** [comment]
> The other thing to consider is if we should add a leading slash in the `'filebrowser:open'` command as well:

Yes. Done.

**Comment by telamonian** [comment]
Looks good to me!

**Comment by jasongrout** [comment]
Feel free to merge when tests pass :)

**Comment by telamonian** [comment]
Sadly, I cannot. Somehow after the changes made during the meeting yesterday removed my write access. I already let Steve know.

Thanks for coming through with the simple solution. I had spent the whole morning trying to get a custom drive to work with paths that had query parameters in them (eg `test/test.hdf5?uri=/group00/group01`), and was definitely overthinking this fix.

**Comment by jasongrout** [comment]
> Sadly, I cannot. Somehow after the changes made during the meeting yesterday removed my write access. I already let Steve know.

I just restored your access. Sorry for the mixup.

**Comment by telamonian** [comment]
> I just restored your access. Sorry for the mixup.

Thanks!

Well, that's extra weird. I'm still not authorized to do the merge. I am still a member of `jupyterlab/committers`, and the [group's repo page](https://github.com/orgs/jupyterlab/teams/committers/repositories) does say that I have write access.

Was there perhaps a change made in this repo's [branch restrictions](https://help.github.com/en/articles/about-branch-restrictions)? I know they're [used in some of the other jupyterlab repos](https://github.com/jupyterlab/jupyterlab_app/settings/branch_protection_rules/906301).

**Comment by jasongrout** [comment]
> Was there perhaps a change made in this repo's [branch restrictions](https://help.github.com/en/articles/about-branch-restrictions)? I know they're [used in some of the other jupyterlab repos](https://github.com/jupyterlab/jupyterlab_app/settings/branch_protection_rules/906301).

There was. I think we fixed that now too.
