### PR TITLE
Fix flaky toolbar item placement in popup

### LINKED ISSUE #18459: `Item added from extension should be correctly placed in popup toolbar` is flaky
## Description

The expectation is that `new item 1` will be placed in the popup but sometimes it gets placed in the main toolbar

## Reproduce

```
Error: expect(locator).toHaveText(expected) failed

Locator: locator('body > .jp-Toolbar-responsive-popup:visible').locator('.jp-Toolbar-item:visible').nth(1)
Timeout: 5000ms
- Expected  -  1
+ Received  + 21

- new item 1
+ Python 3 (ipykernel)
+     
+         
+     
+         
+             
+         
+     
+
+         
+             
+         
+         
+     
+         
+             
+         
+     
+
+     
+

Call log:
  - Expect "toHaveText" with timeout 5000ms
  - waiting for locator('body > .jp-Toolbar-responsive-popup:visible').locator('.jp-Toolbar-item:visible').nth(1)
    9 × locator resolved to <div data-no-focus-on-click="true" data-jp-item-name="kernelName" class="lm-Widget jp-KernelName jp-Toolbar-item">…</div>
      - unexpected value "Python 3 (ipykernel)
    
        
    
        
            
        
    

        
            
        
        
    
        
            
        
    

    
"


  328 |     const popupToolbarItems = popupToolbar.locator('.jp-Toolbar-item:visible');
  329 |
> 330 |     await expect(popupToolbarItems.nth(1)).toHaveText('new item 1');
      |                                            ^
  331 |   });
  332 |
  333 |   test('Item should be correctly removed on ignoring', async ({ page }) => {
    at /home/runner/work/jupyterlab/jupyterlab/galata/test/jupyterlab/notebook-toolbar.test.ts:330:44
```

https://github.com/user-attachments/assets/a1c0b608-1692-42a1-b311-f16408286918

## Expected behavior

Behaviour is fixed or test is adjusted.

## Context

- Browser and version: Chromium
- JupyterLab version: 4.6.0a2

### PR DESCRIPTION
**Pull request by filipeoliveira05**
## References

- Fixes #18459
- The test "Item added from extension should be correctly placed in popup toolbar" is flaky because it clicks the popup opener before the async resizer has moved the new item from the main toolbar to the popup.

## Code changes

- Added an `await expect(...).toHaveCount(0)` assertion before clicking the popup opener, which waits for the reactive toolbar resizer to move the new item out of the main toolbar before opening the popup.
- This replaces the previous approach where the popup was opened immediately after inserting the item, creating a race condition with the async resizer.

## User-facing changes

No user-facing changes. This is a test-only fix.

## Backwards-incompatible changes

No backwards-incompatible changes.

## AI usage

- YES: Some of the content of this PR was generated by AI.
- YES: The human author has carefully reviewed this PR and run this code.
- AI tools and models used: GitHub Copilot (Claude)

### CODE REVIEW

**Review by krassowski — COMMENTED** [review]
Thank you for working on it! This could be the right direction, but it looks like there is more work needed. I run the test 20 times before and after with:

```
jlpm run test --project jupyterlab --grep "Item added from extension should be correctly placed in popup toolbar" --repeat-each 20
```

Before it failed 7 times:

```
  7 failed
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
  13 passed (22.3s)
```

After it failed 10 times:

```
  10 failed
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
    [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 
  10 passed (23.6s)
```

All 10 failures were on the added line:

```
  1) [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar 

    Error: expect(locator).toHaveCount(expected) failed

    Locator:  locator('.jp-NotebookPanel-toolbar').locator('.jp-Toolbar-item:visible').filter({ hasText: 'new item 1' })
    Expected: 0
    Received: 1
    Timeout:  5000ms

    Call log:
      - Expect "toHaveCount" with timeout 5000ms
      - waiting for locator('.jp-NotebookPanel-toolbar').locator('.jp-Toolbar-item:visible').filter({ hasText: 'new item 1' })
        9 × locator resolved to 1 element
          - unexpected value "1"


      370 |     await expect(
      371 |       toolbar.locator('.jp-Toolbar-item:visible', { hasText: 'new item 1' })
    > 372 |     ).toHaveCount(0);
          |       ^
      373 |
      374 |     await toolbar.locator('.jp-Toolbar-responsive-opener').click();
      375 |
```

Looking at the video:

https://github.com/user-attachments/assets/16c1ddaa-c7cf-43d3-b052-131601e6e984

...it could be an implementation rather than a test issue.

CC @brichet who added this test case in https://github.com/jupyterlab/jupyterlab/pull/15843 in case if you have any thoughts.

**Comment by filipeoliveira05** [comment]
Got it. Will make the changes

**Comment by brichet** [comment]
According the screencast in Mike's comment, I agree that there might be an issue with the implementation rather than the test.

That said, I was not able to reproduce the flakiness. Running locally the _Item added from extension should be correctly placed in popup toolbar_ test 20 times is successful, on chrome and firefox.

_tested before https://github.com/jupyterlab/jupyterlab/pull/18618/commits/47b3c926157b11d60025e3d692c7db7c2b1dfaa1_

File: packages/ui-components/src/components/toolbar.tsx [hunk 1]
```diff
@@ -512,9 +512,11 @@ export class ReactiveToolbar extends Toolbar<Widget> {
       this._widgetPositions.set(name, index);
 
       // Invokes resizing to ensure correct display of items after an addition, only
-      // if the toolbar is rendered.
+      // if the toolbar is rendered. Call the resizer twice (callTwice = true) so that
+      // widgets that have not yet been painted (clientWidth === 0) get a chance to be
+      // rendered before the second pass recalculates the layout.
       if (this.isVisible) {
-        void this._resizer.invoke();
+        void this._resizer.invoke(true);
```
Comment (brichet) [inline packages/ui-components/src/components/toolbar.tsx:519]: IIRC `callTwice` should only be necessary on first rendering, but it is probably good to use it here too, widgets are mostly added during first render I guess.

Another option that I can think of is to ensure invoking the resizer twice on after show. I wonder if, in a race condition, the thottler could be set before `onAfterShow` call, which would result to the `callTwice` argument not taken into account.

```ts
  onAfterShow(msg: Message): void {
    void this._resizer.stop().then(() => void this._resizer.invoke(true));
  }
```

Comment (filipeoliveira05) [reply packages/ui-components/src/components/toolbar.tsx:519]: Thanks for the feedback, makes sense. I’ll add a small follow-up commit to make `onAfterShow` robust against a pending throttled call.

**Comment by krassowski** [comment]
Hmm locally I still get 10 passing and 10 failing on:

```
      370 |     await expect(
      371 |       toolbar.locator('.jp-Toolbar-item:visible', { hasText: 'new item 1' })
    > 372 |     ).toHaveCount(0);
```

**Comment by filipeoliveira05** [comment]
> Hmm locally I still get 10 passing and 10 failing on:
> 
> ```
>       370 |     await expect(
>       371 |       toolbar.locator('.jp-Toolbar-item:visible', { hasText: 'new item 1' })
>     > 372 |     ).toHaveCount(0);
> ```

The `toHaveCount(0)` assertion you're hitting on line 372 was removed in my second commit (47b3c92). The current HEAD of this branch no longer has that line (the test is back to the original form). Could you re-test on the latest commit (bbca980)? It includes both changes:

- `insertItem`: `this._resizer.invoke(true)` (double-pass resize on insert)
- `onAfterShow`: `this._resizer.stop().then(() => this._resizer.invoke(true))` (flush pending throttled call before first-render resize)

The test itself is unchanged from upstream, only the implementation in `toolbar.tsx` is modified.

**Review by krassowski — APPROVED** [review]
Right, sorry I should have double checked that I pulled the latest changes. It indeed passes 20/20 times now:

<details>

```
$ jlpm run test --project jupyterlab --grep "Item added from extension should be correctly placed in popup toolbar" --repeat-each 20

Running 20 tests using 14 workers

  ✓   1 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.9s)
  ✓   2 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.7s)
  ✓   3 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.7s)
  ✓   4 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (14.1s)
  ✓   5 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.9s)
  ✓   6 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (14.0s)
  ✓   7 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.7s)
  ✓   8 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.9s)
  ✓   9 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.8s)
  ✓  10 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.8s)
  ✓  11 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.8s)
  ✓  12 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.8s)
  ✓  13 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.7s)
  ✓  14 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (13.7s)
  ✓  15 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (7.1s)
  ✓  16 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (4.4s)
  ✓  17 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (5.1s)
  ✓  18 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (5.2s)
  ✓  19 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (5.3s)
  ✓  20 [jupyterlab] › test/jupyterlab/notebook-toolbar.test.ts:355:7 › Reactive toolbar › Item added from extension should be correctly placed in popup toolbar (5.4s)

  20 passed (24.5s)
```

</details>

Thank you @filipeoliveira05!

**Comment by filipeoliveira05** [comment]
Hi @krassowski, thank you for the review and the approval!

@brichet, please let me know if you have any further concerns or if there's anything else I should adjust regarding the implications for your previous work.

Also, I currently have 3 commits in this PR. Would you like me to squash them, or will you handle that?

Thanks!
