### PR TITLE
Markdown code block fixes

### LINKED ISSUE #2271: Edge cases to improve for markdown code block detection
We have just merged #2270 which adds markdown block detection. There are a few edge cases we don't handle quite right. 

First, if there are multiple single back-tick blocks in a line we get errors.

screen shot 2017-05-24 at 8 54 03 pm

My recommendation for that is that we don't autodetect these blocks unless the cursor in within one of the blocks, rather than on the line.

Second, for a block, we don't strip the leading and trailing newline:

screen shot 2017-05-24 at 8 54 35 pm

We should remove these extra newlines.

### PR DESCRIPTION
**Pull request by ellisonbg**
Fixes #2271

### CODE REVIEW

File: packages/fileeditor-extension/src/index.ts [hunk 1]
```diff
@@ -198,19 +198,20 @@ function activate(app: JupyterLab, registry: IDocumentRegistry, restorer: ILayou
...
         return;
       }
 
       let code = '';
-
       const editor = widget.editor;
       const path = widget.context.path;
       const extension = PathExt.extname(path);
       const selection = editor.getSelection();
       const { start, end } = selection;
```
Comment (blink1073) [inline packages/fileeditor-extension/src/index.ts]: Debug statement.

Comment (ellisonbg) [inline packages/fileeditor-extension/src/index.ts]: pushed fix

**Comment by ellisonbg** [comment]
Tests passing, review comments addressed.
