### PR TITLE
Fix highlighting search on output cells and previous match skips 

### LINKED ISSUE #17796: Previous Match Skips Editor When Outputs Are Included - Search & Replace
### Issue - 1:
- The current search match in cell outputs is not highlighted in yellow as expected.

### Issue - 2:
- When moving backward across cells, the matches inside the output area seem to highlight correctly (though not visible due to Issue-1).
- However, if the same cell also contains matches in its editor, clicking “Previous” does not move the highlight from the output portion into the editor portion.
- Instead, the pointer immediately jumps to the previous cell.

## Reproduce

https://github.com/user-attachments/assets/8c19a168-2b16-4f8a-ad87-c589f5ce86cd

1. Open a notebook in JupyterLab.
2. Press Cmd+F (or Ctrl+F) to open the Search & Replace dialog.
3. Enable “Show from outputs” option.
4. Perform a search that matches both in cell outputs and in the cell editor text.
5. Use the Previous Match navigation button (↑).

## Expected behavior
- The active match in the cell output should be highlighted properly.
- Navigation should cycle through all matches across the cells flawlessly.

## Context

- Operating System and version: macOs Tahoe 26.0
- Browser and version: Edge
- JupyterLab version: latest

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by itsmevichu**
## References

Closes #17796 

## Code changes
- Added `jp-current-match` to highligh the cell output.
- Added a `if` condition to check for any remaining match in the current cell before proceeding to the previous cell.

## User-facing changes
- The active match in the cell output is highlighted properly.

## Backwards-incompatible changes
NIL

### CODE REVIEW

**Comment by itsmevichu** [comment]
The problem is that when moving to the previous match from an output selection, `searchEngine.getCurrentMatch()` is called on the `CodeMirrorSearchHighlighter`, which always returns null for cell outputs (since those are handled by `CodeCellSearchProvider`). Because of this, `this._currentProviderIndex -= 1` runs and the current cell is skipped.

https://github.com/jupyterlab/jupyterlab/blob/47fcd3d06e82a100203f077a82f61532e0776a24/packages/notebook/src/searchprovider.ts#L645-L659

File: packages/documentsearch/src/providers/genericsearchprovider.ts [hunk 1]
```diff
@@ -334,10 +334,13 @@ export class GenericSearchProvider extends SearchProvider<Widget> {
...
 
+        const spanNode = document.createElement('span');
+        spanNode.appendChild(markedNode);
+
         const newNode = activeNode.splitText(match.position);
         newNode.textContent = newNode.textContent!.slice(match.text.length);
-        parent.insertBefore(markedNode, newNode);
-        return markedNode;
+        parent.insertBefore(spanNode, newNode);
+        return spanNode;
```
Comment (krassowski) [inline packages/documentsearch/src/providers/genericsearchprovider.ts]: I think we should be able to solve this with CSS instead?

Comment (krassowski) [reply packages/documentsearch/src/providers/genericsearchprovider.ts]: I though that adding  `.jp-current-match.cm-searching` in the block below could suffice.

https://github.com/jupyterlab/jupyterlab/blob/4cdd285651da0480b1e645a70324184303654e98/packages/codemirror/style/base.css#L86-L101

But it looks it would require `.CodeMirror-selectedtext` instead. I think we can try this change as-is.

**Comment by itsmevichu** [comment]
> Thank you @itsmevichu!

My pleasure! Finally got some time to wrap up this long pending one.

**Comment by krassowski** [comment]
> Notice:   1 failed
>    [jupyterlab] › test/jupyterlab/filebrowser.test.ts:6:5 › Drag file from nested directory to parent via breadcrumb 

Tracking this in https://github.com/jupyterlab/jupyterlab/issues/18008 but not really sure why it only fails on this branch.
