### PR TITLE
Fix broken see-also reference for `inspect_request` message

### LINKED ISSUE #17683: See also documentation reference is broken for kernel message types
Image

There is not even `IKernel`, only `IKernelConnection`

https://github.com/jupyterlab/jupyterlab/blob/22562319f14b87e46df9d984f47bf587593f52f3/packages/services/src/kernel/messages.ts#L874-L875

### PR DESCRIPTION
**Pull request by Krish-876**
Fixes #17683

The documentation for the `inspect_request` kernel message referenced
`IKernel.inspect`, which does not exist. This PR updates the reference
to `IKernelConnection.inspect` and fixes the malformed link syntax.

This is a documentation-only change and does not affect runtime behavior.

### CODE REVIEW

File: packages/services/src/kernel/messages.ts
Comment (krassowski) [inline packages/services/src/kernel/messages.ts]: Also here:

```suggestion
 * **See also:** [[IInspectRequest]], [[IKernelConnection.inspect]]
```

Comment (krassowski) [inline packages/services/src/kernel/messages.ts]: Does this one and following occurrences need updating too?

```suggestion
 * **See also:** [[IInterruptReplyMsg]], [[IKernelConnection.interrupt]]
```

Comment (krassowski) [inline packages/services/src/kernel/messages.ts]:
```suggestion
 * **See also:** [[IInspectRequest]], [[IKernelConnection.inspect]]
```

**Comment by Krish-876** [comment]
Thanks! I’ve applied the suggested updates to all related occurrences.

**Comment by krassowski** [comment]
I think there are more cases, can you update them too?

**Comment by Krish-876** [comment]
> I think there are more cases, can you update them too?

Thanks for the follow up! I double checked the file and updated all inspect related See also references I could find to use IKernelConnection.inspect.
If you’re seeing a specific remaining case I may have missed, could you point it out?

**Comment by krassowski** [comment]
Sorry, I meant that there is quite a few more `IKernel` references which I think need to be replaced by `IKernelConnection`.

**Comment by Krish-876** [comment]
I’ve updated the remaining See Also references to consistently point to the public IKernelConnection APIs. Please let me know if there are other message types that should be updated as well

**Comment by krassowski** [comment]
Hmm it looks like none of these render correctly:

image

**Comment by krassowski** [comment]
Also

image

**Comment by krassowski** [comment]
Maybe typedoc used to accept that format but I guess we need to use `{@link IMessage}`. Maybe we should also use `@see`. https://typedoc.org/documents/Tags._see.html

**Comment by Krish-876** [comment]
Thanks for the example, I’ll check how TypeDoc expects these references to be formatted and update the links so they render correctly.

**Comment by Krish-876** [comment]
I updated the doc comments to use TypeDoc compatible @see {@link ...} references instead of the previous wiki style links. Please let me know if you’d like me to make any additional changes.

File: packages/services/src/kernel/messages.ts [hunk 1]
```diff
@@ -1050,8 +1052,8 @@ export interface IIsCompleteRequestMsg
  * An `'is_complete_reply'` message on the `'stream'` channel.
  *
  * See [Messaging in Jupyter](https://jupyter-client.readthedocs.io/en/latest/messaging.html#code-completeness).
- *
- * **See also:** [[IIsCompleteRequest]], [[IKernel.isComplete]]
+ * @see {@link ICompleteRequest}
```
Comment (krassowski) [inline packages/services/src/kernel/messages.ts]:
```suggestion
 * @see {@link IIsCompleteRequest}
```

File: packages/services/src/kernel/messages.ts [hunk 2]
```diff
@@ -1036,8 +1038,8 @@ export interface IHistoryReplyMsg extends IShellMessage<'history_reply'> {
  * An `'is_complete_request'` message.
  *
  * See [Messaging in Jupyter](https://jupyter-client.readthedocs.io/en/latest/messaging.html#code-completeness).
- *
- * **See also:** [[IIsCompleteReplyMsg]], [[IKernel.isComplete]]
+ * @see {@link ICompleteReplyMsg}
```
Comment (krassowski) [inline packages/services/src/kernel/messages.ts]:
```suggestion
 * @see {@link IIsCompleteReplyMsg}
```

**Review by krassowski — APPROVED** [review]
