### PR TITLE
URLExt.join cant handle colon in relative paths

### LINKED ISSUE #9159: Stylesheet failed to load in case of a path segment that includes a :
Hi.

We are integrating JupyterLab into a cloud environment that has some special path handling. 

It uses urls like this: https://host-name/path1/abc:xyz/lab

JupyterLab loads fine but at the place it generates absolute urls for CSS files it seems to make an error that leads to

Error Loading Theme
Stylesheet failed to load: abc:/path1/abc:xyz/lab/api/themes/@jupyterlab/theme-light-extension/index.css

It might be related to the way that urls are generated here: https://github.com/blink1073/jupyterlab/blob/e633ff77d39b00284359b6ae8eea5ec7f7bdd813/packages/coreutils/src/url.ts#L55

### PR DESCRIPTION
**Pull request by ajbozarth**
## References

Fixes #9159

## Code changes

URLExt.join checks for a colon to seperate protocol prefix from a path.
This happens to work with relative paths because it just sets the prefix
to empty string, but if the relative path includes a colon it thinks
it's a protocol and returns malformed urls.

This fix checks if the given path is relative and sets the prefix to
empty string as it would be if there was no colon.

### CODE REVIEW

**Comment by ajbozarth** [comment]
Tagging @afshin and @blink1073 for review since you two wrote this function.

Note that afaik only the theme code hands relative paths and so this is seen by users as missing CSS files.

File: packages/coreutils/src/url.ts [hunk 1]
```diff
@@ -58,9 +58,12 @@ export namespace URLExt {
     const slashes = colon && header![3];
 
     // Construct the URL prefix.
-    const prefix = shorthand
-      ? '//'
-      : [protocol, colon, slashes].filter(str => str).join('');
+    let prefix = [protocol, colon, slashes].filter(str => str).join('');
```
Comment (jasongrout) [inline packages/coreutils/src/url.ts:61]: How about we fix the header regex above to correctly recognize the protocol instead of make the mistake? According to the RFC, the [scheme](https://tools.ietf.org/html/rfc3986#section-3.1) can only be something like `ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )`. Can we fix the `top.match` line above to correctly parse this?

Another useful resource is the matching ABNF for relative paths: https://tools.ietf.org/html/rfc3986#section-3.3

Comment (jasongrout) [reply packages/coreutils/src/url.ts:61]: Another thing we can do is use the built-in browser URL object to try to parse things. That does all the correct work for us, and is probably much safer, etc: https://developer.mozilla.org/en-US/docs/Web/API/URL

Comment (afshin) [reply packages/coreutils/src/url.ts:61]: Using the browser functionality is probably sound, but I can't remember if we needed `coreutils` to work in `node`.

The trouble is that we aren't dealing with URI/URL values, so it is sound to have the scheme shorthand `//www.example.com/foo/bar` which tells the browser to use whichever protocol is already being used.

Comment (jasongrout) [reply packages/coreutils/src/url.ts:61]: Of course we'd have to use the base parameter for `URL` if we had a relative url. This works fine, for example: `new URL('//a.b.c/d/e', 'https://myurl.com/')`.

Comment (jasongrout) [reply packages/coreutils/src/url.ts:61]: In fact, I think we can just always put in the base parameter for URL no matter what, and the browser will use it if it should.

Now, working in node - right, that is another issue. I think it's probably still good to correct our url parsing above to conform to the RFC.

Comment (jasongrout) [reply packages/coreutils/src/url.ts:61]: huh, except node has a URL package too: https://nodejs.org/api/url.html

Comment (afshin) [reply packages/coreutils/src/url.ts:61]: Right, there are two issues, I agree with you that using `URL(...)` is better all around.

It looks like at some point we meticulously made sure to check if `document` exists before doing browser-specific things, but right now the `time.ts` module appears to refer to `document.documentElement` without checking.

I think we wanted `coreutils` to be useful in a CLI environment, but maybe the time-format functions have never needed to be used in `node` so we didn't notice. Although since node ships with a URL lib, maybe we can conditionally import it if it doesn't exist the way Lumino does with `window.crypto` vs. `requires('crypto')` ...

Comment (afshin) [reply packages/coreutils/src/url.ts:61]: This conversation was too async, we arrived at the same conclusions :joy:

Comment (jasongrout) [reply packages/coreutils/src/url.ts:61]: `let jasonResponsd = await dariansConclusion;` :)

Comment (ajbozarth) [reply packages/coreutils/src/url.ts:61]: Ok so I'm having trouble following the async convo, what is the conclusion exactly?

Comment (afshin) [reply packages/coreutils/src/url.ts:61]: I think the idea is that we should switch the implementation of this function from parsing the strings ourselves to using the `URL` object but also making sure it works both in `node` and in the browser.

**Comment by ajbozarth** [comment]
@afshin @jasongrout I've been reading both the node and web URL docs and maybe I'm misunderstanding it, but I'm not sure how you were thinking we would leverage other of those APIs for this function. Currently `URLExt.join` acts as a URL equivalent to `path.join` taking in an array of parts and joining them together with a `/` delimiter, making sure to remove leading and trailing `/`. It also checks if the first param includes a protocol and makes sure it is not lost when cleaning the parts as previously described. In this case acceptable protocols are: `<protocol>://`, `//`, or `/` (aka relative). As far as I can tell both the URL libraries only support the first case, but current code also leverages the last case, a relative url.

I could replace this section of code (lines 54 - 61) with a URL lib call that checks for a valid URL, but the code to check for `//` and relative case would still need to exist. https://github.com/jupyterlab/jupyterlab/blob/04e0990172efe284762024771ae240e715f52b85/packages/coreutils/src/url.ts#L54

References:
https://nodejs.org/api/url.html
https://developer.mozilla.org/en-US/docs/Web/API/URL

**Comment by jasongrout** [comment]
Perhaps we did get a little carried away with the URL suggestion.

My understanding of this function is that it first strips off the first part of a url, all the way up to the path, then combines path segments, then prepends that first part of the url if it was there originally. The problem is that we are not correctly identifying the first part of the URL in some cases.

The thought was that we could either:

A. use the correct regex for the scheme (see [original suggestion](https://github.com/jupyterlab/jupyterlab/pull/9169#discussion_r506415113)), something like `const header = top.match(/([a-zA-Z][a-zA-Z0-9+.\-]+)(:)(\/\/)?/);
`. But then we'd also have to handle the server name, plus authentication and port, etc., all the way up to the path. (For example, if we had `//user:pass@server.com:port/a/../../b/c` or something, will it be handled correctly?
B. Use `new URL` on that first component to try to strip off the beginning url part. For example, something like `new URL(parts[0], 'XXXX://example.com')`, or even just `new URL(parts[0])` and catch any errors and deal with those separately.

A separate issue is that this regex magic to do the resolution makes me a bit nervous - I'd rather we just call a browser version of the npm path.join, if we can.

**Comment by jasongrout** [comment]
@ajbozarth - I realize this may have blown up in scope here. Minimally, I'd suggest making the protocol parsing actually more correct (like in the A option above). There are other issues brought up here with this function, but those can also be tackled in a different PR. Here's another: how come we are doing our own regex processing instead of using PathExt.join from the path.ts file, or using the join function from the `path-browserify` module?

**Comment by ajbozarth** [comment]
Based on @jasongrout comments above I decided to rework the whole function to leverage PathExt.join to handle the regex leg work. That only left a few minor tweaks to deal with PathExt.join removing some `/` that should stay. I also added test cases.

On another note, fixing this bug is a blocker for a client so if this requires further work to clean up the code around this I would prefer committing this working fix and back porting then continuing work in a follow up PR if possible

File: packages/coreutils/test/url.spec.ts [hunk 2]
```diff
@@ -36,6 +36,13 @@ describe('@jupyterlab/coreutils', () => {
     describe('.join()', () => {
       it('should join a sequence of url components', () => {
         expect(URLExt.join('/foo/', 'bar/')).toBe('/foo/bar/');
+        expect(URLExt.join('//example.com', 'bar/')).toBe('//example.com/bar/');
+        expect(URLExt.join('//example.com', 'foo:bar/')).toBe(
+          '//example.com/foo:bar/'
+        );
+        expect(URLExt.join('http://www.example.com/', '/bar')).toBe(
+          'http://www.example.com/bar'
```
Comment (jasongrout) [inline packages/coreutils/test/url.spec.ts:44]: Can you add these testcases as well?

```js
expect(URLExt.join('//example.com', 'foo:bar:', 'baz')).toBe('//example.com/foo:bar:/baz');
expect(URLExt.join('http://example.com', 'foo', '..', '..', 'bar')).toBe('http://example.com/bar/');
```

Comment (ajbozarth) [reply packages/coreutils/test/url.spec.ts:44]: I added those cases and found that the first one failed, so I also updated the code to address it. Specifically the replace shouldn't be called when there is no protocol

Comment (jasongrout) [reply packages/coreutils/test/url.spec.ts:44]: Thanks Alex! I also looked at it a bit tonight, and realized we could be using the url-parse package like we are doing elsewhere in the file. If it's all right with you, can I submit a commit on top of this?

**Comment by ajbozarth** [comment]
It seems some tests are failing due to my change, they specifically test that relative paths are not supported (but they are now). Should I update those tests or update my code to not use PathExt?

File: packages/coreutils/test/url.spec.ts (hunk 2 above)
Comment (ajbozarth) [reply packages/coreutils/test/url.spec.ts:44]: Go ahead, my priority is just getting a fix in for our client

**Comment by jasongrout** [comment]
Yeah, I saw that PathExt has this weird behavior with removing a slash.

I also took a crack at it, using url-parse and straight up posix path (like PathExt, but without the weird removing slash behavior). What do you think?

**Comment by ajbozarth** [comment]
tested it locally and it works great, I did notice a small issue with how you did auth so I fixed it and added a test for that case. So this LGTM

**Comment by jasongrout** [comment]
> tested it locally and it works great, I did notice a small issue with how you did auth so I fixed it and added a test for that case. So this LGTM

Good catch on the auth case!

I'll leave this open for a day in case @afshin has any comments, then merge if (relevant) tests pass.

**Comment by ajbozarth** [comment]
for the test failure the js-notebook one looks unrelated, but js-services seems to be caused by a change in this PR, do we want to update that test?

**Comment by jasongrout** [comment]
It seems really odd to me that the tests failing in services are actually features we want to preserve: https://github.com/jupyterlab/jupyterlab/blob/46908b566e84d2f025db509f0591b9d86522e796/packages/services/test/contents/index.spec.ts#L293-L298 https://github.com/jupyterlab/jupyterlab/blob/46908b566e84d2f025db509f0591b9d86522e796/packages/services/test/contents/index.spec.ts#L826-L830

@ian-r-rose, if you happen to remember and have time to respond - is that a feature that relative paths are not supported, or just documenting the problems with the current implementation.

**Comment by jasongrout** [comment]
Since we are merging to master, this is in the 3.0 milestone, and the backport will be in the 2.2.9 milestone.

**Comment by jasongrout** [comment]
Codeql failures are expected

**Comment by jasongrout** [comment]
Merging. We'll iterate if there are issues. Thanks @ajbozarth for pushing forward on this!

**Comment by jasongrout** [comment]
@meeseeksdev backport to 2.2.x

**Comment by jasongrout** [comment]
@ajbozarth - can you do the backport?
