### PR TITLE
Correctly dispose `TerminalManager` even if terminals are not available

### LINKED ISSUE #17875: `ServiceManager.dispose()` fails if terminals are not available
This affects extension authors and reuse of components in reactive applications. `ServiceManager.dispose()`  calls `TerminalManager.dispose()` which is broken when terminals are unavailable:

It fails on `this._pollModels.dispose();`:

https://github.com/jupyterlab/jupyterlab/blob/9b34a51a16680465ed4c32900f561af1830e7deb/packages/services/src/terminal/manager.ts#L93-L101

because `this._pollModels` is undefined if terminal is not available:

https://github.com/jupyterlab/jupyterlab/blob/9b34a51a16680465ed4c32900f561af1830e7deb/packages/services/src/terminal/manager.ts#L18-L39

So the type annotation is wrong:

https://github.com/jupyterlab/jupyterlab/blob/9b34a51a16680465ed4c32900f561af1830e7deb/packages/services/src/terminal/manager.ts#L280

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes #17875

## Code changes

- [x] Fixes typing
- [x] Fixes usage

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

File: packages/services/src/terminal/manager.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ export class TerminalManager extends BaseManager implements Terminal.IManager {
     }
 
     // Start polling with exponential backoff.
-    this._pollModels = new Poll({
+    const pollModels = (this._pollModels = new Poll({
```
Comment (jtpio) [inline packages/services/src/terminal/manager.ts:37]: Maybe an alternative to avoid changing the types could be to move the block that checks `this.isAvailable()` a bit below, before setting the `this._ready` promise which then starts the polls?

Comment (krassowski) [reply packages/services/src/terminal/manager.ts:37]: Yes, we could do that but it feels like updating the types is fine:
- it is a private variable
- if a user/extension called `refreshRunning()` with poll initialized it could have unexpected effects; with this PR as is it would just do nothing.

Comment (krassowski) [reply packages/services/src/terminal/manager.ts:37]: @jtpio is changing the types a big concern? If so I can rework this PR.

Comment (jtpio) [reply packages/services/src/terminal/manager.ts:37]: It's likely fine.

Probably we could also consider instantiating a `NoopManager` at the plugin level when the terminals are not available? 

Something like the following in:

https://github.com/jupyterlab/jupyterlab/blob/4cdd285651da0480b1e645a70324184303654e98/packages/services-extension/src/index.ts#L257-L278

```ts
if (!Terminal.isAvailable()) {
  return new TerminalManager.NoopManager();
}
```

Comment (krassowski) [reply packages/services/src/terminal/manager.ts:37]: I think this makes sense, but this might be a potentially breaking change - see my comment in https://github.com/jupyterlab/jupyterlab/pull/17930 which I opened to explore this as a follow-up (since I would like to backport this PR to `4.4.x`).
