### PR TITLE
Fix clicking in the TOC does not scroll

### LINKED ISSUE #14591: Table of Contents: selecting heading only scrolls to position the first time
## Description

When you select a heading in the table of contents, it automatically starts editing the cell. This is not preferred behavior for me, but I can live with it. More problematic, however, is that once the cell is in edit mode, clicking the header again in the ToC will not scroll to the cell. This happens even if you have currently selected/are editing another code or markdown cell, and can be true for multiple headers at the same time. Effectively, you could have an entire table of contents and none of the headers work!

## Reproduce

In the example notebook below: scroll up so that the heading h1 is offscreen. Click h1 in the table of contents, you get scrolled down to it and the cell enters edit mode. Scroll up and optionally select one of the filler cells; clicking the heading again in the table of contents does nothing. Only fixed when the markdown cell is run again.

## Expected behavior

When you click a heading cell in the table of contents, you should always be scrolled to it. In my opinion, it also shouldn't automatically start editing markdown cells, but that's of a secondary concern.

## Context

example notebook contents:
```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1733768e-510c-4fef-b5b9-b086fd969d44",
   "metadata": {},
   "outputs": [],
   "source": [
    "filler = 4"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9d81f6ec-cbd8-49e7-908f-f315b26de2d3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "262057a5-f605-4e23-bf26-f0035189fd8c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2f2d07fc-3bb6-4464-8dda-453d74d5766c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "f37c6c3a-204c-4b92-87d2-db1b28810597",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "cfe35aec-32c0-4d84-82c9-5324a66eab13",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f81f92a1-da97-430a-b785-d85024a600d5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "5c0f0966-852c-4c36-ab8e-fe37262c6826",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "b79cc1dd-a477-4049-8167-3ecd257377b7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "4eb14bda-aa6a-4e9a-83a7-c4829abba2fb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "f996f5ec-5786-4225-bfc7-69f0a2f18c87",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "f07f2ffe-d486-47c0-a63c-5ec454ed9054",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "ab6f22c7-573b-4dd8-a15e-c188433e09f5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "2dc45e1b-c960-47cc-9c14-fe4b950e0810",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cc9db4bb-e736-410e-835b-bef8a971b4b5",
   "metadata": {},
   "source": [
    "## h1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "da7b7248-b994-410c-9b3a-ff3c7591a3be",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by parmentelat**
workaround for cases where headingToElement map is not properly filled

## References

fixes #14591  
intended to supersede #14884

## Code changes

as suggested by @fcollonval in this post
https://github.com/jupyterlab/jupyterlab/pull/14884#pullrequestreview-1568943032

the `onActiveHeadingChanged` function (notebook viewer)
uses a fallback strategy in pathological cases where `headingToElement` map is not properly filled

## User-facing changes

no visual change; clicking in a TOC entry should more reliably scroll to the corresponding cell

## Backwards-incompatible changes

none

### CODE REVIEW

**Comment by parmentelat** [comment]
there are several possible further directions to this PR

- @fcollonval also suggested, in case the target cell is in edit mode, to select the title  
  imho this is not necessarily a good idea, mentioned here for the record
- I have observed similar flaws in the `markdownviewer` area; however the approach used here is not applicable there

regardless, in my experience this first step would already be of great help, particularly in the context of
https://github.com/executablebooks/jupyterlab-myst/issues/184

also, I went for starting on top of the `4.0.x` branch, because that's the version I would be targetting, be should it have gone onto `main` instead ?

**Comment by krassowski** [comment]
Yes, it should be targeting the `main` branch.

**Comment by parmentelat** [comment]
hi @krassowski 
please let me know if there's anything I can do to help this ship as early as possible
I am massively using jupyterlab-myst and this issue basically ruins navigation through the TOC, which is a major productivity impediment, so again I'm highly motivated here ;)

**Comment by krassowski** [comment]
Adding a test case which demonstrates the issue on `main` and fixes it here would help.

**Comment by parmentelat** [comment]
starting here
https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#visual-regression-and-ui-tests

I went to there
https://github.com/jupyterlab/jupyterlab/blob/main/galata/README.md

where I was instructed to do this:

```
cd jupyterlab-repo-top

jlpm add -D @jupyterlab/galata
→ ... ➤ YN0000: Done with warnings in 2s 676ms

# so far so good, but

jlpm playwright install
→ Usage Error: Couldn't find a script named "playwright".
```

what am I doing wrong ?

**Comment by krassowski** [comment]
The https://github.com/jupyterlab/jupyterlab/blob/main/galata/README.md is a bit odd because it is a mix of instructions for use with jupyterlab and with extensions and it has a tendency to get outdated. There is no `jlpm playwright` when running galata in jupyterlab, what I use is:

```bash
jlpm install # just once
# then check nothing is running on port 8888
jlpm run start
# then wait for jupyterlab to start, open another terminal
jlpm run test --project jupyterlab --grep "testofinterest"
```

If a lab instance is running on 8888 and stuck (i.e. you cannot shut it down) I use `kill -9 $(sudo lsof -i -P -n | grep LISTEN | grep 8888 | awk '{ print $2 }')`

**Comment by parmentelat** [comment]
thanks for the tips
before I pour my own test in the mix, I'm trying to run the 'official' test named `toc.test.ts`
but there's clearly something fishy with the `test-toc` temporary folder, that I don't have on my filesystem, and that causes the test to fail with errors like this 
```
[W 2023-10-01 16:31:22.915 ServerApp] 404 GET /api/contents/test-toc?type=directory&content=1 (::1): No such file or directory: test-toc
```

is there anythong I should know about `test-toc` ?
```

**Comment by fcollonval** [comment]
Thanks @parmentelat 

The code looks good - if you could add the test in this PR, it will be easier to validate it and produce the _correct_ reference snapshot.

**Comment by parmentelat** [comment]
please update galata snapshots

**Comment by parmentelat** [comment]
once the linux snapshot is produced and it checks out as compared to the darwin one, we can remove the latter

**Comment by fcollonval** [comment]
FYI the commit updating snapshots are not triggering the CI (some limitation of GitHub to avoid infinite job run). To force the CI to be executed the trick is to close and reopen the PR, don't hesitate to do it when you see the new snapshot commit.

**Comment by parmentelat** [comment]
shaking the PR

**Comment by parmentelat** [comment]
please update galata snapshots

**Comment by parmentelat** [comment]
@fcollonval 
I have closed and reopened the PR, but am still struggling to get the snapshot updated
please advise...

File: packages/notebook/src/toc.ts [hunk 1]
```diff
@@ -530,6 +530,9 @@ export class NotebookToCFactory extends TableOfContentsFactory<NotebookPanel> {
             ) {
               el.scrollIntoView({ block: 'center' });
             }
+          } else {
+            console.debug('scrolling to heading: using fallback strategy');
+            widget.content.scrollToItem(widget.content.activeCellIndex);
```
Comment (krassowski) [inline packages/notebook/src/toc.ts:535]: `Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator`

**Review by krassowski — COMMENTED** [review]
I see the galata update actions running on CI, one started two hours ago but was only picked up an hour ago: https://github.com/jupyterlab/jupyterlab/actions/runs/6381080519/job/17316801930 (probably will fail to push updates though if your forced pushed in the mean time) another is waiting (https://github.com/jupyterlab/jupyterlab/actions/runs/6382766999). There was a few merges, and a few authors rebased their PRs eagerly which lead to CI falling behind (in addition to being generally slower since last month).

**Comment by parmentelat** [comment]
I am no gh actions expert as you have noticed, so thanks for having my back :)

the linux snapshot is now updated and so I have removed the darwin snapshot

File: packages/notebook/src/toc.ts (hunk 1 above)
Comment (fcollonval) [reply packages/notebook/src/toc.ts:535]: To provide some guide line to fix this. I suggest changing:
* `onCellInViewport` to be `async (cell: Cell): Promise<void>`
* adding `await in front of Line 535
* adding `return` at line 550 so that the catch line 552 will catch everything

**Comment by parmentelat** [comment]
I am unsure how to proceed from this point on, is there anything else I need to do to get this merged ?

**Comment by krassowski** [comment]
It looks the liner is still falling:

```
2023-10-05T07:04:07.4461474Z + [[ lint == integrity ]]
2023-10-05T07:04:07.4461789Z + [[ lint == lint ]]
2023-10-05T07:04:07.4583259Z + jlpm run prettier:check
2023-10-05T07:04:08.9120557Z Checking formatting...
2023-10-05T07:04:32.1575423Z [warn] packages/notebook/src/toc.ts
2023-10-05T07:04:41.4732063Z [warn] Code style issues found in the above file. Run Prettier to fix.
2023-10-05T07:04:41.5334848Z + echo 'Please run `jlpm run prettier` locally and push changes'
```

**Comment by parmentelat** [comment]
thanks @krassowski I will take care of it
also I realize I did an unintentional merge, is it preferable that I rebase instead ?

**Comment by krassowski** [comment]
No, is fine we do squash merges anyways.

**Comment by krassowski** [comment]
I tested this locally and it fixes one part of the issue (scrolling on click when switching between headings), but does not seem to fix the problem of lack of scrolling when clicking the same header twice. @parmentelat can you confirm that you also see the same:
1. Click on a heading in the ToC
2. Scroll down
3. Click on the same heading again

Does it scroll back to the heading for you? Note: I am not saying that we should not merge it as-is (we should, it is a great improvement), just want to make sure that we have a clarity on whether merging this PR closes https://github.com/jupyterlab/jupyterlab/issues/14591 or not.

**Comment by parmentelat** [comment]
I can confirm your observation, if I follow your scenario the clicked heading does not come back into view

somehow it does not surprise me because we're talking about a callback that's named `onActiveHeadingChanged`, and in your scenario the active heading, well, does not change...

I can see how this can feel off in terms of user experience, obviously

**Comment by parmentelat** [comment]
is there a chance this may be merged for the next official release ? 
is there anything else I can do to this end ?

File: galata/test/jupyterlab/toc-scrolling.test.ts [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+    );
+  });
+
+  test.beforeEach(async ({ page, tmpPath }) => {
+    await page.notebook.openByPath(`${tmpPath}/${fileName}`);
+    await page.notebook.activate(fileName);
+
+    await page.sidebar.openTab('table-of-contents');
+
+    // await page.click('.jp-toc-numberingButton');
```
Comment (krassowski) [inline galata/test/jupyterlab/toc-scrolling.test.ts:26]: I guess this is not used anymore?

```suggestion
```

**Review by krassowski — APPROVED** [review]
One tiny suggestion, otherwise it looks good to me.

**Comment by parmentelat** [comment]
for the record, the very same code - modulo the harmless removal of a comment line in the very last commit -  has been passing all the checks
I am at a loss to know what to do more on this one, please merge if everything is ok

**Comment by krassowski** [comment]
No worries, some of the checks are just timing out/flaky (i restarted these)  and one (`
Linux JS Tests / JS (js-metapackage) `) is an issue which will be fixed by https://github.com/jupyterlab/jupyterlab/pull/15237 but that needs review before we can proceed with merging it and then other PRs.

**Comment by krassowski** [comment]
I hope to merge this one (along a few others) and release a new point release this week.

**Review by fcollonval — APPROVED** [review]
Thanks @parmentelat

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 4.0.x
