### PR TITLE
Fix a bug since merging arrow navigation between buttons in Dialog (#10349)

### LINKED ISSUE #10394: Using arrows in file dialog and others is broken
## Description

Using arrows is not possible in the file browser input field since merging #10349.

## Reproduce

1. Open rename dialog
2. Try to use arrow keys in the input field
3. See buttons getting focus instead

input-bug

## Expected behavior

Buttons do not steal focus from input fields

## Context

- Browser and version: Chrome
- JupyterLab version: 3.1.0a12

### PR DESCRIPTION
**Pull request by jahn96**
## References

Fixes #10394 

## Code changes

* Added a guard checking for a keydown to be handled only when the focused element is a button.

## User-facing changes
* Pressing arrow keys do not steal the focus from the input element.

arrow_navigation

## Backwards-incompatible changes

None

### CODE REVIEW

File: packages/apputils/src/dialog.tsx [hunk 1]
```diff
@@ -305,34 +305,40 @@ export class Dialog<T> extends Widget {
...
+          if (idx == this._buttons.length) {
+            idx = 0;
+          }
+
+          const node = this._buttonNodes[idx];
+          event.stopPropagation();
+          event.preventDefault();
+          node.focus();
+          break;
+        }
```
Comment (krassowski) [inline packages/apputils/src/dialog.tsx:341]: Lint picked up a case that is missing termination. I think that moving the `break;` below the bracket is all that is needed.

```suggestion
        }
        break;
```

**Review by krassowski — APPROVED** [review]
This fix works good, thank you!
