### PR TITLE
Fix handling of codemirror focus and dialog in notebook

### LINKED ISSUE #3503: notebook cell aggressive focus prevents codemirror dialog focus
With [jupyterlab_vim](https://github.com/jwkvam/jupyterlab_vim), code mirror dialogs never get focused. The dialogs appear when searching `/` or entering command line mode `:`. I appreciate the UX reason for disabling dialogs with default codemirror instances. I think they are expected in vim mode. For example searching is useful for navigating code and command line mode can be used for many things like search and replace and saving notebooks.

I don't think this issue affects vanilla JupyterLab.

Maybe I can try disabling some `_ensureFocus` calls in https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook/src/widget.ts#L1123?

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #3503.

cc @jwkvam 

image

### CODE REVIEW

File: buildutils/src/add-sibling.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ if (fs.existsSync(packagePath)) {
 } else {
   // Otherwise treat it as a git reposotory and try to add it.
   packageDirName = target.split('/').pop().split('.')[0];
-  let packagePath = path.join(basePath, 'packages', packageDirName);
+  packagePath = path.join(basePath, 'packages', packageDirName);
```
Comment (ian-r-rose) [inline buildutils/src/add-sibling.ts]: Nice catch.

**Comment by jwkvam** [comment]
Excellent!!! Thanks guys.
