### PR TITLE
Expand the file browser breadcrumbs when there is space available adaptively

### LINKED ISSUE #18377: Browser path - Too short (not adaptive)
### Problem

I'm always frustrated, that I do not see longer path, as the last 2 levels are often not enough.

Despite, there is more than enough space, we see only last 2 levels, which is often not enough for good orientation.
(especially, when many project have the same standardized nested layout, one is not able to distinguish between projects, when only last 2 levels are visible, as they are same in every project)

Image

### Proposed Solution

Browser path should be adaptive and show **all last** levels, that fit into free space of the Browser sidebar.
That means, when we make it wide enough, we can always see the full path.

The path should be automatically updated (how many path levels are visible / shortened), whenever the width of the sidebar is changed.

### Reproduce

It happens in the latest version : Jupyterlab: v4.5.2
It is clearly visible (easy to reproduce).

### PR DESCRIPTION
**Pull request by MUFFANUJ**
## References
closes #18377 

## Code changes
This pull request introduces an adaptive behavior to the file browser breadcrumbs. Previously, the number of visible path segments was fixed based on user settings, which could leave unused space even when the sidebar was wide. With this change, the breadcrumbs now automatically adjust to the available horizontal space. As the file browser sidebar is widened, more path segments are progressively revealed instead of being hidden behind an ellipsis.

This still respects the existing configuration for minimum visible items to ensure a consistent experience when space is limited

## User-facing changes

https://github.com/user-attachments/assets/cb2621c1-4e2d-4c2d-a162-bdbf7199af51

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by MUFFANUJ** [comment]
@meeseeksdev tag enhancement

File: packages/filebrowser/src/crumbs.ts [hunk 1]
```diff
@@ -397,6 +407,99 @@ export class BreadCrumbs extends Widget {
...
   private _minimumLeftItems: number;
   private _minimumRightItems: number;
+  private _resizeObserver: ResizeObserver;
+  private _lastContainerWidth: number = 0;
+  private _resizeTimeout: ReturnType<typeof setTimeout> | null = null;
+
+  /**
+   * Handle resize events with debouncing.
+   */
+  private _onResize(): void {
```
Comment (krassowski) [inline packages/filebrowser/src/crumbs.ts:436]: Quick stylistic note: let's move these methods above the block of private attribute definitions.

Comment (MUFFANUJ) [reply packages/filebrowser/src/crumbs.ts:436]: Sure, Mike

**Comment by MUFFANUJ** [comment]
Hey @krassowski, if you get time please do review

File: packages/filebrowser/src/crumbs.ts [hunk 2]
```diff
@@ -388,6 +398,96 @@ export class BreadCrumbs extends Widget {
...
+    if (containerWidth === 0) {
+      return { left: this._minimumLeftItems, right: this._minimumRightItems };
+    }
+
+    const HOME_ICON_WIDTH = 22;
+    const SEPARATOR_WIDTH = 4;
+    const ELLIPSIS_WIDTH = 28;
+    const ITEM_PADDING_MARGIN = 8;
+    const AVG_TEXT_WIDTH = 80;
+    const ITEM_WIDTH = ITEM_PADDING_MARGIN + AVG_TEXT_WIDTH;
```
Comment (krassowski) [inline packages/filebrowser/src/crumbs.ts]: In general these values can vary depending on the theme. We should read them cleverly (this is without introducing performance bottleneck). It would probably need to be read in in `requestAnimationFrame` and aggressively cached.

File: packages/filebrowser/src/crumbs.ts [hunk 3]
```diff
@@ -388,6 +398,130 @@ export class BreadCrumbs extends Widget {
...
+
+  /**
+   * Measure element widths from the DOM and cache them.
+   */
+  private _measureElementWidths(): void {
+    const home = this._crumbs[Private.Crumb.Home];
+    const ellipsis = this._crumbs[Private.Crumb.Ellipsis];
+
+    // Find first separator
+    const separators = this.node.querySelectorAll(':scope > span:not([class])');
```
Comment (krassowski) [inline packages/filebrowser/src/crumbs.ts]: This selector feels fragile to changes.

If we cannot get anything better it's fine (I have not checked yet)

**Review by krassowski — COMMENTED** [review]
Looks reasonable (I have not tested this iteration yet), let's see what copilot thinks

File: packages/filebrowser/src/crumbs.ts (hunk 3 above)
Comment (MUFFANUJ) [reply packages/filebrowser/src/crumbs.ts]: You are right, for this then the best would be to add a class to the seperator as there is not class currently and use it.

**Comment by MUFFANUJ** [comment]
Interestingly i was not auto-assigned to this PR.

**Comment by krassowski** [comment]
> Interestingly i was not auto-assigned to this PR.

It looks like a one-off CI failure based on https://github.com/jupyterlab/jupyterlab/actions/runs/21607840350 being red while almost all other jobs are green https://github.com/jupyterlab/jupyterlab/actions/workflows/auto_author_assign.yml. I restarted it now.

**Comment by MUFFANUJ** [comment]
Thanks @krassowski, I have implemented the suggestion from you and Copilot, please take a look and let me know if it needs any further changes.

File: packages/filebrowser/src/crumbs.ts [hunk 4]
```diff
@@ -179,12 +194,22 @@ export class BreadCrumbs extends Widget {
...
     const localPath = contents.localPath(this._model.path);
+
+    // Invalidate cached widths if the local path (and thus breadcrumb labels) changed
+    if (this._previousState && this._previousState.path !== localPath) {
+      this._cachedWidths = null;
+    }
+
+    // Calculate adaptive items based on available width
+    const adaptiveItems = this._calculateAdaptiveItems(localPath);
+
```
[the remark this answers is not in the document]
Comment (MUFFANUJ) [reply packages/filebrowser/src/crumbs.ts]: Hmmm Interesting

File: packages/filebrowser/test/crumbs.spec.ts [hunk 5]
```diff
@@ -369,6 +369,74 @@ describe('filebrowser/model', () => {
...
+          configurable: true,
+          get: () => 1000
+        });
+
+        // Force cache invalidation and recalculation
+        (customCrumbs as any)._cachedWidths = null;
+        (customCrumbs as any)._previousState = null;
+        customCrumbs.update();
+        await framePromise();
+        MessageLoop.sendMessage(customCrumbs, Widget.Msg.UpdateRequest);
```
[the remark this answers is not in the document]
Comment (MUFFANUJ) [reply packages/filebrowser/test/crumbs.spec.ts:423]: Im not sure about this as for now the current test works fine, this might be a super good addition for future regressions but i think it would make it more complex, also until the logic isnt flawed i think it should be fine
@krassowski do you have any take on this ?

[the remark this answers is not in the document]
Comment (krassowski) [reply packages/filebrowser/test/crumbs.spec.ts:423]: Yes, I am not convinced that we should follow this suggestion. A better thing would be to add a playwright test (in addition to this one) which tests the real thing in a real browser.

File: packages/filebrowser/src/crumbs.ts [hunk 6]
```diff
@@ -388,6 +412,165 @@ export class BreadCrumbs extends Widget {
...
+      clearTimeout(this._resizeTimeout);
+    }
+    this._resizeTimeout = setTimeout(() => {
+      if (this.isDisposed || !this.isAttached) {
+        return;
+      }
+      // Force recalculation by clearing previous state
+      this._previousState = null;
+      this.update();
+    }, 100);
```
Comment (krassowski) [inline packages/filebrowser/src/crumbs.ts]: This code implements a trailing edge debouncing. It leads to a delay of at least 100ms between resize and reaction to it, and potentially much longer (if user continues to resize smoothly). This is best visualised by taking things to extreme:

https://github.com/user-attachments/assets/3c89e223-8a91-49a2-8a5c-ab3a36e2a08e

I wonder if a better approach would be to use leading edger throttling rather than debouncing. We have a Throttler in lumino https://lumino.readthedocs.io/en/latest/api/classes/polling.Throttler-1.html here is an example usage:

https://github.com/jupyterlab/jupyterlab/blob/49b0ff9adbcc1845f8949868a9314fc30cf2f4ce/packages/cells/src/resizeHandle.ts#L18-L23

And this comment demonstrates the difference https://github.com/jupyterlab/jupyterlab/pull/15357#issuecomment-1801303647

File: packages/filebrowser/src/crumbs.ts [hunk 7]
```diff
@@ -388,6 +412,165 @@ export class BreadCrumbs extends Widget {
...
+   * including those currently hidden behind the ellipsis.
+   */
+  private _measureAllItemWidths(parts: string[]): void {
+    const node = this.node;
+
+    // Measure fixed elements that are already in the DOM
+    const home = this._crumbs[Private.Crumb.Home];
+    const ellipsis = this._crumbs[Private.Crumb.Ellipsis];
+    const preferred = this._crumbs[Private.Crumb.Preferred];
+    const separators = node.querySelectorAll(`.${BREADCRUMB_SEPARATOR_CLASS}`);
```
Comment (krassowski) [inline packages/filebrowser/src/crumbs.ts]: `getElementsByClassName` would be marginally faster here, in general `getElementsByClassName()` is `O(1)` whereas `node.querySelectorAll()` is `O(n)` because it make a copy.

```suggestion
    const separators = node.getElementsByClassName(BREADCRUMB_SEPARATOR_CLASS);
```

File: packages/filebrowser/test/crumbs.spec.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (MUFFANUJ) [reply packages/filebrowser/test/crumbs.spec.ts:423]: Thanks @krassowski, I have added the test.

**Comment by MUFFANUJ** [comment]
bot please update galata snapshots

File: galata/test/jupyterlab/breadcrumbs-snapshot.test.ts [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+
+    // Set a wide viewport to accommodate sidebar expansion
+    await page.setViewportSize({ width: 1600, height: 720 });
+
+    // Wait for file browser to stabilize
+    await page.waitForTimeout(1000);
+
+    // Configure Breadcrumbs Settings
+    await page.evaluate(async pluginId => {
+      const settingsManager = (window as any).jupyterapp.serviceManager
```
Comment (krassowski) [inline galata/test/jupyterlab/breadcrumbs-snapshot.test.ts]: It should not need `any` cast I hope. Here and in line 38. Ref:

https://github.com/jupyterlab/jupyterlab/blob/49b0ff9adbcc1845f8949868a9314fc30cf2f4ce/galata/test/jupyterlab/settings.test.ts#L43-L47

File: galata/test/jupyterlab/breadcrumbs-snapshot.test.ts-snapshots/breadcrumbs-jupyterlab-linux.png
Comment (krassowski) [inline galata/test/jupyterlab/breadcrumbs-snapshot.test.ts-snapshots/breadcrumbs-jupyterlab-linux.png:1]: I'm surprised this passed. I would expect the 590480 string to be subject to change. It could also change on retries. Let's use `tmpPath` to fix it: https://github.com/jupyterlab/jupyterlab/tree/main/galata#tmppath

File: galata/test/jupyterlab/breadcrumbs-snapshot.test.ts [hunk 9]
```diff
@@ -0,0 +1,59 @@
...
+      await (window as any).jupyterapp.commands.execute(
+        'filebrowser:open-path',
+        {
+          path: p
+        }
+      );
+    }, `${tmpPath}/${path}`);
+
+    // Wait for breadcrumbs to load
+    await page.waitForTimeout(1000);
```
Comment (krassowski) [inline galata/test/jupyterlab/breadcrumbs-snapshot.test.ts]: Explicit timeouts should be replaced be locator waits as much as possible because they can lead to flaky tests on slower runners.

**Review by krassowski — COMMENTED** [review]
I have not tested latest version yet, some comments on test only for now

**Comment by MUFFANUJ** [comment]
bot please update galata snapshots

File: packages/filebrowser/src/crumbs.ts [hunk 10]
```diff
@@ -78,6 +84,10 @@ export class BreadCrumbs extends Widget {
     }
     this.node.appendChild(this._crumbs[Private.Crumb.Home]);
     this._model.refreshed.connect(this.update, this);
+    this._resizeThrottler = new Throttler(() => this._onResize(), 50);
+    this._resizeObserver = new ResizeObserver(() => {
+      void this._resizeThrottler.invoke();
+    });
```
Comment (krassowski) [inline packages/filebrowser/src/crumbs.ts:99]: Hmm reducing the width still has this jittery behavior where items can jump to next line triggering layout shift.

I think the throttler & full update can stay, but maybe we need to add another condition: take the width the resize observer receives as an argument (this corresponds to `containerWidth`), compare it the space the current items take up (+overhead) and trigger update outside of the throttler routine if this is less.

Does it make sense?

File: galata/test/jupyterlab/notebook-toolbar.test.ts-snapshots/toolbar-items-jupyterlab-linux.png
Comment (krassowski) [inline galata/test/jupyterlab/notebook-toolbar.test.ts-snapshots/toolbar-items-jupyterlab-linux.png:1]: This one was flaky, can you revert this update (`git checkout main galata/test/jupyterlab/notebook-toolbar.test.ts-snapshots/toolbar-items-jupyterlab-linux.png` then commit and push)?

File: galata/test/jupyterlab/toc-scrolling.test.ts-snapshots/scrolled-to-bottom-heading-jupyterlab-linux.png
Comment (krassowski) [inline galata/test/jupyterlab/toc-scrolling.test.ts-snapshots/scrolled-to-bottom-heading-jupyterlab-linux.png:1]: Same here.

File: galata/test/jupyterlab/notebook-toolbar.test.ts-snapshots/toolbar-items-jupyterlab-linux.png
Comment (MUFFANUJ) [reply galata/test/jupyterlab/notebook-toolbar.test.ts-snapshots/toolbar-items-jupyterlab-linux.png:1]: sure its done.

File: packages/filebrowser/src/crumbs.ts (hunk 10 above)
Comment (MUFFANUJ) [reply packages/filebrowser/src/crumbs.ts:99]: Yes, it does. I briefly tested it locally after the changes, and it definitely looks improved.

File: packages/filebrowser/src/crumbs.ts [hunk 11]
```diff
@@ -78,6 +84,17 @@ export class BreadCrumbs extends Widget {
...
+    this._resizeThrottler = new Throttler(() => this._onResize(), 50);
+    this._resizeObserver = new ResizeObserver(entries => {
+      for (const entry of entries) {
+        const newWidth = entry.contentRect.width;
+        if (this._lastRenderedWidth > 0 && newWidth < this._lastRenderedWidth) {
+          this._onResize();
+        } else {
+          void this._resizeThrottler.invoke();
+        }
+      }
```
Comment (krassowski) [inline packages/filebrowser/src/crumbs.ts:98]: Correct me if I am wrong but I think we only ever expect one entry? Suggestion below would make it more clear for a future reader I think:

```suggestion
    this._resizeObserver = new ResizeObserver((entry) => {
      if (!entry) return;
      const newWidth = entry.contentRect.width;
      if (this._lastRenderedWidth > 0 && newWidth < this._lastRenderedWidth) {
        this._onResize();
      } else {
        void this._resizeThrottler.invoke();
      }
```

File: packages/filebrowser/src/crumbs.ts [hunk 12]
```diff
@@ -78,6 +84,17 @@ export class BreadCrumbs extends Widget {
...
+    });
```
[the remark this answers is not in the document]
Comment (krassowski) [reply packages/filebrowser/src/crumbs.ts:99]: It's fine as-is.

File: packages/filebrowser/src/crumbs.ts [hunk 13]
```diff
@@ -388,6 +417,173 @@ export class BreadCrumbs extends Widget {
...
+      );
+    }
+
+    // Clean up
+    node.removeChild(measurer);
+
+    this._cachedWidths = {
+      home: (home.getBoundingClientRect().width || 22) + 4,
+      ellipsis: (ellipsis.getBoundingClientRect().width || 28) + 4,
+      separator: separator?.getBoundingClientRect().width || 4,
```
[the remark this answers is not in the document]
Comment (krassowski) [reply packages/filebrowser/src/crumbs.ts:491]: If no separator exists then we don't need this routine

File: packages/filebrowser/src/crumbs.ts (hunk 11 above)
Comment (MUFFANUJ) [reply packages/filebrowser/src/crumbs.ts:98]: Yes, thanks for pointing it, We only ever observe a single node, so looping might be unnecessary

File: packages/filebrowser/src/crumbs.ts [hunk 14]
```diff
@@ -388,6 +417,173 @@ export class BreadCrumbs extends Widget {
...
+    // If total parts fit within minimums, no adaptation needed
+    const minTotal = this._minimumLeftItems + this._minimumRightItems;
+    if (totalParts <= minTotal) {
+      return { left: this._minimumLeftItems, right: this._minimumRightItems };
+    }
+
+    const containerWidth = this.node.clientWidth;
+    if (containerWidth === 0) {
+      return { left: this._minimumLeftItems, right: this._minimumRightItems };
+    }
```
[the remark this answers is not in the document]
Comment (MUFFANUJ) [reply packages/filebrowser/src/crumbs.ts:526]: It does make sense.

File: packages/filebrowser/src/crumbs.ts [hunk 15]
```diff
@@ -78,6 +84,17 @@ export class BreadCrumbs extends Widget {
     }
     this.node.appendChild(this._crumbs[Private.Crumb.Home]);
     this._model.refreshed.connect(this.update, this);
+    this._resizeThrottler = new Throttler(() => this._onResize(), 50);
+    this._resizeObserver = new ResizeObserver(entries => {
+      for (const entry of entries) {
+        const newWidth = entry.contentRect.width;
+        if (this._lastRenderedWidth > 0 && newWidth < this._lastRenderedWidth) {
```
[the remark this answers is not in the document]
Comment (MUFFANUJ) [reply packages/filebrowser/src/crumbs.ts]: I feel this suggestion is invalid, as the first resize event happens automatically upon mounting. At that point, the component has no rendered items yet, so there is nothing to "immediately collapse."

File: packages/filebrowser/src/crumbs.ts [hunk 16]
```diff
@@ -170,6 +190,8 @@ export class BreadCrumbs extends Widget {
     node.removeEventListener('lm-dragleave', this);
     node.removeEventListener('lm-dragover', this);
     node.removeEventListener('lm-drop', this);
+    this._resizeObserver.disconnect();
+    this._resizeThrottler.dispose();
```
[the remark this answers is not in the document]
Comment (krassowski) [reply packages/filebrowser/src/crumbs.ts]: Indeed `_resizeThrottler` should be disposed in `dispose()`, not here.

The suggestion from copilot to use `disconnect` is incorrect, it does not have `disconnect()`.

Note: the dispose method should be added above the protected methods.

File: galata/test/jupyterlab/breadcrumbs-snapshot.test.ts [hunk 17]
```diff
@@ -0,0 +1,65 @@
...
+    }, `${tmpPath}/${path}`);
+
+    // Wait for breadcrumbs to reflect the navigated path
+    await page.locator(`${BREADCRUMB_SELECTOR} >> text=dir5`).waitFor();
+
+    // Widen sidebar
+    await page.sidebar.setWidth(800);
+
+    // Wait for breadcrumb recalculation after resize
+    await page.locator(`${BREADCRUMB_SELECTOR} >> text=Longer_dir4`).waitFor();
```
[the remark this answers is not in the document]
Comment (krassowski) [reply galata/test/jupyterlab/breadcrumbs-snapshot.test.ts]: I don't immediately know if that's true, it requires looking at the test execution more closely.

File: packages/filebrowser/src/crumbs.ts (hunk 16 above)
[the remark this answers is not in the document]
Comment (MUFFANUJ) [reply packages/filebrowser/src/crumbs.ts]: Sure

File: galata/test/jupyterlab/breadcrumbs-snapshot.test.ts (hunk 17 above)
[the remark this answers is not in the document]
Comment (MUFFANUJ) [reply galata/test/jupyterlab/breadcrumbs-snapshot.test.ts]: `dir3` is also visible when the sidebar is rendered, so keeping the safer option (`dir2`) seems more appropriate. The width adjustment happens quickly and hasn’t affected the snapshot tests so far. Overall, I think this suggestion makes sense.
