### PR TITLE
Fix handling of code editor refresh

### LINKED ISSUE #7671: Code editor refresh is brittle
## Description
The logic around when to refresh the code editor is brittle.  I tested this by opening the same set of static notebook contents in three main area widgets.  The last one populated successfully shows its input areas, but the other two did not.  I have a fix coming.

### PR DESCRIPTION
**Pull request by blink1073**
## References
Fixes #7671 

## Code changes
Handles the case where a code editor is not visible when it tries to update.  This can happen when the widget is attached and visible, and then is no longer visible when `onUpdateRequest` is later called.

## User-facing changes
None in core JupyterLab, affects extension authors using code editors and things that depend on them (like notebooks).

## Backwards-incompatible changes
None.

### CODE REVIEW

File: packages/codeeditor/src/widget.ts [hunk 1]
```diff
@@ -141,7 +141,7 @@ export class CodeEditorWrapper extends Widget {
    * A message handler invoked on an `'after-show'` message.
    */
   protected onAfterShow(msg: Message): void {
-    if (this._updateOnShow) {
+    if (this._updateOnShow || !this._hasRefreshed) {
```
Comment (jasongrout) [inline packages/codeeditor/src/widget.ts]: It seems like this should be `&&`, not `||`? Also, should `_hasRefreshed` be reset to false on hide?

Comment (blink1073) [reply packages/codeeditor/src/widget.ts]: I updated the variable name and added a comment, as well as a reset whenever we attach.

Comment (jasongrout) [reply packages/codeeditor/src/widget.ts]: Thanks. That name change and comment made the logic clearer. I'll test.
