### PR TITLE
Fix handling of backspaces and carriage returns

### LINKED ISSUE #3881: bug: printing '\b' at start of new line causes a hard freeze
Printing the backspace escape character `\b` in certain places, such as at the start of a new line, causes a hard freeze. In a jupyterlab python notebook, if I run a cell with the code:

    print('foo')
    print('\b')

all of jupyterlab freezes and has to be reloaded. You get the same freeze if you try to backspace past an initial character on the first line:

    print('a\b\b')

On the other hand, this works:

    print('\b', end='')

though it does print a line of white space, which I'm not sure is the correct behavior.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #3881.  Fixes https://github.com/jupyterlab/jupyterlab/issues/3718.

image

### CODE REVIEW

**Comment by ian-r-rose** [comment]
This still hangs for me entering:
```python


print('foo')
print('\b')
```

**Comment by blink1073** [comment]
Wow, `.` does not match `\n`, investigating...

**Comment by blink1073** [comment]
"(The dot, the decimal point) matches any single character except line terminators".  Great.   https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#character-classes

**Comment by ian-r-rose** [comment]
Relevant function in classic: https://github.com/jupyter/notebook/blob/master/notebook/static/base/js/utils.js#L491

**Comment by blink1073** [comment]
Thanks, I went ahead and used the classic notebook functions directly.

**Comment by ian-r-rose** [comment]
FWIW, that same MDN reference cites using `[^]` to match any character including newlines.

**Comment by blink1073** [comment]
Two for one, we also fixed https://github.com/jupyterlab/jupyterlab/issues/3718.  Thanks for the reference, @ian-r-rose ✊

File: packages/outputarea/src/model.ts [hunk 1]
```diff
@@ -377,31 +377,40 @@ class OutputAreaModel implements IOutputAreaModel {
...
 
+  /**
+   * Remove characters that are overridden by backspace characters.
+   */
+  private _fixBackspace(txt: string): string {
+    let tmp = txt;
+    do {
+      txt = tmp;
+      // Cancel out anything-but-newline followed by backspace
+      tmp = txt.replace(/[^\n]\x08/gm, '');
```
Comment (jasongrout) [inline packages/outputarea/src/model.ts]: How does this handle `abcd\b\b\b\b`? Does it first match the first `\b`, delete the `d`, then recursively apply to `c\b`? Or does it match `d\b`, then match `\b\b`?

Comment (jasongrout) [reply packages/outputarea/src/model.ts]: Please not that I don't think this handling is correct either. backspace does *not* erase a character. It only moves the insertion point, like \r. Compare:

```
% echo 'a\b'
a
% echo 'a\bc'
c
```
In the first case, I moved the insertion point back to the start of the line, but I didn't overwrite a. In the second case, I moved the insertion point back to the beginning of the line and *also* overwrite `a`.

Comment (ian-r-rose) [reply packages/outputarea/src/model.ts]: In my testing, it appears to do the latter. It's a little surprising, but also the identical behavior to the classic notebook.

Comment (ian-r-rose) [reply packages/outputarea/src/model.ts]: Similar issue jupyter/notebook#2892

Comment (jasongrout) [reply packages/outputarea/src/model.ts]: Of course, we may decide we don't want that. Notice what `\r` does here - it only overwrites the single character:

```
% echo 'abc\rA' 
Abc
```
That may be problematic for people thinking that `\r` erases the line.

Comment (blink1073) [reply packages/outputarea/src/model.ts]: I'm advocating that we go with the classic notebook behavior, and only make intentional changes later if necessary.

Comment (jasongrout) [reply packages/outputarea/src/model.ts]: But to show this regex is the wrong approach, notice this in the js console:

```
"aa\b\b\b".replace(/.[\b]/gm, '')
"a"
```
You see how the `\b\b` was replaced with `''`?

Comment (ian-r-rose) [reply packages/outputarea/src/model.ts]: I agree with @blink1073 . Especially since libraries have been writing their stdout for things like progress bars to work with the classic notebook.

Comment (jasongrout) [reply packages/outputarea/src/model.ts]: > I'm advocating that we go with the classic notebook behavior, and only make intentional changes later if necessary.

Yes, compatibility (bugs and all) is more important at this point.

**Comment by blink1073** [comment]
@meeseeksdev backport to 0.31.x.

**Comment by narfanar** [comment]
The issue of multiple `\b` working as one is still an issue in jupyterlab 0.35.4 .
