### PR TITLE
fixes issue for 4257

### LINKED ISSUE #4257: New console for editor from file tab
If I want to open a new console for the file I'm working on in the file editor, I have to go in "File->New Console for Editor", but I always *instinctively* first right-click on to the file tab,  , where I can rename the file and open a new view the file, but not open a new console. Then I realise I have to go the top menu bar.

Would it be a good idea to add a "New Console for Editor" in the right-click file tab menu for editor tabs ?

EDIT : same goes for .md files : with the right-click on the file tab, I can only rename or have a new view. If I want a Rendered-markdown view, I have to right click on the file in the browser. I would expect to have the "Markdown Preview" avalaible along "Rename Markdown file" and "New View for Markdown file" in the right-click menu of the file tab.

### PR DESCRIPTION
**Pull request by Spencer-Long**
Fixes #4257 

**Screenshots**

Before:
screen shot 2018-11-17 at 3 49 49 pm

After:
screen shot 2018-11-17 at 3 50 41 pm

### CODE REVIEW

File: packages/docmanager-extension/src/index.ts [hunk 1]
```diff
@@ -746,6 +746,12 @@ function addCommands(
     selector: '[data-type="document-title"]',
     rank: 5
   });
+  // .jp-mod-current added to open console from a right click on a tab for the selected (blue line) txt file or notebook
```
Comment (ian-r-rose) [inline packages/docmanager-extension/src/index.ts]:
```suggestion
  // .jp-mod-current added so that the console-creation command is only shown on the current document.
  // Otherwise it will delegate to the wrong widget.
```

**Comment by ian-r-rose** [comment]
Thanks @Spencer-Long!
