### PR TITLE
Handle deprecated JavaScript output

### LINKED ISSUE #2666: add a warning about javascript rendering
Since the lab cannot display javascript anymore, which breaks a lot of existing notebooks, consider adding a "placeholder" javascript display utility that shows a warning that the lab won't support js output (and potentially refer to the docs). Without such a notification, the natural user reaction may be to think that the installation is broken or some settings are off and *panic*.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #2666.

<image src="https://user-images.githubusercontent.com/2096628/28225728-41f448b4-6899-11e7-897f-6de28026a218.png" width=400>

<image src="https://user-images.githubusercontent.com/2096628/28225954-f15c32da-6899-11e7-96c2-377513b4e92e.png" width=400>

### CODE REVIEW

File: packages/rendermime/src/renderers.ts [hunk 1]
```diff
@@ -59,6 +59,10 @@ function renderHTML(options: renderHTML.IOptions): Promise<void> {
   // Set the inner HTML of the host.
   host.innerHTML = source;
 
+  if (host.getElementsByTagName('script')) {
```
Comment (sccolbert) [inline packages/rendermime/src/renderers.ts]: you need a `length > 0` check here.

File: packages/rendermime/src/renderers.ts [hunk 2]
```diff
@@ -305,6 +309,10 @@ function renderMarkdown(options: renderMarkdown.IRenderOptions): Promise<void> {
     // Set the inner HTML of the host.
     host.innerHTML = content;
 
+    if (host.getElementsByTagName('script')) {
```
Comment (sccolbert) [inline packages/rendermime/src/renderers.ts]: you need a `length > 0` check here.

**Comment by sccolbert** [comment]
:shipit:
