### PR TITLE
Fix typing in editable elements inside of open shadow DOM

### LINKED ISSUE #15757: Typing into into fields that are wrapped with shadow DOM is intercepted by commands
## Description

Typing most characters into fields wrapped in shadow DOM, such as widgets generated by panel, is impossible because command shortcuts intercept the keystrokes.

## Reproduce

See https://github.com/holoviz/panel/issues/6314, but briefly:

```python
import panel as pn
pn.extension()
text_input = pn.widgets.TextInput(name='Text Input', placeholder='Enter a string starting with "A" or "B" here...')
text_input
```

and try to type <kbd>A</kbd>, <kbd>C</kbd>, <kbd>X</kbd>, etc.

Dependency-free reproducer:

```python
from IPython.display import HTML
HTML("""
<div id='shadow-test'></div>
<script>
{
const shadowHost = document.querySelector('#shadow-test');
const shadowRoot = shadowHost.attachShadow({mode: 'open'});
shadowRoot.innerHTML = '<input/>';
}
</script>
""")
```

Note: iframes work as they also isolate keystrokes.

<details>

```python
from IPython.display import HTML
HTML("<iframe srcdoc='<input>'></iframe>")
```

```python
from IPython.display import HTML
HTML("<iframe srcdoc='<div><template shadowrootmode=\"open\"><input></template></div>' />")
```

</details>

## Expected behavior

Typing works as in 4.0 and earlier.

## Context

- JupyterLab version: 4.1.0

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes #15757

## Code changes

- adds an integration test ensuring that typing works in open shadow DOM (should fail in the first commit)
- adds a new `jp-mod-readWrite` class that is added to the notebook node on focus change when the active element (or active element within active shadow DOM) is editable
- updates selectors for command-mode commands accordingly
- updates migration script and migration documentation to reflect the above
- documents the `lm-suppress-shortcuts` data attribute
- `hasActiveEditableElement` utility gets added to `DOMUtils`; this function checks the current `activeElement` (and all elements within active shadow DOM) against `:read-write` selector, but in the future could be extended for additional heuristics such as checking if the active element has a key event handler.

## User-facing changes

| Before | After |
|--|--|
| [before.webm](https://github.com/jupyterlab/jupyterlab/assets/5832902/ac7668a2-1531-4e44-b619-77478f3db358) | [after.webm](https://github.com/jupyterlab/jupyterlab/assets/5832902/c0fe312c-44e7-436e-be90-adac0b52e933) |

## Backwards-incompatible changes

None

### CODE REVIEW

File: examples/notebook/src/commands.ts [hunk 1]
```diff
@@ -396,17 +396,17 @@ export const setupCommands = (
       command: COMMAND_IDS.findPrevious
     },
     {
-      selector: '.jp-Notebook.jp-mod-commandMode :focus:not(:read-write)',
+      selector: '.jp-Notebook.jp-mod-commandMode:not(.jp-mod-readWrite) :focus',
```
Comment (krassowski) [inline examples/notebook/src/commands.ts:399]: Question: should we keep the extra `not(:read-write)`? No functional difference, but if user downgrades to 4.1.0 for some reason this would be compatible.

File: packages/mainmenu-extension/schema/plugin.json [hunk 2]
```diff
@@ -270,22 +270,22 @@
     {
       "command": "kernelmenu:interrupt",
       "keys": ["I", "I"],
-      "selector": "[data-jp-kernel-user] :focus:not(:read-write)"
+      "selector": "[data-jp-kernel-user]:not(.jp-mod-readWrite) :focus:not(:read-write)"
```
Comment (brichet) [inline packages/mainmenu-extension/schema/plugin.json:273]: Is there a reason to keep the `:not(read-write)` here ?

File: packages/notebook/src/widget.ts [hunk 3]
```diff
@@ -2771,10 +2779,26 @@ export class Notebook extends StaticNotebook {
...
+   */
+  private _updateReadWrite(): void {
+    const inReadWrite = DOMUtils.hasActiveEditableElement(this.node);
+    const hasReadWriteClass = this.node.classList.contains(READ_WRITE_CLASS);
+    if (inReadWrite && !hasReadWriteClass) {
+      this.node.classList.add(READ_WRITE_CLASS);
+    } else if (!inReadWrite && hasReadWriteClass) {
+      this.node.classList.remove(READ_WRITE_CLASS);
+    }
+  }
```
Comment (brichet) [inline packages/notebook/src/widget.ts:2793]: It can be simplified with:
```ts
this.node.classList.toggle(READ_WRITE_CLASS, inReadWrite);
```

**Review by brichet — COMMENTED** [review]
Thanks @krassowski, this looks good to me.

File: examples/notebook/src/commands.ts (hunk 1 above)
Comment (brichet) [reply examples/notebook/src/commands.ts:399]: Not sure, since both versions are documented in the extension migration guide.

File: packages/mainmenu-extension/schema/plugin.json (hunk 2 above)
Comment (krassowski) [reply packages/mainmenu-extension/schema/plugin.json:273]: Yes, I added it back because extensions may have  elements which are kernel runners but would not have time to implement `.jp-mod-readWrite`. Basically out of abundance of caution to not break anything in the wild.

File: packages/apputils/src/domutils.ts [hunk 4]
```diff
@@ -50,4 +50,22 @@ export namespace DOMUtils {
...
+  /**
+   * Check whether the active element descendant from given parent is editable.
+   * When checking active elements it includes elements in the open shadow DOM.
+   */
+  export function hasActiveEditableElement(
+    parent: Node | DocumentFragment,
+    root: ShadowRoot | Document = document
+  ): boolean {
+    const element = root.activeElement;
+    return !!(
```
Comment (gabalafou) [inline packages/apputils/src/domutils.ts:63]: For JavaScript purist points:

```suggestion
    return Boolean(
```

File: packages/console/src/widget.ts [hunk 5]
```diff
@@ -846,6 +879,20 @@ export class CodeConsole extends Widget {
...
+   * Update the console node with class indicating read-write state.
+   */
+  private _updateReadWrite(): void {
+    // TODO: de-duplicate with code in console/src/widget.ts
+    const inReadWrite = DOMUtils.hasActiveEditableElement(this.node);
+    const hasReadWriteClass = this.node.classList.contains(READ_WRITE_CLASS);
+    if (inReadWrite && !hasReadWriteClass) {
+      this.node.classList.add(READ_WRITE_CLASS);
+    } else if (!inReadWrite && hasReadWriteClass) {
+      this.node.classList.remove(READ_WRITE_CLASS);
```
Comment (gabalafou) [inline packages/console/src/widget.ts:892]: Why can't you do 

```suggestion
    this.node.classList.toggle(READ_WRITE_CLASS, inReadWrite);
```

like you do in the notebook code?

File: packages/console/src/widget.ts [hunk 6]
```diff
@@ -70,6 +70,13 @@ const CONTENT_CLASS = 'jp-CodeConsole-content';
  */
 const INPUT_CLASS = 'jp-CodeConsole-input';
 
+/**
+ * The class name added to the notebook when the focused notebook element takes keyboard input.
```
Comment (gabalafou) [inline packages/console/src/widget.ts:74]:
```suggestion
 * The class name added to the notebook when an element within it is focused and takes keyboard input, such as <input> and <div contenteditable> 
```

**Review by gabalafou — COMMENTED** [review]
I'm relieved not to see the solution with extended ("/deep/") selectors.

This is a clever and elegant solution that builds on available methods without reinventing the wheel.

File: docs/source/extension/notebook.rst [hunk 7]
```diff
@@ -175,6 +175,41 @@ The ipywidgets widget manager is an example of an extension that adds a
...
+.. code:: html
+
+   <div
+     contenteditable="false"
+     onkeydown="alert()"
+     tabindex="1"
+     data-lm-suppress-shortcuts="true"
+   >
+     Click on me and press "A" with and without "lm-suppress-shortcuts"
+   </div>
```
[the remark this answers is not in the document]
Comment (brichet) [reply docs/source/extension/notebook.rst:211]: It also works in a Notebook cell with `IPython.display.HTML()`, perhaps we can specify it.

File: docs/source/extension/notebook.rst [hunk 8]
```diff
@@ -175,6 +175,41 @@ The ipywidgets widget manager is an example of an extension that adds a
...
+enabling quick access to cell- and notebook-specific actions.
+These shortcuts are only active when the notebook is in command mode
+and the active element is non-editable,
+as signalled by absence of ``.jp-mod-readWrite`` class on the notebook node.
+This class is set if active element is editable as ascertained by matching
+to the ``:read-write`` pseudo-selector, and accounts for any elements nested
+in the open shadow DOM, but not for the closed shadow DOM nor non-editable
+elements with custom key event handlers (such as
+``<div contenteditable="false" onkeydown="alert()" tabindex="0"></div>``).
+If your output widget uses closed shadow DOM or non-editable elements with custom
```
Comment (krassowski) [inline docs/source/extension/notebook.rst:198]:
```suggestion
If your output widget (for example created with ``IPython.display.HTML``,
or created by your MIME renderer on cell output in a notebook or console)
uses closed shadow DOM or non-editable elements with custom
```

File: packages/notebook/src/widget.ts [hunk 9]
```diff
@@ -92,6 +93,13 @@ const OTHER_SELECTED_CLASS = 'jp-mod-multiSelected';
  */
 const UNCONFINED_CLASS = 'jp-mod-unconfined';
 
+/**
+ * The class name added to the notebook when the focused notebook element takes keyboard input.
```
Comment (krassowski) [inline packages/notebook/src/widget.ts:97]:
```suggestion
 * The class name added to the notebook when an element within it is focused
 * and takes keyboard input, such as focused <input> or <div contenteditable>.
```

File: packages/apputils/src/domutils.ts (hunk 4 above)
Comment (gabalafou) [reply packages/apputils/src/domutils.ts:63]: I was being facetious when I said "purist." I think it essentially comes down to a stylistic choice. But a lot of programmers just don't know about it. :)

File: packages/console/src/widget.ts [hunk 10]
```diff
@@ -846,6 +880,16 @@ export class CodeConsole extends Widget {
...
   }
 
+  /**
+   * Update the console node with class indicating read-write state.
+   */
+  private _updateReadWrite(): void {
+    // TODO: de-duplicate with code in notebook/src/widget.ts
+    const inReadWrite = DOMUtils.hasActiveEditableElement(this.node);
+    this.node.classList.toggle(READ_WRITE_CLASS, inReadWrite);
+    }
```
Comment (krassowski) [inline packages/console/src/widget.ts:890]:
```suggestion
```

**Comment by krassowski** [comment]
Is this PR still needed if we merge https://github.com/jupyterlab/jupyterlab/pull/15790? Yes, because while it also fixes the typing part it does not block commands bound to shortcuts which do not change input, e.g. Ctrl + A:

still-needed

**Review by brichet — APPROVED** [review]
