### PR TITLE
Fix cell toolbar enabled status with multiple notebooks

### LINKED ISSUE #17426: The toolbar up/down arrow status changes depending on active cell in another notebook
## Description

The move cell up/down buttons in toolbar are disabled for first/last cell respectively. It appears the logic for detecting which cell the toolbar belongs too is using active notebook, not the notebook the cell toolbar belongs too.

The content on the toolbar changing in a background notebook when navigating the focused notebook is slightly distracting.

## Reproduce

Right notebook is focused in all cases.  The left notebook should show both arrows disabled in all cases below.

When middle cell is selected in the right notebook:

Image

When first cell is selected in the right notebook:

Image

When last cell is selected in the right notebook:

Image

## Expected behavior

Correct notebook should be used as reference.

## Context

- JupyterLab version: 4.4.0b2 and earlier

### PR DESCRIPTION
**Pull request by MUFFANUJ**
## References
fixes #17426 

## User-facing changes
The ```getCurrent()``` function in notebook commands always returned tracker.currentWidget (the focused notebook), regardless of which notebook's toolbar triggered the command. Cell toolbar commands only received { toolbar: true } as arguments with no way to identify their source notebook.

## Code changes
I tried traversing the DOM at runtime to locate the parent notebook panel proved too brittle, it depended on which element happened to have focus, broke easily whenever JupyterLab’s markup changed, also attempting to modify a toolbar component’s props after it had been created is fundamentally at odds with React’s immutable props model there is no safe way to inject new arguments into an already instantiated component without forcing a re‐render.

Hence settled on a custom toolbar‐factory approach that cleanly injects the correct notebook context at creation time. Our ```CellBarExtension.createFactoryWithPanelId()``` method produces toolbar items whose commands already carry the notebook’s panelId in their argument list. We then wire up CellToolbarTracker to use this specialized factory rather than the generic toolbar setter, and enhance the command dispatcher with a small helper that reads the baked in panelId to ensure the action targets the intended notebook instance.

After changes:-

https://github.com/user-attachments/assets/7934f662-c377-4c0d-94e5-0635d319788c

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by MUFFANUJ** [comment]
@meeseeksdev tag bug

File: packages/cell-toolbar/src/celltoolbartracker.ts [hunk 1]
```diff
@@ -545,13 +552,60 @@ export class CellBarExtension implements DocumentRegistry.WidgetExtension {
...
+      // Get the original items from the default factory
+      const originalItems = this._toolbarFactory(widget);
+
+      // Create new items with modified command args
+      const modifiedItems = new ObservableList<ToolbarRegistry.IToolbarItem>();
+
+      for (const item of originalItems) {
+        if (item.widget.hasClass('jp-CommandToolbarButton')) {
+          // Get the original button
+          const originalButton = item.widget as any;
```
Comment (krassowski) [inline packages/cell-toolbar/src/celltoolbartracker.ts]: Let's avoid `any` if possible.

File: packages/cell-toolbar/src/celltoolbartracker.ts [hunk 2]
```diff
@@ -545,13 +552,60 @@ export class CellBarExtension implements DocumentRegistry.WidgetExtension {
...
 
+  /**
+   * Create a toolbar factory that includes the panel ID in command arguments
+   */
+  private createFactoryWithPanelId(
+    panel: NotebookPanel
+  ): (widget: Widget) => IObservableList<ToolbarRegistry.IToolbarItem> {
+    return (widget: Widget) => {
+      // Get the original items from the default factory
+      const originalItems = this._toolbarFactory(widget);
```
Comment (krassowski) [inline packages/cell-toolbar/src/celltoolbartracker.ts]: Could the `panelId` be passed to the `_toolbarFactory` here, instead of creating the buttons twice? Maybe the default factory should accept optional `commandArgs` argument?

File: packages/notebook-extension/src/index.ts [hunk 3]
```diff
@@ -2173,9 +2173,18 @@ function getCurrent(
...
   args: ReadonlyPartialJSONObject
 ): NotebookPanel | null {
-  const widget = args[SemanticCommand.WIDGET]
-    ? tracker.find(panel => panel.id === args[SemanticCommand.WIDGET]) ?? null
-    : tracker.currentWidget;
+  let widget: NotebookPanel | null = null;
+
+  // Check for panelId in args (used by cell toolbars)
+  if (args['panelId']) {
+    widget = tracker.find(panel => panel.id === args['panelId']) ?? null;
```
Comment (krassowski) [inline packages/notebook-extension/src/index.ts]: Two suggestions:
- we may want to use the cell toolbar on cells which are in other kinds of widgets, so I would just name it `widgetId`
- can you define the string once on `CellBarExtension` as a `const` and just refer to it in all other places (as is done for `SemanticCommand.WIDGET` below) - this makes it easier to navigate between things in IDE and less likely that to break if name is changed in place and not in another; it is ok to use explicit string in tests though.

**Review by krassowski — COMMENTED** [review]
Thank you, this works very well! Leaving some suggestions on code style and implementation.

File: packages/cell-toolbar/src/celltoolbartracker.ts (hunk 1 above)
Comment (MUFFANUJ) [reply packages/cell-toolbar/src/celltoolbartracker.ts]: yes sure

File: packages/cell-toolbar/src/celltoolbartracker.ts (hunk 2 above)
Comment (MUFFANUJ) [reply packages/cell-toolbar/src/celltoolbartracker.ts]: i actually tried this once but i was stuck here for long time, hence was looking for alternative approach but this is the correct way of handling it as creating the button twice doesn't make as it is inefficient.

File: packages/notebook-extension/src/index.ts (hunk 3 above)
Comment (krassowski) [inline packages/notebook-extension/src/index.ts]: I think this needs an update here too, ideally by importing `CellBarExtension` and passing the `WIDGET_ID_ARG`:

```suggestion
  if (args[CellBarExtension.WIDGET_ID_ARG]) {
    widget = tracker.find(panel => panel.id === args[CellBarExtension.WIDGET_ID_ARG]) ?? null;
```

File: packages/cell-toolbar/test/celltoolbartracker.spec.ts [hunk 4]
```diff
@@ -159,6 +159,38 @@ describe('@jupyterlab/cell-toolbar', () => {
...
+        // Mock the command execution to capture args
+        const executeArgs: any[] = [];
+        commands.addCommand('test:move-cell-up', {
+          execute: args => {
+            executeArgs.push(args);
+            return null;
+          },
+          isEnabled: args => {
+            // This should receive the panelId in args
+            return args.panelId === panel.id;
```
Comment (krassowski) [inline packages/cell-toolbar/test/celltoolbartracker.spec.ts]:
```suggestion
            return args.widgetId === panel.id;
```

**Comment by MUFFANUJ** [comment]
Thanks @krassowski for showing up on my mistakes

File: packages/cell-toolbar/test/celltoolbartracker.spec.ts [hunk 5]
```diff
@@ -159,6 +159,38 @@ describe('@jupyterlab/cell-toolbar', () => {
         const tracker = extension.createNew(panel);
         expect(tracker).toBeInstanceOf(CellToolbarTracker);
       });
+
+      it('should create toolbar commands with panel ID in args', async () => {
```
Comment (krassowski) [inline packages/cell-toolbar/test/celltoolbartracker.spec.ts]: This test does not test the code in `celltoolbartracker.ts`. I will try to write up a better one

**Comment by MUFFANUJ** [comment]
Thank for you help @krassowski
