### PR TITLE
Fix layout trashing when navigating notebook cell-by-cell

### LINKED ISSUE #18076: Layout trashing under heavy load when switching between cell editors
## Description

Under heavy load (when many styles and elements are present in the DOM), switching between cells in edit mode is slow and takes even ~250ms. This is noticeable to users and adds multi-second delay when navigating multiple cells up/down. This is in part due to layout trashing.

## Reproduce

1. Install multiple extensions to reflect real-world use of jupyterlab, or just use the binder I prepared for testing 4.5.0rc0: https://gist.github.com/krassowski/4c5f22e79fd7934ec6fd947f7ef2acc8
2. For easier reproduction switch windowing mode to `defer` as the `contentVisibility` mode slightly alleviates the issue already by reducing layout and style recalculation cost (but not eliminating the problematic trashing)
3. Create or upload a notebook with 500 blank cells [500_blank_cells.ipynb](https://github.com/user-attachments/files/23336590/500_blank_cells.ipynb)
4. Enter a cell editor
5. Press Up or Down arrow and hold
6. See how slow the UI reacts

Image

On recording below, I pressed the Down arrow for 2 seconds and it did not go through editors one by one but just jumped a few cells down after freezing for a few seconds:

https://github.com/user-attachments/assets/e95ea361-9b1e-4499-aa4c-b5b08415fba6

## Expected behavior

No layout trashing

## Context

- Browser and version: Chrome / Edge  141
- JupyterLab version: 4.5.0rc0

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/18076

## Code changes

- [x] Adds a test which should fail in the first commit
- [x] Limits DOM modifications to minimum by avoiding flipping `.jp-mod-readWrite` back and forth when switching cells
- [x] Applies `jp-mod-focused` before focusing the CodeMirror editor to avoid style recalculation when CodeMirror checks `scrollTop` for its own windowing logic

## User-facing changes

Much faster notebook navigation!

| Before | After |
|--|--|
| image | image |

## Backwards-incompatible changes

None

### CODE REVIEW

File: packages/codemirror/src/editor.ts [hunk 1]
```diff
@@ -289,6 +289,10 @@ export class CodeMirrorEditor implements CodeEditor.IEditor {
    * Brings browser focus to this editor text.
    */
   focus(): void {
+    // Add the focused class before the editor focus even fires
+    // to avoid layout trashing when it getcs called in response
```
Comment (krassowski) [inline packages/codemirror/src/editor.ts]:
```suggestion
    // Add the focused class before the editor focus event fires
    // to avoid layout trashing when it gets called in response
```

File: packages/notebook/src/widget.ts [hunk 2]
```diff
@@ -2545,6 +2545,9 @@ export class Notebook extends StaticNotebook {
     editor: CodeEditor.IEditor,
     location: CodeEditor.EdgeLocation
   ): void {
+    // Ensure edit mode but do not focus yet
+    this.setMode('edit', { focus: false });
```
Comment (brichet) [inline packages/notebook/src/widget.ts:2551]: Is this necessary ?
The `_edgeRequest` should be called only if we are already in edit mode.

**Review by brichet — APPROVED** [review]
Thanks @krassowski, looks good.

File: packages/notebook/src/widget.ts (hunk 2 above)
Comment (krassowski) [reply packages/notebook/src/widget.ts:2551]: Good question. I think it is assumed that the mode may change before this handler gets called. I am not sure why, but this is what happens 20 lines down in this method:

image

This addition invocation brings the action forward, reducing the number of times the DOM layout needs to be recomputed. But I agree this is not super clear.

Comment (brichet) [reply packages/notebook/src/widget.ts:2551]: Thanks for clarifying.
We can probably remove the `setMode` at the end of the function, this is not supposed to have changed between.

Comment (krassowski) [reply packages/notebook/src/widget.ts:2551]: We probably can do that - I am just apprehensive of making more changes than absolutely necessary to that logic just before a release :)

Comment (brichet) [reply packages/notebook/src/widget.ts:2551]: Let's keep it in mind for after the release.

Comment (brichet) [reply packages/notebook/src/widget.ts:2551]: Or add a comment about the need to remove it later.

File: packages/notebook/src/widget.ts
Comment (krassowski) [inline packages/notebook/src/widget.ts:2575]:
```suggestion
    // This is potentially no longer needed with the `setMode` call at the top.
    this.mode = 'edit';
```

File: packages/notebook/src/widget.ts [hunk 3]
```diff
@@ -2545,6 +2545,9 @@ export class Notebook extends StaticNotebook {
     editor: CodeEditor.IEditor,
     location: CodeEditor.EdgeLocation
   ): void {
+    // Ensure edit mode but do not focus yet
```
Comment (krassowski) [inline packages/notebook/src/widget.ts]:
```suggestion
    // Ensure edit mode but do not focus yet; we ensure the edit mode
    // with focus trigger at the end, as a side-effect of `this.mode = 'edit'`,
    // which could be simplified in the future.
```

File: packages/notebook/src/widget.ts (hunk 2 above)
Comment (krassowski) [reply packages/notebook/src/widget.ts:2551]: Done in https://github.com/jupyterlab/jupyterlab/pull/18080/commits/a1cb84c27b82c187f1a397adc13a9cd675dbb6dc

**Comment by brichet** [comment]
Thanks @krassowski
