### PR TITLE
Remove auto content type

### LINKED ISSUE #2817: Can't use FormData with ServerConnection
Hi, we use ServerConnection all over the place but wanted to upload a file. We couldn't figure out how to use ServerConnection with formData.

I got some of the way as follows:

```
export
namespace FormServerConnection {
  export
  function makeRequest(
    request: IRequest,
    settings: ServerConnection.ISettings
  ): Promise<ServerConnection.IResponse> {
    return ServerConnection.makeRequest(request, settings);
  }
  export
  function makeSettings(options?: Partial<ServerConnection.ISettings>) {
    return ServerConnection.makeSettings(options);
  }
  export
  interface IRequest {
    // Copied from ServerConnection
    url: string;
    method?: string;
    dataType?: string;
    contentType?: string;
    cache?: boolean;
    headers?: { [key: string]: string; };
    // Different so can post formData
    data?: any;
  }
}
```

but the implementation is really tied to JSON so other things still don't work e.g. the handleRequest populates the wrong content type if you leave contentType empty, which i wanted to so the browser could fill in the boundary part of the contentType.

Here's our request code that does work.
```
export function postPromise(url: string, formData: FormData) {
  // Return a new promise.
  return new Promise(function(resolve, reject) {
    // Do the usual XHR stuff
    let req = new XMLHttpRequest();
    req.open('POST', url);

    req.onload = () => {
      // This is called even on 404 etc
      // so check the status
      if (req.status === 204) {
        // Resolve the promise with the response text
        resolve(req.response);
      } else {
        // Otherwise reject with the status text
        // which will hopefully be a meaningful error
        reject(Error(req.statusText));
      }
    };

    // Handle network errors
    req.onerror = () => {
      reject(new Error('Network Error'));
    };

    // Make the request
    req.send(formData);
  });
}
```

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #2817.  Updates our handling of XHR data to match the spec: https://fetch.spec.whatwg.org/#bodyinit.  We explicitly set the `contentType` where we are sending JSON data.

### CODE REVIEW

**Comment by birdsarah** [comment]
This will be insufficient. The typing of data is such that it ONLY accepts JSON data. Even though from other code in the file it appears that that was not the intention.

**Comment by blink1073** [comment]
Updated to relax the typing.

**Comment by birdsarah** [comment]
i will test this out

File: packages/services/src/serverconnection.ts [hunk 1]
```diff
@@ -93,14 +93,14 @@ namespace ServerConnection {
...
-     * The outgoing content type, used to set the `Content-Type` header.  Defaults to `'application/json'` when there is sent data.
+     * The outgoing content type, used to set the `Content-Type` header.
      */
     contentType?: string;
 
     /**
      * The request data.
      */
-    data?: any;
+    data?: Blob | BufferSource | FormData | URLSearchParams | ReadableStream | string;
```
Comment (birdsarah) [inline packages/services/src/serverconnection.ts]: Sorry, things are very hectic, so I haven't had a chance to check this yet.

I'm confused about line 352 of this file - why, if there's no data, is the Content-Type set to be `application/json`?

Comment (blink1073) [inline packages/services/src/serverconnection.ts]: We ensure there is always data on the methods that should have a payload (otherwise it can be perceived by the server as an attack vector).  If there is no data we inject '{}' and give it a `Content-Type`.
