### PR TITLE
Fix accessibility of Keyboard Shortcuts dialog

### LINKED ISSUE #18374: [a11y] Make the Keyboard Shortcuts dialog more accessible
With a focus on keyboard navigation, one of the most important elements in JupyterLab is the Keyboard Shortcuts dialog. Any user should be able to easily access this dialog and be able to navigate it with the keyboard.

### Problem

Currently, when a user opens the Shortcuts dialog, the focus moves directly to the `Close` button. This prevents the user from being able to scroll through the table with the arrow keys. A user needs to press `Shift` + `Tab` to navigate back to the table and be able to scroll.

Video showing how a user cannot scroll the shortcuts dialog when it is first opened

Additionally, when using a screen reader, there are no announcements regarding the contents of the dialog.

#### Make the table a proper accessible table
1. Add headers so that screen readers can announce them

| Command   | Keybinding  |
| --------- | ----------- |
| Close Tab | `Alt` + `W` |

2. Add scope attribute to those headers
3. Make the title `Keyboard Shortcuts` be the caption for the table, this is needed for screen readers.

### Additional context

The tests were performed with JupyterLab v4.5.2 and the Orca Screen Reader.

I am not a regular screen reader user, so any input from someone who is more familiar with these tools would be highly valuable.

All feedback is welcomed. Thank You!

#### Potentially relevant issues

- https://github.com/jupyterlab/jupyterlab/issues/17759
- https://github.com/jupyterlab/jupyterlab/issues/15303
- https://github.com/jupyterlab/jupyterlab/issues/15497
- https://github.com/jupyterlab/jupyterlab/issues/6573

### PR DESCRIPTION
**Pull request by IsabelParedes**
## References

- Fixes #18374
- Continuation of #18517

## Code changes

- Improve keyboard navigation and screen reader support in the Keyboard Shortcuts dialog.
- Add proper table header semantics using `<th scope="col">` needed for screen readers.

## User-facing changes

- Dialog does not auto-focus on the `Close` button when opened.
- Arrow keys navigate the shortcuts table correctly.
- Tab order behaves as expected.

### Before
key-help_before

### After
key-help_after

## Backwards-incompatible changes

None

## AI usage

- **YES**: Some or all of the content of this PR was generated by AI.
- **YES**: The human author has carefully reviewed this PR and run this code (keep this PR "draft" until the answer is YES)
- AI tools and models used: Copilot

### CODE REVIEW

**Comment by IsabelParedes** [comment]
bot would you be so kind as to update galata snapshots please

**Comment by IsabelParedes** [comment]
bot would you be so kind as to update galata snapshots please

File: packages/apputils-extension/src/shortcuts.tsx [hunk 1]
```diff
@@ -184,9 +184,24 @@ export function displayShortcuts(options: IOptions) {
   }
 
   const body = (
-    <table>
-      <tbody>{bindingTable}</tbody>
-    </table>
+    <div
+      id="shortcut-dialog-table"
```
Comment (krassowski) [inline packages/apputils-extension/src/shortcuts.tsx]: Could we avoid adding id here? If not, can it be `jp-` prefixed?

```suggestion
```

File: packages/apputils-extension/src/shortcuts.tsx [hunk 2]
```diff
@@ -196,6 +211,7 @@ export function displayShortcuts(options: IOptions) {
       Dialog.cancelButton({
         label: trans.__('Close')
       })
-    ]
+    ],
+    focusNodeSelector: '#shortcut-dialog-table' // Focus the table container instead of the button
```
Comment (krassowski) [inline packages/apputils-extension/src/shortcuts.tsx]: Would this work as well?

```suggestion
    focusNodeSelector: '.jp-Shortcuts-Container' // Focus the table container instead of the button
```

Comment (IsabelParedes) [reply packages/apputils-extension/src/shortcuts.tsx]: yes, this works too

**Comment by IsabelParedes** [comment]
Hi @krassowski ,
I think the failing test is flaky. It doesn't seem related to the changes in this PR. Is it possible to trigger a rerun?
